### ISSUE TITLE
Start Mining

### ISSUE THREAD

**Issue by Bogdan2609** [Snipa22/nodejs-pool#102]
Hello, how to configure the server for mining?
All installed according to the instructions

Screenshots
http://i.imgur.com/mqojplG.jpg

**Comment by Snipa22** [comment]
Setup/deployment help can be gotten through the IRC channel.  This is not the correct location for deployment assistance.  Please ensure you've done a SQL DB sync, as well as read the wiki: https://github.com/Snipa22/nodejs-pool/wiki/Configuration-Details

I strongly suspect you left your pool's IP as 127.0.0.1

**Comment by Bogdan2609** [comment]
I try to reinstall again?
