### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Bogdan2609** [Snipa22/nodejs-pool#104]
After playing
`sudo env PATH=$PATH:`pwd`/.nvm/versions/node/v6.9.2/bin `pwd`/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/bin/pm2 startup systemd -u $CURUSER --hp `pwd`
`

Reproduced error

[[PM2] Writing init configuration in /etc/systemd/system/pm2---hp.service
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/systemd/system/pm2---hp.service
[DONE]
>>> Executing systemctl enable pm2---hp
[DONE]
>>> Executing systemctl start pm2---hp
Job for pm2---hp.service failed because the control process exited with error code. See "systemctl status pm2---hp.service" and "journalctl -xe" for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2---hp failed, see error above.]

Screenshot
http://i.imgur.com/ONBwz2u.jpg

**Comment by Snipa22** [comment]
The install scripts handle all of this for you.   You didn't start PM2 as the non-prived user before you executed this command.  If you need installation help, please ask in IRC.  Github issues are for bugs in the software.
