### ISSUE TITLE
Mined but not accepted to the pool

### ISSUE THREAD

**Issue by GGLW123** [Snipa22/nodejs-pool#105]
09:24:19:667	2b44	
09:24:19:695	2b44	赏屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯突
09:24:19:749	2b44	?           Claymore CryptoNote CPU Miner  v3.5 Beta            ?
09:24:19:751	2b44	韧屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯图
09:24:19:954	2b44	64-bit version
09:24:19:955	2b44	CPU supports AES-NI - faster mining!
09:24:19:956	2b44	Logical CPU cores: 4
09:24:19:957	2b44	Using 4 threads
09:24:19:992	2b44	scfg: 1
09:24:35:007	2b44	1 pool specified.
09:24:35:008	2b44	Press "m" key for tune mode.
09:24:35:192	3360	Stratum - connecting to 'pool.supportxmr.com' <94.130.12.30> port 5555
09:24:35:192	17f4	Stratum - connecting to 'pool.supportxmr.com' <94.130.12.30> port 5555
09:24:35:406	3360	Stratum - Connected
09:24:35:623	3360	got 381 bytes
09:24:35:624	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"b1000241-1a43-45d0-9892-da95673c3200","job":{"blob":"0505b4b2f3cc05c63e2bdad2bf7b51cab5b82e95895dda00f8f4d94e619f6f7c75ab09a7a27eca000000009f4a2fd3319ed6ae26fe0928d994603cad223ad58ac1e3aa9501d518ac14ae7c0b","job_id":"qO4PbZwULH8WsCE9fHnoPoH4B0va","target":"37894100","id":"b1000241-1a43-45d0-9892-da95673c3200"},"status":"OK"}}

09:24:35:625	3360	parse packet: 381
09:24:35:626	3360	new buf size: 0
09:24:35:627	3360	Pool Diff 1000
09:24:35:628	3360	df has same pool, skip
09:24:36:412	17f4	Stratum - Connected
09:24:36:633	17f4	got 381 bytes
09:24:36:633	17f4	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"3c0ca033-b501-47b7-84d9-a69331f3177b","job":{"blob":"0505b4b2f3cc05c63e2bdad2bf7b51cab5b82e95895dda00f8f4d94e619f6f7c75ab09a7a27eca00000000db1333eb5ca5513c21cabf23e8a7c9f306aac11b488209663988f8f448a39f110b","job_id":"NH5uXrs6+eQr9af+Nud1qgpKzJiX","target":"37894100","id":"3c0ca033-b501-47b7-84d9-a69331f3177b"},"status":"OK"}}

09:24:36:634	17f4	parse packet: 381
09:24:36:635	17f4	new buf size: 0
09:24:36:635	17f4	DevFee: Pool Diff 1000
09:24:39:391	2bcc	round found 1 shares
09:24:39:392	3360	08/23/17-09:24:39 - SHARE FOUND (target 1000) - (THR 1 of 4)
09:24:39:606	3360	got 63 bytes
09:24:39:606	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:24:39:607	3360	parse packet: 63
09:24:39:607	3360	Share accepted
09:24:39:607	3360	new buf size: 0
09:24:57:843	3034	round found 1 shares
09:24:57:858	3360	08/23/17-09:24:57 - SHARE FOUND (target 1000) - (THR 2 of 4)
09:24:58:069	3360	got 63 bytes
09:24:58:070	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:24:58:082	3360	parse packet: 63
09:24:58:082	3360	Share accepted
09:24:58:085	3360	new buf size: 0
09:25:05:013	2b44	watchdog - thread 0, hb time 547
09:25:05:013	2b44	watchdog - thread 1, hb time 1250
09:25:05:014	2b44	watchdog - thread 2, hb time 625
09:25:05:014	2b44	watchdog - thread 3, hb time 1235
09:25:14:109	3360	got 310 bytes
09:25:14:115	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"0505b4b2f3cc05c63e2bdad2bf7b51cab5b82e95895dda00f8f4d94e619f6f7c75ab09a7a27eca00000000766f4bce9385b9f4fa1e82bf308f859327b87ea1ce1bf30d9544044e86f19ea90b","job_id":"fBiT6KmUdewZYdB9x6yduZVA7QX/","target":"a0022a00","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:25:14:115	3360	parse packet: 310
09:25:14:116	3360	new buf size: 0
09:25:14:116	3360	df has same pool, skip
09:25:14:144	3360	08/23/17-09:25:14 - New job received from pool.supportxmr.com:5555
09:25:14:152	3360	Speed: 50 h/s, TotalHashes: 1K, DevHashes: 0K Mining time:
09:25:14:187	3360	00:00
09:25:35:016	2b44	watchdog - thread 0, hb time 110
09:25:35:016	2b44	watchdog - thread 1, hb time 1047
09:25:35:017	2b44	watchdog - thread 2, hb time 266
09:25:35:017	2b44	watchdog - thread 3, hb time 1453
09:25:35:296	17f4	got 310 bytes
09:25:35:297	3360	got 310 bytes
09:25:35:302	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b900000000fba0406912b86d1a9201e5fee5c3188fec09b27639dea638ed0189091935532305","job_id":"zh3qrcqWqtb0F4TNT2qEaUL/YoC6","target":"a0022a00","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:25:35:305	3360	parse packet: 310
09:25:35:306	3360	new buf size: 0
09:25:35:306	3360	df has same pool, skip
09:25:35:307	3360	08/23/17-09:25:35 - New job received from pool.supportxmr.com:5555
09:25:35:307	3360	Speed: 49 h/s, TotalHashes: 2K, DevHashes: 0K Mining time:
09:25:35:308	3360	00:01
09:25:35:296	17f4	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b9000000009c0c747a3e8d1674303fb49a9bd9b4897a5f61af94626e606aacde182acb340e05","job_id":"B8WRv78MmGbSaLNDXcppvZDN3OpA","target":"37894100","id":"3c0ca033-b501-47b7-84d9-a69331f3177b"}}

09:25:35:343	17f4	parse packet: 310
09:25:35:344	17f4	new buf size: 0
09:25:35:344	17f4	DevFee: 08/23/17-09:25:35 - New job received from pool.supportxmr.com:5555
09:25:35:938	17f4	got 310 bytes
09:25:35:938	3360	got 310 bytes
09:25:35:940	17f4	parse packet: 310
09:25:35:940	3360	parse packet: 310
09:25:35:941	17f4	DevFee: 08/23/17-09:25:35 - New job received from pool.supportxmr.com:5555
09:25:35:941	3360	df has same pool, skip
09:25:35:942	3360	08/23/17-09:25:35 - New job received from pool.supportxmr.com:5555
09:25:35:942	3360	Speed: 50 h/s, TotalHashes: 2K, DevHashes: 0K Mining time:
09:25:35:943	3360	00:01
09:25:59:147	3360	got 310 bytes
09:25:59:150	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b900000000dc3a32931e00a8920a7e7da1c029d4913bfb1a131f15173aced7c8de3feede9105","job_id":"Y540XHvkyMxnEpzH2Is+s47QPIr/","target":"b0055b00","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:25:59:151	3360	parse packet: 310
09:25:59:163	3360	new buf size: 0
09:25:59:163	3360	df has same pool, skip
09:25:59:220	3360	08/23/17-09:25:59 - New job received from pool.supportxmr.com:5555
09:25:59:236	3360	Speed: 49 h/s, TotalHashes: 4K, DevHashes: 0K Mining time:
09:25:59:261	3360	00:01
09:26:02:567	226c	round found 1 shares
09:26:02:609	3360	08/23/17-09:26:02 - SHARE FOUND (target 720) - (THR 0 of 4)
09:26:02:834	3360	got 63 bytes
09:26:02:835	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:26:02:835	3360	parse packet: 63
09:26:02:861	3360	Share accepted
09:26:02:862	3360	new buf size: 0
09:26:04:424	3034	round found 1 shares
09:26:04:457	3360	08/23/17-09:26:04 - SHARE FOUND (target 720) - (THR 2 of 4)
09:26:04:671	3360	got 63 bytes
09:26:04:671	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:26:04:672	3360	parse packet: 63
09:26:04:672	3360	Share accepted
09:26:04:686	3360	new buf size: 0
09:26:05:020	2b44	watchdog - thread 0, hb time 953
09:26:05:020	2b44	watchdog - thread 1, hb time 719
09:26:05:021	2b44	watchdog - thread 2, hb time 1563
09:26:05:022	2b44	watchdog - thread 3, hb time 1282
09:26:09:212	226c	round found 1 shares
09:26:09:245	3360	08/23/17-09:26:09 - SHARE FOUND (target 720) - (THR 0 of 4)
09:26:09:767	3360	got 63 bytes
09:26:09:769	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:26:09:770	3360	parse packet: 63
09:26:09:783	3360	Share accepted
09:26:09:791	3360	new buf size: 0
09:26:11:456	226c	round found 1 shares
09:26:11:462	3360	08/23/17-09:26:11 - SHARE FOUND (target 720) - (THR 0 of 4)
09:26:11:857	3360	got 63 bytes
09:26:11:858	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:26:11:858	3360	parse packet: 63
09:26:11:859	3360	Share accepted
09:26:11:859	3360	new buf size: 0
09:26:20:295	2808	round found 1 shares
09:26:20:319	3360	08/23/17-09:26:20 - SHARE FOUND (target 720) - (THR 3 of 4)
09:26:20:555	3360	got 63 bytes
09:26:20:556	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:26:20:556	3360	parse packet: 63
09:26:20:557	3360	Share accepted
09:26:20:557	3360	new buf size: 0
09:26:34:811	17f4	got 310 bytes
09:26:34:812	17f4	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b900000000420980f863dcd65fb82a4fd0f8a23d49b7ad753080dcf2b85e0f90a20b743cdb05","job_id":"25gQJjjVIEBHEvcc7Nf8SLTERQo9","target":"37894100","id":"3c0ca033-b501-47b7-84d9-a69331f3177b"}}

09:26:34:812	3360	got 310 bytes
09:26:34:817	17f4	new buf size: 0
09:26:34:836	17f4	DevFee: 08/23/17-09:26:34 - New job received from pool.supportxmr.com:5555
09:26:35:024	2b44	watchdog - thread 0, hb time 703
09:26:35:024	2b44	watchdog - thread 1, hb time 1094
09:26:35:025	2b44	watchdog - thread 2, hb time 1860
09:26:35:025	2b44	watchdog - thread 3, hb time 172
09:26:35:704	3034	round found 1 shares
09:26:35:706	3360	08/23/17-09:26:35 - SHARE FOUND (target 720) - (THR 2 of 4)
09:26:35:916	3360	got 63 bytes
09:26:35:916	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:26:35:917	3360	parse packet: 63
09:26:35:917	3360	Share accepted
09:26:35:918	3360	new buf size: 0
09:26:36:699	3034	round found 1 shares
09:26:36:761	3360	08/23/17-09:26:36 - SHARE FOUND (target 720) - (THR 2 of 4)
09:26:36:976	3360	got 63 bytes
09:26:36:977	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:26:36:977	3360	parse packet: 63
09:26:36:977	3360	Share accepted
09:26:36:985	3360	new buf size: 0
09:26:44:160	3360	got 310 bytes
09:26:44:170	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b9000000003e694cefd1c39b018f002cfa648c0d6b8243a63aedd1f088c4d7aa0806b5f72705","job_id":"cx6YaVk/4USgJvvCN62l/VN7oVnl","target":"02b82700","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:26:44:171	3360	parse packet: 310
09:26:44:179	3360	new buf size: 0
09:26:44:180	3360	df has same pool, skip
09:26:44:205	3360	08/23/17-09:26:44 - New job received from pool.supportxmr.com:5555
09:26:44:240	3360	Speed: 47 h/s, TotalHashes: 6K, DevHashes: 0K Mining time:
09:26:44:251	3360	00:02
09:27:05:028	2b44	watchdog - thread 0, hb time 312
09:27:05:028	2b44	watchdog - thread 1, hb time 1156
09:27:05:029	2b44	watchdog - thread 2, hb time 2265
09:27:05:029	2b44	watchdog - thread 3, hb time 2328
09:27:29:192	3360	got 310 bytes
09:27:29:193	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b900000000d0ef13423a867ea3a8b160600187247f0579cad54397d1c5331aee04eb3d158b05","job_id":"38GpaWvu2kp5m3CqBPGD86QyeY/n","target":"039d3600","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:27:29:208	3360	parse packet: 310
09:27:29:209	3360	new buf size: 0
09:27:29:209	3360	df has same pool, skip
09:27:29:214	3360	08/23/17-09:27:29 - New job received from pool.supportxmr.com:5555
09:27:29:243	3360	Speed: 46 h/s, TotalHashes: 7K, DevHashes: 0K Mining time:
09:27:29:249	3360	00:02
09:27:34:882	17f4	got 310 bytes
09:27:34:892	17f4	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b9000000009ea3eb5e4731cc4d53e8b36c42a55b5c2394a7c0cd3dbef82226b04621b4ac1a05","job_id":"wqIUvteLyeXL1VdpuTn0meTEXReo","target":"37894100","id":"3c0ca033-b501-47b7-84d9-a69331f3177b"}}

09:27:34:892	17f4	parse packet: 310
09:27:34:893	17f4	new buf size: 0
09:27:34:893	17f4	DevFee: 08/23/17-09:27:34 - New job received from pool.supportxmr.com:5555
09:27:35:033	2b44	watchdog - thread 0, hb time 593
09:27:35:033	2b44	watchdog - thread 1, hb time 31
09:27:35:033	2b44	watchdog - thread 2, hb time 781
09:27:35:034	2b44	watchdog - thread 3, hb time 828
09:27:35:159	3360	got 310 bytes
09:27:35:170	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb3f3cc05c5b7c1bff3a19ba42e6a48ae6023afa5386db156cb3c18774e46b0d839cc09b900000000b17e2b2f14a28690d4d1390027639f6deba1cf2db0c247d9725f13f06df3072805","job_id":"YteU+P5bOF6afCx4cf9L7qf2WX0N","target":"039d3600","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:27:35:171	3360	parse packet: 310
09:27:35:179	3360	new buf size: 0
09:27:35:180	3360	df has same pool, skip
09:27:35:213	3360	08/23/17-09:27:35 - New job received from pool.supportxmr.com:5555
09:27:35:244	3360	Speed: 46 h/s, TotalHashes: 8K, DevHashes: 0K Mining time:
09:27:35:284	3360	00:03
09:27:42:627	3360	got 310 bytes
09:27:42:629	17f4	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb4f3cc0599d9dadbfd94d0b105d6a690bb03ebe9f0a269437dc6c141a1473480c2ffb5d8000000002497ca7c536c053c5b0762f21939331d887f3550e97b9dea2ed6d4f8ce0e35b905","job_id":"LYnPuSVK2EbUk8d9v2V+GnR4RHFA","target":"37894100","id":"3c0ca033-b501-47b7-84d9-a69331f3177b"}}

09:27:42:629	17f4	parse packet: 310
09:27:42:630	17f4	new buf size: 0
09:27:42:630	17f4	DevFee: 08/23/17-09:27:42 - New job received from pool.supportxmr.com:5555
09:27:42:641	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb4f3cc0599d9dadbfd94d0b105d6a690bb03ebe9f0a269437dc6c141a1473480c2ffb5d800000000acdd9bcf4015ea699f0a42525cb35a0828ba28da3bac79ced2c785b74a83711105","job_id":"FJBzrksLASRgHudz9HjGyLKBhnEM","target":"039d3600","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:27:42:641	3360	parse packet: 310
09:27:42:642	3360	new buf size: 0
09:27:42:642	3360	df has same pool, skip
09:27:42:663	3360	08/23/17-09:27:42 - New job received from pool.supportxmr.com:5555
09:27:42:685	3360	Speed: 47 h/s, TotalHashes: 8K, DevHashes: 0K Mining time:
09:27:42:717	3360	00:03
09:27:47:638	3034	round found 1 shares
09:27:47:654	3360	08/23/17-09:27:47 - SHARE FOUND (target 1200) - (THR 2 of 4)
09:27:47:870	3360	got 63 bytes
09:27:47:871	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:27:47:871	3360	parse packet: 63
09:27:47:871	3360	Share accepted
09:27:47:872	3360	new buf size: 0
09:28:05:037	2b44	watchdog - thread 0, hb time 984
09:28:05:037	2b44	watchdog - thread 1, hb time 875
09:28:05:038	2b44	watchdog - thread 2, hb time 1265
09:28:05:039	2b44	watchdog - thread 3, hb time 1656
09:28:13:621	226c	round found 1 shares
09:28:13:650	3360	08/23/17-09:28:13 - SHARE FOUND (target 1200) - (THR 0 of 4)
09:28:13:866	3360	got 63 bytes
09:28:13:867	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:28:13:886	3360	parse packet: 63
09:28:13:893	3360	Share accepted
09:28:13:905	3360	new buf size: 0
09:28:14:214	3360	got 310 bytes
09:28:14:229	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb4f3cc0599d9dadbfd94d0b105d6a690bb03ebe9f0a269437dc6c141a1473480c2ffb5d800000000ecfe89f1e88223e9a4189af40114998fa83942fa0074012f6d54648b529fa52605","job_id":"j7mbPgqn3VMGmmvJCapwJ853yifg","target":"98cd3200","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:28:14:230	3360	parse packet: 310
09:28:14:230	3360	new buf size: 0
09:28:14:230	3360	df has same pool, skip
09:28:14:254	3360	08/23/17-09:28:14 - New job received from pool.supportxmr.com:5555
09:28:14:275	3360	Speed: 47 h/s, TotalHashes: 10K, DevHashes: 0K Mining time:
09:28:14:299	3360	00:03
09:28:35:041	2b44	watchdog - thread 0, hb time 843
09:28:35:041	2b44	watchdog - thread 1, hb time 1250
09:28:35:042	2b44	watchdog - thread 2, hb time 1375
09:28:35:042	2b44	watchdog - thread 3, hb time 453
09:28:59:240	3360	got 310 bytes
09:28:59:253	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb4f3cc0599d9dadbfd94d0b105d6a690bb03ebe9f0a269437dc6c141a1473480c2ffb5d8000000008e429ac5901ee88050ebd049ec466afd4e4b6f211b2359a9c675bb5ce3e747a505","job_id":"de5135Emt5g2PTNz6IsmGbKmWWuR","target":"4d6a3e00","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:28:59:257	3360	parse packet: 310
09:28:59:258	3360	new buf size: 0
09:28:59:258	3360	df has same pool, skip
09:28:59:280	3360	08/23/17-09:28:59 - New job received from pool.supportxmr.com:5555
09:28:59:295	3360	Speed: 47 h/s, TotalHashes: 12K, DevHashes: 0K Mining time:
09:28:59:326	3360	00:04
09:29:05:045	2b44	watchdog - thread 0, hb time 469
09:29:05:045	2b44	watchdog - thread 1, hb time 1359
09:29:05:046	2b44	watchdog - thread 2, hb time 938
09:29:05:046	2b44	watchdog - thread 3, hb time 641
09:29:34:973	17f4	got 310 bytes
09:29:34:980	17f4	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb4f3cc0599d9dadbfd94d0b105d6a690bb03ebe9f0a269437dc6c141a1473480c2ffb5d800000000d5cdfa66afd1e78c31bf44aa33d55495c5c991aec22e197f72b0bc158b8ca41f05","job_id":"3hdusw4lg+RutuZEgmOpUU8YJlco","target":"37894100","id":"3c0ca033-b501-47b7-84d9-a69331f3177b"}}

09:29:34:981	17f4	parse packet: 310
09:29:34:981	3360	df has same pool, skip
09:29:34:981	17f4	new buf size: 0
09:29:34:982	3360	08/23/17-09:29:34 - New job received from pool.supportxmr.com:5555
09:29:35:015	3360	Speed: 47 h/s, TotalHashes: 14K, DevHashes: 0K Mining time:
09:29:35:048	2b44	watchdog - thread 0, hb time 453
09:29:35:048	2b44	watchdog - thread 1, hb time 156
09:29:35:049	2b44	watchdog - thread 2, hb time 1031
09:29:35:049	2b44	watchdog - thread 3, hb time 844
09:29:35:057	3360	00:04
09:29:44:268	3360	got 310 bytes
09:29:44:268	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"05058eb4f3cc0599d9dadbfd94d0b105d6a690bb03ebe9f0a269437dc6c141a1473480c2ffb5d800000000f1e09b7d4bcc10213deb962143e403d5b5c0c3d913713c96402902c72e53687705","job_id":"1N3RvGx9n9Z7rYzObBrtySWheCTV","target":"59d14800","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:29:44:269	3360	parse packet: 310
09:29:44:277	3360	new buf size: 0
09:29:44:305	3360	df has same pool, skip
09:29:44:358	3360	08/23/17-09:29:44 - New job received from pool.supportxmr.com:5555
09:29:44:405	3360	Speed: 47 h/s, TotalHashes: 14K, DevHashes: 0K Mining time:
09:29:44:438	3360	00:05
09:30:05:053	2b44	watchdog - thread 0, hb time 875
09:30:05:053	2b44	watchdog - thread 1, hb time 469
09:30:05:054	2b44	watchdog - thread 2, hb time 2172
09:30:05:054	2b44	watchdog - thread 3, hb time 1656
09:30:08:485	226c	round found 1 shares
09:30:08:519	3360	08/23/17-09:30:08 - SHARE FOUND (target 900) - (THR 0 of 4)
09:30:08:734	3360	got 63 bytes
09:30:08:755	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:30:08:767	3360	parse packet: 63
09:30:08:782	3360	Share accepted
09:30:08:783	3360	new buf size: 0
09:30:09:709	17f4	got 310 bytes
09:30:09:740	17f4	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"0505a0b5f3cc058ea6a97e496d68345af7dbb7d6067a3f479f88c95ef3bdd2699a20898b2305e6000000007400388c9b43d151a5620b4bd9d328ada24093e560129f39d8170feb19f43a100c","job_id":"LV+CuLzIOao+FkDqDJg7QE0NRbS2","target":"37894100","id":"3c0ca033-b501-47b7-84d9-a69331f3177b"}}

09:30:09:741	17f4	parse packet: 310
09:30:09:741	17f4	new buf size: 0
09:30:09:748	17f4	DevFee: 08/23/17-09:30:09 - New job received from pool.supportxmr.com:5555
09:30:29:293	3360	got 310 bytes
09:30:29:294	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"0505a0b5f3cc058ea6a97e496d68345af7dbb7d6067a3f479f88c95ef3bdd2699a20898b2305e600000000dca0ed32c8148dea6c843e3fbf79f5f0070e5289e3535b9270cd54a447a209b20c","job_id":"sjTwbZ6hYGCxAfd9lzCEP3p2U2uS","target":"28544b00","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:30:29:294	3360	parse packet: 310
09:30:29:322	3360	new buf size: 0
09:30:29:332	3360	df has same pool, skip
09:30:29:367	3360	08/23/17-09:30:29 - New job received from pool.supportxmr.com:5555
09:30:29:401	3360	Speed: 46 h/s, TotalHashes: 16K, DevHashes: 0K Mining time:
09:30:29:424	3360	00:05
09:30:34:959	17f4	got 310 bytes
09:30:34:968	3360	got 310 bytes
09:30:34:974	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"0505a0b5f3cc058ea6a97e496d68345af7dbb7d6067a3f479f88c95ef3bdd2699a20898b2305e600000000435c51e553a094faaba73ffa527752c24781ce2fb5583530f80240fde55048a70c","job_id":"CL0CNXAPPNKNu9igO2VqIOTk41Sp","target":"28544b00","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:30:34:975	3360	parse packet: 310
09:30:34:976	3360	new buf size: 0
09:30:34:976	3360	df has same pool, skip
09:30:34:976	3360	08/23/17-09:30:34 - New job received from pool.supportxmr.com:5555
09:30:34:977	17f4	parse packet: 310
09:30:34:977	3360	00:05
09:30:34:978	17f4	DevFee: 08/23/17-09:30:34 - New job received from pool.supportxmr.com:5555
09:30:35:057	2b44	watchdog - thread 0, hb time 1641
09:30:35:057	2b44	watchdog - thread 1, hb time 1797
09:30:35:058	2b44	watchdog - thread 2, hb time 969
09:30:35:058	2b44	watchdog - thread 3, hb time 719
09:30:42:305	226c	round found 1 shares
09:30:42:335	3360	08/23/17-09:30:42 - SHARE FOUND (target 870) - (THR 0 of 4)
09:30:42:546	3360	got 63 bytes
09:30:42:573	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:30:42:573	3360	parse packet: 63
09:30:42:602	3360	Share accepted
09:30:42:607	3360	new buf size: 0
09:30:55:715	3034	round found 1 shares
09:30:55:744	3360	08/23/17-09:30:55 - SHARE FOUND (target 870) - (THR 2 of 4)
09:30:55:959	3360	got 63 bytes
09:30:55:979	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:30:55:980	3360	parse packet: 63
09:30:55:992	3360	Share accepted
09:30:55:999	3360	new buf size: 0
09:31:05:061	2b44	watchdog - thread 0, hb time 344
09:31:05:061	2b44	watchdog - thread 1, hb time 47
09:31:05:062	2b44	watchdog - thread 2, hb time 47
09:31:05:062	2b44	watchdog - thread 3, hb time 282
09:31:12:967	226c	round found 1 shares
09:31:12:985	3360	08/23/17-09:31:12 - SHARE FOUND (target 870) - (THR 0 of 4)
09:31:13:202	3360	got 63 bytes
09:31:13:203	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:31:13:213	3360	parse packet: 63
09:31:13:214	3360	Share accepted
09:31:13:214	3360	new buf size: 0
09:31:14:320	3360	got 310 bytes
09:31:14:325	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"0505a0b5f3cc058ea6a97e496d68345af7dbb7d6067a3f479f88c95ef3bdd2699a20898b2305e600000000c2e14dac508488544df9cc21d043c205f3899010e1a17047d842614ac4067b0c0c","job_id":"gN4HrOBgC7YL9MHFAIllYb04+Fqq","target":"44444400","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:31:14:325	3360	parse packet: 310
09:31:14:345	3360	new buf size: 0
09:31:14:346	3360	df has same pool, skip
09:31:14:379	3360	08/23/17-09:31:14 - New job received from pool.supportxmr.com:5555
09:31:14:394	3360	Speed: 47 h/s, TotalHashes: 18K, DevHashes: 0K Mining time:
09:31:14:417	3360	00:06
09:31:18:186	3360	got 310 bytes
09:31:18:187	17f4	got 310 bytes
09:31:18:188	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"0505e5b5f3cc05bd8cbe8c679d74ba0937962a2b2e2b80f9379c28813229a368530393ee4ff6bc0000000083e5b99c07321c545ae2419d4d722af2e99854c4cb122a0ff87df5c3c5eb4a9f09","job_id":"Q5oULASkicgjKjyQDMWOSeXnM3vv","target":"44444400","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:31:18:200	3360	parse packet: 310
09:31:18:203	3360	new buf size: 0
09:31:18:222	3360	df has same pool, skip
09:31:18:234	3360	08/23/17-09:31:18 - New job received from pool.supportxmr.com:5555
09:31:18:256	3360	Speed: 47 h/s, TotalHashes: 18K, DevHashes: 0K Mining time:
09:31:18:292	3360	00:06
09:31:24:393	2bcc	round found 1 shares
09:31:24:444	3360	08/23/17-09:31:24 - SHARE FOUND (target 960) - (THR 1 of 4)
09:31:24:677	3360	got 63 bytes
09:31:24:678	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:31:24:690	3360	parse packet: 63
09:31:24:724	3360	Share accepted
09:31:24:726	3360	new buf size: 0
09:31:28:274	2808	round found 1 shares
09:31:28:303	3360	08/23/17-09:31:28 - SHARE FOUND (target 960) - (THR 3 of 4)
09:31:28:524	3360	got 63 bytes
09:31:28:525	3360	buf: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}

09:31:28:525	3360	parse packet: 63
09:31:28:543	3360	Share accepted
09:31:28:571	3360	new buf size: 0
09:31:35:066	2b44	watchdog - thread 0, hb time 1266
09:31:35:066	2b44	watchdog - thread 1, hb time 1829
09:31:35:067	2b44	watchdog - thread 2, hb time 922
09:31:35:067	2b44	watchdog - thread 3, hb time 1469
09:31:59:345	3360	got 310 bytes
09:31:59:352	3360	buf: {"jsonrpc":"2.0","method":"job","params":{"blob":"0505e5b5f3cc05bd8cbe8c679d74ba0937962a2b2e2b80f9379c28813229a368530393ee4ff6bc0000000070f2b8eefe85fbb5951f6b5a7507b0ec599ba4dd01a039160f69a1c7df64a35b09","job_id":"dIGK9U105b/Ge60XFqaC/jE34qsz","target":"ae324200","id":"b1000241-1a43-45d0-9892-da95673c3200"}}

09:31:59:353	3360	parse packet: 310
09:31:59:353	3360	new buf size: 0
09:31:59:354	3360	df has same pool, skip
09:31:59:381	3360	08/23/17-09:31:59 - New job received from pool.supportxmr.com:5555
09:31:59:408	3360	Speed: 47 h/s, TotalHashes: 20K, DevHashes: 0K Mining time:
09:31:59:422	3360	00:07
09:32:05:072	2b44	watchdog - thread 0, hb time 641
09:32:05:072	2b44	watchdog - thread 1, hb time 1485
09:32:05:073	2b44	watchdog - thread 2, hb time 1235
09:32:05:073	2b44	watchdog - thread 3, hb time 63

**Comment by Snipa22** [comment]
Nothing I see here says you're not mining to a pool.  Please contact pool-ops directly, this is not a channel for pool-support.
