### ISSUE TITLE
miner error

### ISSUE THREAD

**Issue by coolsd** [Snipa22/nodejs-pool#110]
![1](https://user-images.githubusercontent.com/7413058/30061415-d825c89e-9279-11e7-9e6d-2b2dd5af2d22.png)
![2](https://user-images.githubusercontent.com/7413058/30061432-e91645b6-9279-11e7-8278-a09586c2103f.png)

**Comment by Snipa22** [comment]
Likely a misconfiguration within the pool.  Error in remote comms would suggest an issue with the leaf API address in your database.
