### ISSUE TITLE
Hash statistics are inaccurate

### ISSUE THREAD

**Issue by coolsd** [Snipa22/nodejs-pool#115]
![3](https://user-images.githubusercontent.com/7413058/30108507-33dcb498-9335-11e7-8e08-8456ecbf4ca7.png)
![4](https://user-images.githubusercontent.com/7413058/30108634-9893905a-9335-11e7-9cfb-399dc23ae380.png)

**Comment by Snipa22** [comment]
All hash averages on the pool are calculated from your submitted shares.  These will normally be below the speeds listed by your miners.  This is nothing unusual or unexpected.

**Comment by coolsd** [comment]
Very inaccurate
