### ISSUE TITLE
The pool  dos not payment

### ISSUE THREAD

**Issue by coolsd** [Snipa22/nodejs-pool#121]
![7](https://user-images.githubusercontent.com/7413058/30247159-2a5ca94c-9640-11e7-9350-1eac567db99f.png)
![8](https://user-images.githubusercontent.com/7413058/30247161-30075590-9640-11e7-9386-497d3050fe33.png)

![11](https://user-images.githubusercontent.com/7413058/30247164-3745d9c6-9640-11e7-9b06-6cfecffe62d8.png)

**Comment by Snipa22** [comment]
Other than the fact I'd tell you that it's nuts to post your miner's addresses like this.  That user is using an exchange/payment ID based address.  Any address with a period in it, contains a PaymentID.

**Comment by coolsd** [comment]
Why don't you pay for it?
