### ISSUE TITLE
exit code: 1

### ISSUE THREAD

**Issue by Obli-One** [Snipa22/nodejs-pool#127]
Hello

first off thanks for the installer, this must have taken alot of work.

I've run the installer a few times on a linode  running the correct unbuntu version and each time right at the end I get this error

>>> Executing systemctl start pm2-usernamehere
Job for pm2-sernamehere.service failed because the control process exited with error code. See "systemctl status pm2-usernamehere.service" and "journalctl -xe" for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-usernamehere failed, see error above.

is this an error / bug?

strangely I can see the pm2 screens a few times showing the api instance but cant interact with it

**Comment by Obli-One** [comment]
sorry am closing this as i've figured it out, all seems to be working.

thanks again for the wicked installer and the work you've put into this

**Comment by mxjoe** [comment]
Is it working although it shows the errors? Cause mine shows this error too and is not working.
