### ISSUE TITLE
Cant get into Admin

### ISSUE THREAD

**Issue by uaktags** [Snipa22/nodejs-pool#135]
So a number of things appear to not be found/loaded.

- /#/admin only redirects me back to /#/home
- /admin.html shows the login, but you can't login with Administrator : Password123 because /authenticate fails to load.
- /config appears to want to load on the home page but it too fails to load

**Comment by camthegeek** [comment]
I've had no issues with /admin.html with the default settings.

However, if you reset the password to something else, it seems to create an issue as user name and password combination are invalid.

Creating a second administrative user is the route to go here. Use non-obvious administrative names (admin, root, administrator) for security reasons. All works fine.

**Comment by uaktags** [comment]
Yea, I can't get past the login screen. It does a POST to /authenticate and that is a 404 Not Found.

**Comment by uaktags** [comment]
issue is resolved now after RemoteShare is setup properly. Uses the Administrator account you create (or the default if you didn't delete it.)
