### ISSUE TITLE
wallet.wallet2	src/wallet/wallet2.cpp:660	Transaction extra has unsupported format

### ISSUE THREAD

**Issue by thisjrodriguez** [Snipa22/nodejs-pool#137]
my wallet rpc say:
wallet.wallet2	src/wallet/wallet2.cpp:660	Transaction extra has unsupported format

**Comment by boulosda** [comment]
I am also getting the same error, @thisjrodriguez, did you end up solving it?

**Comment by Snipa22** [comment]
Is this for XMR?  Aeon?  What coin?

**Comment by javietanh** [comment]
I'm getting that message too. that's for XMR wallet.
Cheers

**Comment by TrippySquidsman** [comment]
Same here, XMR wallet. Anything I can do to help?

**Comment by vitorgatti** [comment]
Same here:

`2|monero-w | 2017-11-08 15:57:51.156    [RPC0]  WARN    wallet.wallet2  src/wallet/wallet2.cpp:660      Transaction extra has unsupported format: <5f31db50dd3631eafc650023129dd1228dfd607c4cf4bef30f124bfe787a2e95>`

**Comment by christian198** [comment]
I'm getting exactly the same error with XMR.

**Comment by mxjoe** [comment]
Hi,

I am getting this message, too. I pulled and updated to latest code but problem still exists.

`2|monero-w | 2017-11-13 01:43:22.097	[RPC0]	WARN 	wallet.wallet2	src/wallet/wallet2.cpp:660	Transaction extra has unsupported format: <c...d>`
`2|monero-w | 2017-11-13 02:06:06.278	[RPC0]	WARN 	wallet.wallet2	src/wallet/wallet2.cpp:660	Transaction extra has unsupported format: <8...1>`
`2|monero-w | 2017-11-13 02:10:51.084	[RPC0]	WARN 	wallet.wallet2	src/wallet/wallet2.cpp:660	Transaction extra has unsupported format: <8...1>`

**Comment by vitorgatti** [comment]
try to remove the argument --restricted-rpc from monero.service and see if it works now

**Comment by TrippySquidsman** [comment]
I'm so sorry if this is a dumb question but what is monero.service? I do remember using --restricted-rpc at some point but can't recall where.

**Comment by vitorgatti** [comment]
it's the file stored at /lib/systemd/system/monero.service

**Comment by TrippySquidsman** [comment]
I don't have one? I've launched monero-wallet-rpc without using the --restricted-rpc arguement (that's where I was using it), however my dameon is still syncing as I haven't run the pool in a few days so I won't be of any use for a while...

**Comment by vitorgatti** [comment]
it's not monero-wallet-rpc, it's monerod

**Comment by CollusionPool** [comment]
`Transaction extra has unsupported format`

Also an error, and what it affects and how critical a mistake
