### ISSUE TITLE
Monerod Bind IP 127.0.0.01 for port 18081

### ISSUE THREAD

**Issue by rjclarkewp007** [Snipa22/nodejs-pool#138]
Please can someone help explain to me how I can change the bind IP of monerod RPC daemon to my external IP of the server and not to localhost?
Would have been simple if i installed monerod myself, but I used the script so now i'm not sure how to do this and how the service starts up automatically.

thanks!

**Comment by vitorgatti** [comment]
`/lib/systemd/system/monero.service`

this is the file created by the deploy.bash script that autostarts the monerod service

and the default command is:

`/usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc`

**Comment by rjclarkewp007** [comment]
Thanks! I found it eventually, but pool doesn't start up if I change the IP. I figure you also need to add:
--confirm-external-bind
