### ISSUE TITLE
What exactly does the "testnet=1" flag do?

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#139]
I'm trying to build a nodejs-pool and I successfully brought it up on testnet mode, but the payments are very odd, if there's only one miner it gets paid, if another miner joins the pool, the payments stop happening forever until I restart the pool (and the pool's wallet keeps receiving a lot of coins from the found blocks, not paying the miners after it's rebooted).

How does the option on the SQL "testnet=0/1" work?

**Comment by Snipa22** [comment]
This just enables the testnet address checker:
https://github.com/Snipa22/nodejs-pool/blob/ce1f81c7cb1afea1f0699424c2dfc502bbdb47ae/lib/coins/xmr.js#L36

If there's an error in payments with multiple miners at once, run the payment process in debug mode:  DEBUG=* node init.js --module=payments
And it'll spit out the response from the wallet to you with the error.

**Comment by vitorgatti** [comment]
Thanks
