### ISSUE TITLE
Sockets break!

### ISSUE THREAD

**Issue by thisjrodriguez** [Snipa22/nodejs-pool#140]
I have this error when very users mining from proxy

6|pool     | (Worker 3 - 30549) Excessive packet size from: 161.222.117.154 
6 |pool     | 2017-10-24 19:59 +00:00: (Worker 5 - 30561) Socket Error from  161.222.117.15 Error: Error: write EPIPE

**Comment by Snipa22** [comment]
Stop using Atrides' proxy.  This is a bug with the fact Atrides doesn't limit it's max packet size.

**Comment by thisjrodriguez** [comment]
i use this: https://github.com/cazala/coin-hive-stratum 

i can limit packet size, i work in this
