### ISSUE TITLE
pool alway show this debug info.

### ISSUE THREAD

**Issue by javietanh** [Snipa22/nodejs-pool#143]
Dear,

My pool running without problems but when i check the console of pool it always show this line, is this normal?
- pm2 logs pool --lines 1000
>pool>(Master) Queue debug state: 0 items in the queue o items being processed.

What does this line mean?

Cheers

**Comment by vitorgatti** [comment]
are there miners on your pool?

**Comment by javietanh** [comment]
yup, all miner work well no error showing, hash submitted. worry if any problem with the pool because over 16 days without block :(

**Comment by vitorgatti** [comment]
you can try in testnet first, even with 50H/s you find a block every 10 minutes, it's great to see if your pool is working as intended.

**Comment by Snipa22** [comment]
pool>(Master) Queue debug state: 0 items in the queue o items being processed.

This is a listing of the number of items in the queue to be submitted to the remoteShare system.  If you are fully caught up, this should show 0/0.
