### ISSUE TITLE
Log Warning: Malformed message

### ISSUE THREAD

**Issue by mxjoe** [Snipa22/nodejs-pool#146]
Hi,

my pool gets a "Malformed message" every several seconds for different workers. What does this mean exactly? Below is an example:

9|pool     | 2017-11-06 20:36 +00:00: (Worker 4 - 1500) Malformed message from 93.123.85.23 Message: ���Y�@B|

**Comment by Snipa22** [comment]
> 9|pool | 2017-11-06 20:36 +00:00: (Worker 4 - 1500) Malformed message from 93.123.85.23 Message: ���Y�@b|

This is from someone scanning your pool and hitting the open port, sending invalid data.

**Comment by mxjoe** [comment]
This is a relevant security risk, right? What can I do to prevent this/harden the pool.

**Comment by Snipa22** [comment]
No, this is expected, and why the pool pops them out as malformed.

**Comment by mxjoe** [comment]
Okay, thanks. So I will ignore them from now on.
