### ISSUE TITLE
API throws errors

### ISSUE THREAD

**Issue by M5M400** [Snipa22/nodejs-pool#15]
6|api      | 2017-02-14 10:40 +00:00: Unhandled rejection TypeError: Cannot read property 'pool_type' of undefined
6|api      |     at /home/xmrpool/nodejs-pool/lib/api.js:215:41
6|api      |     at tryCatcher (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
6|api      |     at Promise._settlePromiseFromHandler (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
6|api      |     at Promise._settlePromise (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
6|api      |     at Promise._settlePromise0 (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
6|api      |     at Promise._settlePromises (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
6|api      |     at Async._drainQueue (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
6|api      |     at Async._drainQueues (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
6|api      |     at Immediate.Async.drainQueues (/home/xmrpool/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
6|api      |     at runCallback (timers.js:637:20)
6|api      |     at tryOnImmediate (timers.js:610:5)
6|api      |     at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by Snipa22** [comment]
I see your site is up and good?  I'm closing this out unless there's another issue going forwards!
