### ISSUE TITLE
TypeError: Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by ArqTras** [Snipa22/nodejs-pool#150]
(Worker 1 - 15089) Started server on port: 9000
(Worker 2 - 15095) Started server on port: 9000
(Worker 3 - 15096) Started server on port: 3333
(Worker 3 - 15096) Started server on port: 5555
(Worker 3 - 15096) Started server on port: 7777
(Worker 3 - 15096) Started server on port: 9000
(Master) Queue debug state: 0 items in the queue 0 items being processed
(Master) Queue debug state: 0 items in the queue 0 items being processed
/home/arek/nodejs-pool/lib/pool.js:819
        global.mysql.query("UPDATE pools SET blockIDTime = now(), blockID = ? where id = ?", [activeBlockTemplate.height, global.config.pool_id]);
                                                                                                                 ^

TypeError: Cannot read property 'height' of undefined
    at Timeout._onTimeout (/home/arek/nodejs-pool/lib/pool.js:819:114)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by javietanh** [comment]
Hi, i guess that's your monero demon not running correctly. check the demon if it's full synch with the network and running.

Cheers

**Comment by ArqTras** [comment]
Default from deploy batch installation 

sudo systemctl status monero.service
● monero.service - Monero Daemon
   Loaded: loaded (/lib/systemd/system/monero.service; enabled; vendor preset: enabled)
   Active: active (running) since czw 2017-11-09 15:42:17 UTC; 5h 6min ago
  Process: 1268 ExecStart=/usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc (code=exited, status=0/SUCCESS)
    Tasks: 18
   Memory: 6.3G
      CPU: 25min 7.723s
   CGroup: /system.slice/monero.service
           └─1449 /usr/local/src/monero/build/release/bin/monerod --rpc-bind-ip 127.0.0.1 --detach --restricted-rpc

lis 09 15:42:16 mine systemd[1]: Starting Monero Daemon...
lis 09 15:42:17 mine monerod[1268]: 2017-11-09 15:42:17.278            7f42c8bbd740        INFO         global        src/daemon/main.cpp:279        Monero 'Helium Hydr
lis 09 15:42:17 mine monerod[1268]: Forking to background...
lis 09 15:42:17 mine systemd[1]: Started Monero Daemon.

**Comment by ArqTras** [comment]
The same problem with aeon. Daemon full synced, wallet full synced.
TypeError: Cannot read property 'height' of undefined
at Timeout._onTimeout (/home/arek/nodejs-pool/lib/pool.js:819:114)

**Comment by newhelp** [comment]
If you solve the problem then tell me how

**Comment by ArqTras** [comment]
Put your server generated wallet address (no ip only wallet address Wmtxxxxx) in to sql config 
47 : address string pool there should be wallet address

**Comment by ArqTras** [comment]
To solve problem remove ssl port 9000 from config
