### ISSUE TITLE
npm update

### ISSUE THREAD

**Issue by ArqTras** [Snipa22/nodejs-pool#151]
Is this normal issue.
It always build with warns 

 cryptonote-util@0.0.3 install /home/arek/nodejs-pool/node_modules/cryptonote-util
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/arek/nodejs-pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }

**Comment by ArqTras** [comment]
also missing boolberry

**Comment by Snipa22** [comment]
Yes, this is normal, as for boolberry, assuming it's moderately up to date, this should be working.
