### ISSUE TITLE
iOS App for watching pool/personal stats

### ISSUE THREAD

**Issue by mxjoe** [Snipa22/nodejs-pool#152]
I think about programming a basic iOS app for checking some data like pool and personal hashrate, total due and total paid. Is there a way to get such data through an API? @Snipa22 do you have a better idea?

**Comment by Snipa22** [comment]
Full API specs can be found at: https://cryptonote-pool-api.restlet.io/

**Comment by mxjoe** [comment]
Thanks, this resource was new to me.
