### ISSUE TITLE
No PPLNS payout in log

### ISSUE THREAD

**Issue by stlobe** [Snipa22/nodejs-pool#155]
2|blockMan | 2017-11-10 14:20 +08:00: Performing PPS payout on block: 1439631 Block Value: 5.939927232631
2|blockMan | 2017-11-10 14:20 +08:00: PPS payout cycle complete on block: 1439631 Block Value: 5.939927232631 Block Payouts: 0 Payout Percentage: 0%
2|blockMan | 2017-11-10 14:20 +08:00: Scan complete, unlocking remainder of blockManager functionality.
2|blockMan | 2017-11-10 14:22 +08:00: Performing PPS payout on block: 1439632 Block Value: 5.939915903119
2|blockMan | PPS payout cycle complete on block: 1439632 Block Value: 5.939915903119 Block Payouts: 0 Payout Percentage: 0%
2|blockMan | Scan complete, unlocking remainder of blockManager functionality.

I mined more than 1 month with 5 KH/s but no block found and no PPLNS payout was shown in log file.  Is it normal?
I am not sure any config are missed. Any hint is appreciated.

**Comment by javietanh** [comment]
Hi guys,

Many duplicate job received, reconnect message showing the pool logs. and each time the miner will auto reconnect (no active pool, stop mining) is this normal?

I'm same with you with about 4kh/s and over 1 month without any block. not sure when i could found the block happen :)

Cheers

**Comment by mxjoe** [comment]
(PPLNS) payout can only happen when a block was found, right?! So as you haven't found a block there cannot be a payout.

**Comment by stlobe** [comment]
Oh...Thank you. I am just thinking something wrong or missed in my config file.
