### ISSUE TITLE
Limit worker!

### ISSUE THREAD

**Issue by javietanh** [Snipa22/nodejs-pool#157]
Hi, 

My small pool and only 1 miner, can i limit only 1 worker on pool? currently, i saw the pool set with 2 worker running together and when i check the miner terminal the duplicate shared and disconnect always show in about 5 minutes even i remove all the overclock of my rig (the cpu mining also have duplicate share and reconnect)

Cheers

**Comment by RlyehDoom** [comment]
I can second this... I noticed too on my pool some errors with duplicated shares trying to be inserted on mysql.

**Comment by javietanh** [comment]
Hi guys,

I found out: the number of worker is base on the number of CPU cores. if you have 1 core then the pool assigned 1 worker, when you have 10 cores then it will have 10 worker.

Cheers
