### ISSUE TITLE
monerod running with --restricted-rpc makes monero-wallet-rpc error "failed to get random outs"

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#159]
Even if `monero-wallet-rpc` is running with the `--trusted-daemon` argument, the pool can't make the payments because the error `Issue making payments{"code":-4,"message":"failed to get random outs"}` shows up.

The only way my pool makes the payments correctly is if I remove the `--restricted-rpc` argument in `/lib/systemd/system/monero.service`

Is this intended or a bug?

**Comment by Snipa22** [comment]
This is an issue with the monero daemon, not with any of the code running.  Restricted-RPC is a security measure, to keep your XMR instance from being shut down by a RPC command.
