### ISSUE TITLE
MAILGUN not working

### ISSUE THREAD

**Issue by RlyehDoom** [Snipa22/nodejs-pool#160]
I have created a MAILGUN account and set values:

general/mailgunKey = https://api.mailgun.net/v3/xxx.cl (domain active and working)
general/mailgunURL = key-2615c8aa31b6aece3dc7505c82d5517
general/emailFrom  = noreply@xxx.cl

But my workers are not being notified.

**Comment by Snipa22** [comment]
You have your key and URL reversed.  Also, please have them reset your key.

https://github.com/Snipa22/nodejs-pool/wiki/Configuration-Details

**Comment by RlyehDoom** [comment]
Thanks for time Snipa22 but they where reversed on this example only... and the key was fake thanks for your concern. I did a pm2 stop/start worker. same issue what else can I look into?

**Comment by ArqTras** [comment]
It works for me only if I add trusted email to mailgun panel. Don know why it stop working

**Comment by ArqTras** [comment]
Did you solved problem ?

**Comment by RlyehDoom** [comment]
@ArqTras you need to use a Domain account on MAILGUN the sandbox one expire after some use.

This are my settings:
general/mailgunKey = https://api.mailgun.net/v3/xxx.cl
general/mailgunURL = key-XXXXXXXXXXXXXXXX
general/emailFrom = noreply@xxx.cl

**Comment by ArqTras** [comment]
I have the same settings. Private key + domain account confirmed in dns.
I receive message that I need manually add email to trusted recipients. And email doesn’t come out

**Comment by RlyehDoom** [comment]
Trusted recipient is for "Sandbox email account" not Domain email account.

**Comment by ArqTras** [comment]
let me goof understand.
On node accout I put

mailgunKey  key-1exxxxxx
mailgunURL : https://api.mailgun.net/v3/domain.pl
emailFrom : postmaster@domain.pl
On mailgun account I have mydomain.pl and sandbox

I have restarted worker and api and no auto sending mail.

**Comment by ArqTras** [comment]
curl -s --user 'api:key-1ezzzzz' https://api.mailgun.net/v3/mydomain.pl/messages -F from='Excited User <postmaster@mydomain.pl>' -F to=test@mydomain.pl -F subject='Hello' -F text='key!'
{
  "message": "Free accounts are for test purposes only. Please upgrade or add the address to authorized recipients in Account Settings."

**Comment by vitorgatti** [comment]
you have to add your credit card to your account

it will only charge if you send more than 10000 emails

**Comment by ArqTras** [comment]
But if I dont wont to add card it work before with other domain :/

**Comment by ArqTras** [comment]
Added Credit Card i think it should be work
