### ISSUE TITLE
set PPLNS payout timer to specific value

### ISSUE THREAD

**Issue by mxjoe** [Snipa22/nodejs-pool#161]
Hi,

how can I set the PPLNS payout timer to a value other than 120 minutes? Can this be done via `sample_config.sql`? If so could you add module and item name to the Wiki, please.

Thanks.

**Comment by Snipa22** [comment]
All SQL is self-documented in the Item_desc row.

https://github.com/Snipa22/nodejs-pool/blob/master/deployment/base.sql#L231

**Comment by mxjoe** [comment]
Thank you, didn't know that.
