### ISSUE TITLE
Invalid payment address

### ISSUE THREAD

**Issue by stlobe** [Snipa22/nodejs-pool#162]
When I try to enable testnet, I got an error "Invalid payment address provided".  Any hint is appreciated.

**Comment by vitorgatti** [comment]
you have to change the mysql field testnet to 1 (true) in pool.config

**Comment by stlobe** [comment]
Yes I did. After changed and rebooted, all miners showed same error (Invalid payment address provided).

**Comment by vitorgatti** [comment]
did you create testnet wallets? they should start with 9 or A, 4 is only for mainnet

**Comment by vitorgatti** [comment]
the ports used by testnet are different too (monerod and monero-wallet-rpc, you have to change to 28081 and 28082 respectively

**Comment by stlobe** [comment]
oh thank you
