### ISSUE TITLE
No API connections

### ISSUE THREAD

**Issue by PandemRus** [Snipa22/nodejs-pool#166]
Hello.
I build fresh install on clear Ubuntu 16.04.

And API is not work.
Caddy log:
Nov 14 10:33:02 pool1 caddy[1245]: 14/Nov/2017:10:33:02 +0300 [ERROR 502 /api/pool/stats] dial tcp 127.0.0.1:8001: getsockopt: connection refused
Nov 14 10:33:02 pool1 caddy[1245]: 14/Nov/2017:10:33:02 +0300 [ERROR 502 /api/network/stats] dial tcp 127.0.0.1:8001: getsockopt: connection refused

All PM2 Logs is like:
2017-11-14 10:29 +03:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:                                         
Error: Cannot find module 'multi-hashing'                                                                                                                       
    at Function.Module._resolveFilename (module.js:469:15)                                                                                                      
    at Function.Module._load (module.js:417:25)                                                                                                                 
    at Module.require (module.js:497:17)                                                                                                                        
    at require (internal/module.js:20:19)                                                                                                                       
    at Object.<anonymous> (/home/pandem/nodejs-pool/lib/coins/xmr.js:4:22)                                                                                      
    at Module._compile (module.js:570:32)                                                                                                                       
    at Object.Module._extensions..js (module.js:579:10)                                                                                                         
    at Module.load (module.js:487:32)                                                                                                                           
    at tryModuleLoad (module.js:446:12)                                                                                                                         
    at Function.Module._load (module.js:438:3)                                                                                                                  
    at Module.require (module.js:497:17)                                                                                                                        
    at require (internal/module.js:20:19)                                                                                                                       
    at /home/pandem/nodejs-pool/init.js:46:15                                                                                                                   
    at tryCatcher (/home/pandem/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)                                                                     
    at Promise._settlePromiseFromHandler (/home/pandem/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)                                          
    at Promise._settlePromise (/home/pandem/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)

pm2 status
┌───────────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name          │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user   │ watching │
├───────────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ api               │ 1  │ fork │ 1456 │ online │ 0       │ 20m    │ 0%  │ 45.6 MB   │ pandem │ disabled │
│ blockManager      │ 3  │ fork │ 1465 │ online │ 0       │ 20m    │ 0%  │ 51.1 MB   │ pandem │ disabled │
│ longRunner        │ 7  │ fork │ 1510 │ online │ 0       │ 20m    │ 0%  │ 47.7 MB   │ pandem │ disabled │
│ monero-wallet-rpc │ 2  │ fork │ 1462 │ online │ 0       │ 20m    │ 0%  │ 59.0 MB   │ pandem │ disabled │
│ payments          │ 5  │ fork │ 1480 │ online │ 0       │ 20m    │ 0%  │ 47.5 MB   │ pandem │ disabled │
│ pool              │ 8  │ fork │ 1512 │ online │ 0       │ 20m    │ 0%  │ 46.2 MB   │ pandem │ disabled │
│ remoteShare       │ 6  │ fork │ 1491 │ online │ 0       │ 20m    │ 0%  │ 45.3 MB   │ pandem │ disabled │
│ worker            │ 4  │ fork │ 1471 │ online │ 0       │ 20m    │ 0%  │ 47.6 MB   │ pandem │ disabled │
└───────────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user   │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼────────┤
│ pm2-logrotate │ 2.3.0   │ N/A        │ online │ 0       │ 0%  │ 38.727 MB   │ pandem │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴────────┘

pm2 show 1
 Describing process with id 1 - name api 
┌───────────────────┬────────────────────────────────────────┐
│ status            │ online                                 │
│ name              │ api                                    │
│ restarts          │ 0                                      │
│ uptime            │ 21m                                    │
│ script path       │ /home/pandem/nodejs-pool/init.js       │
│ script args       │ --module=api                           │
│ error log path    │ /home/pandem/.pm2/logs/api-error-1.log │
│ out log path      │ /home/pandem/.pm2/logs/api-out-1.log   │
│ pid path          │ /home/pandem/.pm2/pids/api-1.pid       │
│ interpreter       │ node                                   │
│ interpreter args  │ N/A                                    │
│ script id         │ 1                                      │
│ exec cwd          │ /home/pandem/nodejs-pool               │
│ exec mode         │ fork_mode                              │
│ node.js version   │ 6.9.2                                  │
│ watch & reload    │ ✘                                      │
│ unstable restarts │ 0                                      │
│ created at        │ 2017-11-14T05:33:04.452Z               │
└───────────────────┴────────────────────────────────────────┘
 Revision control metadata 
┌──────────────────┬────────────────────────────────────────────┐
│ revision control │ git                                        │
│ remote url       │ https://github.com/Snipa22/nodejs-pool.git │
│ repository root  │ /home/pandem/nodejs-pool                   │
│ last update      │ 2017-11-14T07:50:34.537Z                   │
│ revision         │ 53029d9d5a24f9e4abe3c969455fc7ff45abc6bd   │
│ comment          │ Whoops, removing the socket listen.        │
│ branch           │ master                                     │
└──────────────────┴────────────────────────────────────────────┘
 Code metrics value 
┌────────────┬────────┐
│ Loop delay │ 6.38ms │
└────────────┴────────┘

**Comment by PandemRus** [comment]
Can anyone help me?
I use autoinstaller on fresh Unbuntu 16.04. I generate wallets, start all services. But API port 8001 is not opened.
in API log this message only:
2017-11-16 08:06 +03:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Cannot find module 'multi-hashing'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pandem/nodejs-pool/lib/coins/xmr.js:4:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/pandem/nodejs-pool/init.js:46:15
    at tryCatcher (/home/pandem/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pandem/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pandem/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)

**Comment by ArqTras** [comment]
Look at Caddy file /etc/caddy
If you have default there should be :80 
then curl http://public ip/leafApi 
Should be something like this: Cannot GET /leafApi
Its ok 
Make sure all deamons on and in sql put the same address in section : shareHost http://public ip/leafApi
Think about tweak caddy to domain with ssl 
It will looks like:
https://mydomain {
Then restart caddy and all daemons (after update in sql) , correct your api address in frontend ui to use https://domain/api

**Comment by PandemRus** [comment]
Something wrong.

Command curl http://public_ip/leafApi show:
502 Bad Gateway

System log:
pool caddy[18124]: 16/Nov/2017:12:29:07 +0000 [ERROR 502 /leafApi] dial tcp 127.0.0.1:8000: getsockopt: connection refused

At this time all services started:
pm2 status
┌──────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name     │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user   │ watching │
├──────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ api          │ 0  │ fork │ 21057 │ online │ 3       │ 3m     │ 0%  │ 47.4 MB   │ pandem │ disabled │
│ blockManager │ 2  │ fork │ 20852 │ online │ 0       │ 3m     │ 0%  │ 45.8 MB   │ pandem │ disabled │
│ longRunner   │ 6  │ fork │ 20986 │ online │ 0       │ 3m     │ 0%  │ 45.9 MB   │ pandem │ disabled │
│ payments     │ 4  │ fork │ 20918 │ online │ 0       │ 3m     │ 0%  │ 44.4 MB   │ pandem │ disabled │
│ pool         │ 7  │ fork │ 21020 │ online │ 0       │ 3m     │ 0%  │ 46.7 MB   │ pandem │ disabled │
│ remoteShare  │ 5  │ fork │ 20952 │ online │ 0       │ 3m     │ 0%  │ 46.5 MB   │ pandem │ disabled │
│ worker       │ 3  │ fork │ 20884 │ online │ 0       │ 3m     │ 0%  │ 47.1 MB   │ pandem │ disabled │
└──────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘

**Comment by ArqTras** [comment]
Look at /etc/caddy/Caddy
Default looks like:
# Catch-all vhost
:80 {
    root /var/www
    proxy /leafApi 127.0.0.1:8000
    proxy /api 127.0.0.1:8001 {
        without /api
    }
    proxy /socket.io 127.0.0.1:8001 {
        header_upstream Connection {>Connection}
        header_upstream Upgrade {>Upgrade}
    }
    header / {
        Access-Control-Allow-Methods "GET, POST, OPTIONS"
        Access-Control-Allow-Headers "Content-Type, x-access-token"
    }
    gzip
    mime .manifest text/cache-manifest
}

Then as roor user or sudouser run:
systemctl restart caddy.service
next restart api daemon:
pm2 restart api

**Comment by PandemRus** [comment]
Caddyfile is ok.

There is no connection to API's port 8000 and 8001.

System log.
Nov 16 15:40:25 pool caddy[23658]: 16/Nov/2017:12:40:25 +0000 [ERROR 502 /leafApi] dial tcp 127.0.0.1:8000: getsockopt: connection refused

Opened ports:
netstat -natp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 127.0.0.1:3306 0.0.0.0:* LISTEN 14206/mysqld
tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN 1246/sshd
tcp 0 0 127.0.0.1:3306 127.0.0.1:53926 ESTABLISHED 14206/mysqld
tcp 0 0 127.0.0.1:53926 127.0.0.1:3306 ESTABLISHED 20986/init.js
tcp 0 0 127.0.0.1:53928 127.0.0.1:3306 ESTABLISHED 21020/init.js
tcp 0 0 127.0.0.1:3306 127.0.0.1:53920 ESTABLISHED 14206/mysqld
tcp 0 0 127.0.0.1:3306 127.0.0.1:53918 ESTABLISHED 14206/mysqld
tcp 0 0 127.0.0.1:53924 127.0.0.1:3306 ESTABLISHED 20952/init.js
tcp 0 0 127.0.0.1:3306 127.0.0.1:53930 ESTABLISHED 14206/mysqld
tcp 0 0 127.0.0.1:53930 127.0.0.1:3306 ESTABLISHED 21057/init.js
tcp 0 0 127.0.0.1:53920 127.0.0.1:3306 ESTABLISHED 20884/init.js
tcp 0 0 127.0.0.1:53922 127.0.0.1:3306 ESTABLISHED 20918/init.js
tcp 0 0 127.0.0.1:3306 127.0.0.1:53924 ESTABLISHED 14206/mysqld
tcp 0 0 127.0.0.1:53918 127.0.0.1:3306 ESTABLISHED 20852/init.js
tcp 0 0 127.0.0.1:3306 127.0.0.1:53928 ESTABLISHED 14206/mysqld
tcp 0 0 127.0.0.1:3306 127.0.0.1:53922 ESTABLISHED 14206/mysqld
tcp6 0 0 :::80 :::* LISTEN 18124/caddy
tcp6 0 0 :::22 :::* LISTEN 1246/sshd

All services started:
pm2 status
┌──────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
├──────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ api │ 0 │ fork │ 21057 │ online │ 3 │ 3m │ 0% │ 47.4 MB │ pandem │ disabled │
│ blockManager │ 2 │ fork │ 20852 │ online │ 0 │ 3m │ 0% │ 45.8 MB │ pandem │ disabled │
│ longRunner │ 6 │ fork │ 20986 │ online │ 0 │ 3m │ 0% │ 45.9 MB │ pandem │ disabled │
│ payments │ 4 │ fork │ 20918 │ online │ 0 │ 3m │ 0% │ 44.4 MB │ pandem │ disabled │
│ pool │ 7 │ fork │ 21020 │ online │ 0 │ 3m │ 0% │ 46.7 MB │ pandem │ disabled │
│ remoteShare │ 5 │ fork │ 20952 │ online │ 0 │ 3m │ 0% │ 46.5 MB │ pandem │ disabled │
│ worker │ 3 │ fork │ 20884 │ online │ 0 │ 3m │ 0% │ 47.1 MB │ pandem │ disabled │
└──────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘

**Comment by PandemRus** [comment]
More ideas?

**Comment by ArqTras** [comment]
Reboot all and start daemons it should work

**Comment by PandemRus** [comment]
No :(
pm2 restart all
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [all](ids: 0,2,3,4,5,6,7)
[PM2] [api](0) ✓
[PM2] [blockManager](2) ✓
[PM2] [worker](3) ✓
[PM2] [payments](4) ✓
[PM2] [remoteShare](5) ✓
[PM2] [longRunner](6) ✓
[PM2] [pool](7) ✓
┌──────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬────────┬──────────┐
│ App name     │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user   │ watching │
├──────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼────────┼──────────┤
│ api          │ 0  │ fork │ 25475 │ online │ 6       │ 0s     │ 88% │ 47.7 MB   │ pandem │ disabled │
│ blockManager │ 2  │ fork │ 25484 │ online │ 1       │ 0s     │ 65% │ 44.1 MB   │ pandem │ disabled │
│ longRunner   │ 6  │ fork │ 25589 │ online │ 1       │ 0s     │ 44% │ 29.6 MB   │ pandem │ disabled │
│ payments     │ 4  │ fork │ 25539 │ online │ 1       │ 0s     │ 62% │ 39.4 MB   │ pandem │ disabled │
│ pool         │ 7  │ fork │ 25612 │ online │ 1       │ 0s     │ 42% │ 24.9 MB   │ pandem │ disabled │
│ remoteShare  │ 5  │ fork │ 25570 │ online │ 1       │ 0s     │ 45% │ 31.8 MB   │ pandem │ disabled │
│ worker       │ 3  │ fork │ 25526 │ online │ 1       │ 0s     │ 65% │ 41.4 MB   │ pandem │ disabled │
└──────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user   │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼────────┤
│ pm2-logrotate │ 2.3.0   │ N/A        │ online │ 0       │ 0%  │ 40.863 MB   │ pandem │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴────────┘
 Use `pm2 show <id|name>` to get more details about an app


Nov 16 15:47:56 pool caddy[23658]: 16/Nov/2017:12:47:56 +0000 [ERROR 502 /api/config] dial tcp 127.0.0.1:8001: getsockopt: connection refused
Nov 16 15:47:56 pool caddy[23658]: 16/Nov/2017:12:47:56 +0000 [ERROR 502 /api/pool/stats] dial tcp 127.0.0.1:8001: getsockopt: connection refused
Nov 16 15:47:56 pool caddy[23658]: 16/Nov/2017:12:47:56 +0000 [ERROR 502 /api/network/stats] dial tcp 127.0.0.1:8001: getsockopt: connection refused
Nov 16 15:48:00 pool caddy[23658]: 16/Nov/2017:12:48:00 +0000 [ERROR 502 /api/pool/stats] dial tcp 127.0.0.1:8001: getsockopt: connection refused
Nov 16 15:48:00 pool caddy[23658]: 16/Nov/2017:12:48:00 +0000 [ERROR 502 /api/network/stats] dial tcp 127.0.0.1:8001: getsockopt: connection refuse

**Comment by ArqTras** [comment]
reboot machine

**Comment by PandemRus** [comment]
Done. No changes.

**Comment by ArqTras** [comment]
In sql you have the same address in remoteShare http://public ip/leafApi

**Comment by PandemRus** [comment]
yes

**Comment by ArqTras** [comment]
Come to irc # supportxmr

**Comment by vitorgatti** [comment]
run this command and paste the results:

`sudo netstat -tuplen`

**Comment by PandemRus** [comment]
# sudo netstat -tuplen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:18080           0.0.0.0:*               LISTEN      1001       14601       1366/monerod    
tcp        0      0 127.0.0.1:18081         0.0.0.0:*               LISTEN      1001       14897       1366/monerod    
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      113        16026       1345/mysqld     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          15879       1240/sshd       
tcp6       0      0 :::80                   :::*                    LISTEN      33         15999       1238/caddy      
tcp6       0      0 :::22                   :::*                    LISTEN      0          15887       1240/sshd       
udp        0      0 46.4.237.67:123         0.0.0.0:*                           0          14091       1350/ntpd       
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          14089       1350/ntpd       
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          14085       1350/ntpd       
udp6       0      0 fe80::2eff:fe04:ed4:123 :::*                                114        14130       1350/ntpd       
udp6       0      0 ::1:123                 :::*                                0          14093       1350/ntpd       
udp6       0      0 :::123                  :::*                                0          14082       1350/ntpd

**Comment by vitorgatti** [comment]
port 8001 is not running, that is your problem, something is wrong with your installation, check the deploy.bash script and run some commands again

this is the result in my server:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp6       0      0 :::8001                 :::*                    LISTEN      1002       146443      25508/init.js
```

**Comment by PandemRus** [comment]
I launched deploy.bash as is without changes:
curl -L https://raw.githubusercontent.com/Snipa22/nodejs-pool/master/deployment/deploy.bash | bash

**Comment by vitorgatti** [comment]
yes, but in one of my tests the script crashed, maybe something similar happened to you, try checking the commands manually (it's not a long script), or reinstall from zero

**Comment by PandemRus** [comment]
Tried to install manually... Everithing is ok, except builing 'multi-hashing' module.

**Comment by PandemRus** [comment]
Да что ж за хрень-то такая.... столько раз уже ставил на чистую систему, всё равно косяк.... Как вы умудряетесь это чудо запускать????

**Comment by MineMoneroPRO** [comment]
Чувак, это не имеет никакого отношения к ишью самого пула.
Это имеет отношение только к твоим скиллам.

На кой черт ты сюда пишешь?

**Comment by PandemRus** [comment]
Как не имеет, если всё делается по инструкции, а результат не такой как ожидается.

**Comment by MineMoneroPRO** [comment]
Вероятнее всего, на твоём говносерваке нет поддержки AES и модуль multihashing не собрался.

**Comment by PandemRus** [comment]
Ура!!! Спасибо, MineMoneroPRO! 3 дня мучений, выручил дружище!

p.s. AES-NI CPU support required.

**Comment by ArqTras** [comment]
Запуск системы и изучение ее работы заняли у меня почти неделю. многие установки и несколько серверов, которые я должен был проверить.

**Comment by ArqTras** [comment]
There is non aes ni module hashing from clintar
Google help you

**Comment by lorvent** [comment]
proxy /leafApi 127.0.0.1:8000
proxy /api 127.0.0.1:8001 {

do we need to keep `127.0.0.1` or change with our ip?

i am having same problem.

502 error with API

**Comment by bobbieltd** [comment]
proxy /leafApi 127.0.0.1:8000
proxy /api 127.0.0.1:8001 {

Correct. 127.0.0.1 , keep it like that. Don’t put your IP here. http://yourIP//api

**Comment by LegolasGChief** [comment]
Same problem here

**Comment by besereiter** [comment]
same problem here

**Comment by ArqTras** [comment]
Https don’t work with ip there must be domain name.
Caddy file in etc :80 for access over ip 
After restart caddy service check http://your up/api/pool/stats

**Comment by ArqTras** [comment]
Check wiki on my Github there is step by step info. Ofc for different coin but rest is similar 
GitHub.com/ArqTras

**Comment by besereiter** [comment]
thanks buut the api will not start
i get the exception in pm2 log when i restart the api

[PM2] [api](0) ✓
┌──────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬────────────┬──────────┐
│ App name     │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user       │ watching │
├──────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼────────────┼──────────┤
│ api          │ 0  │ fork │ 8499 │ online │ 11      │ 0s     │ 0%  │ 11.8 MB   │ pooldaemon │ disabled │
│ blockManager │ 2  │ fork │ 6783 │ online │ 4       │ 5m     │ 0%  │ 44.3 MB   │ pooldaemon │ disabled │
│ longRunner   │ 6  │ fork │ 6870 │ online │ 4       │ 5m     │ 0%  │ 46.7 MB   │ pooldaemon │ disabled │
│ payments     │ 4  │ fork │ 6820 │ online │ 4       │ 5m     │ 0%  │ 46.4 MB   │ pooldaemon │ disabled │
│ pool         │ 7  │ fork │ 6894 │ online │ 4       │ 5m     │ 0%  │ 44.8 MB   │ pooldaemon │ disabled │
│ remoteShare  │ 5  │ fork │ 7856 │ online │ 5       │ 2m     │ 0%  │ 46.3 MB   │ pooldaemon │ disabled │
│ worker       │ 3  │ fork │ 6810 │ online │ 4       │ 5m     │ 0%  │ 44.4 MB   │ pooldaemon │ disabled │

Exception:

/home/pooldaemon/.pm2/logs/api-error-0.log last 15 lines:
0|api      |     at processImmediate [as _immediateCallback] (timers.js:722:5)
0|api      | 2018-02-21 12:39 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|api      | TypeError: Cannot read property 'funcFile' of undefined
0|api      |     at /home/pooldaemon/nodejs-pool/init.js:46:42
0|api      |     at tryCatcher (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
0|api      |     at Promise._settlePromiseFromHandler (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
0|api      |     at Promise._settlePromise (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
0|api      |     at Promise._settlePromise0 (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
0|api      |     at Promise._settlePromises (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
0|api      |     at Async._drainQueue (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
0|api      |     at Async._drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
0|api      |     at Immediate.Async.drainQueues (/home/pooldaemon/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
0|api      |     at runCallback (timers.js:789:20)
0|api      |     at tryOnImmediate (timers.js:751:5)
0|api      |     at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by ArqTras** [comment]
Vm aes_ni support 
Ip public on config file in nodejs drir
Ip public in MySQL where pool ports
Pm2 restart api —update-env

**Comment by besereiter** [comment]
AES_NI support enabled
public ip in config.json set
public ip in mysql ... in tables ports there is no entry, only in port_config

i think there is something defect in the api module, is there a easy way to reinstall it ?

**Comment by besereiter** [comment]
Found it, thanks for your help -> path to coin config permission problem
