### ISSUE TITLE
Block not show on poolui 

### ISSUE THREAD

**Issue by ArqTras** [Snipa22/nodejs-pool#167]
I have make a horrible thing.
When restarting caddy for api changes and also all pm2 modules I found a block
(Worker 3 - 21862) Block 199740 found at height 890421 by WmsxxxxxxxxG ID: x IP: XX.XXx.XXX.XXX, share type: false - submit result: {"status":"OK"} 
It is strange that I get on pool wallet about 13 aeons confirmed but there is no info on pool.
I make restart and put daemon to disable autosave, restart all modules but still nothing.
Also block manager showing only PPS performing payout but pool is PPLNS.
Should I wait for next block and the payment will be send by automat or need to do it manually?

**Comment by ArqTras** [comment]
Catching last block and using script block_locker from debugscripts solved problem

**Comment by sevendoorknobs** [comment]
@ArqTras how did you fix this?

**Comment by ArqTras** [comment]
node block_locker.js --blockID=
(number of block you mine)

**Comment by sevendoorknobs** [comment]
Do I use the blockID that has issue or current blockID? 

And thank you for the prompt response

**Comment by ArqTras** [comment]
Join my discord and describe problem.
You can find link on supportaeon.com

**Comment by sevendoorknobs** [comment]
I was able to resolve it by updating the debug file and using recent blockID as past blockID was removed from share DB. Thank you mate!

**Comment by ArqTras** [comment]
Greate and good :)
