### ISSUE TITLE
MDB_VERSION_MISMATCH: Database environment version mismatch

### ISSUE THREAD

**Issue by vikgdev** [Snipa22/nodejs-pool#171]
When I run "mdb_stat -fear ~/pool_db/" I receive "mdb_env_open failed, error -30794 MDB_VERSION_MISMATCH: Database environment version mismatch"

I don't know how to fix it

**Comment by wwarlock** [comment]
@vikgdev So, what are you did to fix this error?

**Comment by bobbieltd** [comment]
Just in case someone run into it. Here is the solution : 
bash ~/nodejs-pool/deployment/install_lmdb_tools.sh

**Comment by wwarlock** [comment]
I found that this error is showing when the pool is working.
If I'm stopping pool services by `pm2 stop all` for example, then this error is disappeared and DB becomes available.

**Comment by bobbieltd** [comment]
Weird, I can check on live pool without stopping anything.
