### ISSUE TITLE
Any good advice to check if everything is fine?

### ISSUE THREAD

**Issue by RlyehDoom** [Snipa22/nodejs-pool#176]
I don't want mine on my pool for two months and then realize something is wrong... and paf! block found is lost.

So any advice?

This is my pool: https://www.cryptominers.cl

**Comment by vitorgatti** [comment]
test payments and blocks in testnet, with 50H/s you can find a block every 20 minutes

that's why I did before releasing my pool

**Comment by ArqTras** [comment]
You have put bad geo addres in sql 
Propably it should be cryptominers.cl if your web is hosted on pool or any domain you created in. 
Check your front page

**Comment by RlyehDoom** [comment]
@vitorgatti thanks but I can't sync testnet blockchain dunno why but is taking forever to sync...
@ArqTras Thanks you!!! you are right!

**Comment by vitorgatti** [comment]
Yes testnet blockhain takes a while to sync because it doesn't have many people seeding. Took me ~10 hours to sync. Try raising the max peers allowed to connect.

If you're not sure your pool will work, I really recommend that you try with testnet first :)

**Comment by RlyehDoom** [comment]
Well I think everything is fine... there is no log errors and the output files are good. Did you experience or found something interesting while testing with testnet?

**Comment by mxjoe** [comment]
I am asking me the same question currently. I have found 6 Blocks in 3 weeks and now I have found NO blocks in 2 weeks although the pool has a hashrate of approx. 35 KH/s. The only thing I changed was lowering the PPLNS fee from 0.1% to 0%.
I am running the latest code.

This is my XMR mining pool: `https://secumine.net`

**Comment by RlyehDoom** [comment]
Probably...  you can't always find blocks with that luck ratio you got! Lucky you bro. I hope you found more!
