### ISSUE TITLE
Feature request: switching to UTF8

### ISSUE THREAD

**Issue by minecoins** [Snipa22/nodejs-pool#18]
I think it's a good idea to make live easier for non ascii world by switching to UTF8 at early stage of development. Currently we have some strings in SQL for emailing. It would be nice if we make at least that fields UTF8 to allow further l10n/i18n.

In general: I think it's better to switch SQL db entirely to UTF8, it doesn't break anything, but gives us much more chances to deal with diff. languages.

Thus, at this stage:

- switching to UTF8 DB
- setting sql connection to UTF8

mailgun is smart enough to set utf8 headers and encode subject (tested with curl).

**Comment by Snipa22** [comment]
While I don't care too much about UTF-8 support, it's not a hard patch. I'll add it to the SQL repository a little bit later today.

**Comment by Snipa22** [comment]
SQL Alters + SQL available in: https://github.com/Snipa22/nodejs-pool/commit/5b75efcd3281a04f31a370a3d7e3ae945641c3c7
