### ISSUE TITLE
Unable to make payments due to random_outs_error

### ISSUE THREAD

**Issue by razorman8669** [Snipa22/nodejs-pool#180]
The pool was making payments just fine until recently when I started receiving the following in my logs.  Payments no longer work even after restarting multiple times and configuring it with different values for `maxPaymentTxns`:
```
Database Worker: LMDB Env Initialized.
Setting the payment timer to: 1440 minutes with a: 25 minute delay if the wallet is out of money
Loaded all payees into the system for processing
Paying out: 5 people

  [RPC0]  WARN    wallet.wallet2  src/wallet/wallet2.cpp:4023 selected transfers: 

  [RPC0]  ERROR   wallet.wallet2  src/wallet/wallet2.cpp:3785 daemon_resp.status != CORE_RPC_STATUS_OK. THROW EXCEPTION: 
  [RPC0]  WARN    net.http    src/wallet/wallet_errors.h:707  /usr/local/src/monero/src/wallet/_rpc_requestINS0_14transfer_errorELi3EEE: failed to get random outs, status = Too many outs requested

Issue making payments{"code":-4,"message":"failed to get random outs"}
Will not make more payments until the payment daemon is restarted!
```

Any ideas?

**Comment by Snipa22** [comment]
This is an error from the monero daemon, it's unable to get enough outs to perform the txn.  You'd want to check into the monero side to see exactly what's tripping this error, as this isn't something that can be fixed at the pool side.  You may want to double check that it's running --trusted-daemon, and other arguments in relations to that.

**Comment by javietanh** [comment]
Hi guys,

My pool working smoothly but the miner due XMR always showing 0.0000.....? what's the problem? today, i transfer 1 XMR to my pool xmr address but the problem still?

Cheers

**Comment by vitorgatti** [comment]
https://github.com/monero-project/monero/issues/2855

It's a known bug that has already been fixed (pending commit in the official branch).

For now you can make the payments by removing the `--restricted-rpc` from `monerod`

**Comment by vitorgatti** [comment]
@javietanh did you pool find a block? If not, miner due will always be empty.

**Comment by razorman8669** [comment]
@vitorgatti thanks!  your suggestion about removing `--restricted-rpc` from the daemon worked.

@Snipa22 `--trusted-daemon` was already being used.  my command was `pm2 start /usr/local/src/monero/build/release/bin/monero-wallet-rpc -- --rpc-bind-port 18082 --password-file ~/wallet_pass --wallet-file <Your wallet name here> --disable-rpc-login --trusted-daemon`

@javietanh you do realize you hijacked this issue ticket right?  next time create a new ticket instead of adding noise to other tickets that are unrelated to your particular issue...it pollutes the cosmos
