### ISSUE TITLE
Aeon

### ISSUE THREAD

**Issue by newhelp** [Snipa22/nodejs-pool#181]
Hello
How to install a pool for Aeon, is there an instruction?

**Comment by vitorgatti** [comment]
there are some flags that you have to change in mysql, but the rest of the process (node, wallet-rpc) is manual, most of it is not, though

always use testnet first if you are not sure your pool is going to work

**Comment by newhelp** [comment]
I use deploy_aeon.bash ?

**Comment by vitorgatti** [comment]
yes, pretty much

**Comment by CollusionPool** [comment]
Thanks, but you do not tell me how to configure testnet?

**Comment by newhelp** [comment]
Thanks, but you do not tell me how to configure testnet?

**Comment by newhelp** [comment]
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-pool failed, see error above.
bash: line 85: cd: /home/pool/nodejs-pool: No such file or directory

**Comment by newhelp** [comment]
Spent 1 day did not understand how to install who could describe how to install the pool under aeon
