### ISSUE TITLE
Who is tracking us?

### ISSUE THREAD

**Issue by jimoquinn** [Snipa22/nodejs-pool#182]
"Turn visitors into customers.
Intelligent live chat software to engage with visitors at the perfect time."

That is what it says on the http://gosquared.com homepage and given the link that is embedded in the nodejs-pool source or one of the associated npm packages, I'd venture to say this gosquared.com serivce has identified a good number of people's real life identity if they visited a nodejs-pool site.

Maybe I'm wrong, but a cryptocurrency that uses privacy has a major feature probably shouldn't have a mining pool that tracks visitors in such a manner.

Here is the tracker that showed up in FireFox Developer b/c I had that Network pane running.  It is sending the resolution of my screen, name of the pool I was on, and if they use a service like FullContact.com or ClearBit.com they can often turn a few key data points back to a full profile on a single individual:  https://www.gosquared.com/docs/tracking/identify/

Tracking code:
https://data2.gosquared.com/pv?cs=UTF-8&cd=24&la=en-US&sw=1440&sh=900&dp=2&pu=https%3A%2F%2Fkiwiirc.com%2Fclient%2Firc.kiwiirc.com%2F%3F%26theme%3Dmini&pt=Kiwi%20IRC&ri=0&ru=http%3A%2F%2Fxmr.xxxxpool.xxxnge%2F&re=1&vi=11&pv=11&lv=1511851707&vw=992&vh=650&dw=992&dh=650&st=0&sl=0&tz=360&rc=1&cb=0&a=GSN-581113-U&id=f769faad0b598e02077e39a612d62c7b&tv=6.3.1871
Jim

PS - more "features" from gosquare.com 's site.

Stitching across devices
  Users can access your apps on multiple devices. GoSquared CRM stitches together all user 
  sessions across devices seamlessly.

Always in sync
  Server-side integrations and modules for all major languages ensure GoSquared 
  CRM is always in sync with your internal databases and systems.
 
Instant search
  Whether you're dealing with a customer support case or just trying to understand a 
  specific user's journey a little better, you can find them in an instant.
 
Intuitive filtering
  Every piece of information about every user can be queried in GoSquared  
  CRM. Easily find people based on properties (like their lifetime value) or by 
   events they've triggered.

Smart segmentation
  Save commonly used sets of filters as Smart Groups so you can check back 
   easily on groups such as "latest signups", "new customers", or "users likely to churn".

Easy export
It's easy to grab a list of your users and pull it into other tools, where you 
can take action on the data. Now you have everything you need to connect 
with your users.

**Comment by RemmyLee** [comment]
This is not part of nodejs-pool. It's kiwiIRC which is just an iframe on the support page that links to a web based IRC client. You can remove it.

<iframe src="https://kiwiirc.com/client/irc.kiwiirc.com/?&theme=mini#monero-pools" style="border:0; width:100%; height:650px;"></iframe>

**Comment by jimoquinn** [comment]
Appreciate the clarification, I'll take this over to poolui.  

Not sure if anyone else has an opinion on this, but I believe that embedding a link that includes a tracking code for a service specifically designed to reveal identities is unwarranted.
