### ISSUE TITLE
Block headers identical to historical header.

### ISSUE THREAD

**Issue by mxjoe** [Snipa22/nodejs-pool#183]
Hi,

worker module throws every few seconds a message like:
`4|worker   | 2017-11-28 16:35 +00:00: Block headers identical to historical header.  Ignoring`

Is this a problem? Can this be fixed?

**Comment by ArqTras** [comment]
Its normal state. Works good

**Comment by Snipa22** [comment]
This is normal, this is the system handling the fact that the BT hasn't changed.  This used to look way worse, but can be used as a status check to make sure worker is still talking to Monerod.
