### ISSUE TITLE
Odd distribution bug.

### ISSUE THREAD

**Issue by RemmyLee** [Snipa22/nodejs-pool#189]
Our pool hit its first block today and something odd happened with the distribution of XMR to our miners.

7.7 KH/s | ADDRESS | 0 XMR | 0.103327217013 XMR | 1,415,086,060 | 41,409 | 3 | 4 | 13 minutes ago

287 H/s | ADDRESS | 0 XMR | 0.01707509079 XMR | 219,464,858 | 23,836 |   | 2 | 14 minutes ago

0 H/s | ADDRESS | 0 XMR | 8.50305e-7 XMR | 10,770 | 9 |   | 1 | 3 days ago

The reward was 5.7XMR

Our pool log shows that the 7.7KH/s miner solved the block, but for some reason, it distributed to someone who only mined with us for a few minutes and the amount is showing greater than the reward was. Any thing we can look at to fix this in particular? Anyone seen this before?

**Comment by vitorgatti** [comment]
Check the balance of your miners with this mysql command:

`select * from pool.balance;`

**Comment by RemmyLee** [comment]
That shows the same thing, but the anomaly address only shows 850305 hashes instead of the aforementioned 8.50305e-7. Any idea what would have caused that to happen? It's telling us we owe that miner 8.5XMR while the two people that actually worked for it are receiving 0.01 and 0.001 respectively.

**Comment by vitorgatti** [comment]
no, 8.50305e-7 isn't 8.5XMR, it's 0.0000000850305XMR

**Comment by RemmyLee** [comment]
The pool is showing that we owe them 8.5XMR.

**Comment by RemmyLee** [comment]
Deleted the offending address and things seem to be stabilized now.
