### ISSUE TITLE
Installing pool on CentOS 6.9 - Script warnings

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#193]
I'm using CentOS 6.9.  I followed the steps to create a non-root account and added it to the sudoers file, then I ran the script and the output is below (I will see what happens and let you know):
Continuing install, this will prompt you for your password if you're not already running as root and you didn't enable passwordless sudo.  Please do not run me as root!
sudo: timedatectl: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: debconf-set-selections: command not found
sudo: debconf-set-selections: command not found
[client]
user=root
password=<password hash>
sudo: apt-get: command not found
fatal: destination path 'nodejs-pool' already exists and is not an empty directory.
bash: line 20: cd: /usr/src/gtest: No such file or directory
sudo: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.
mv: cannot stat `libg*': No such file or directory
sudo: systemctl: command not found
Cloning into 'monero'...
remote: Counting objects: 33935, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 33935 (delta 15), reused 20 (delta 13), pack-reused 33905
Receiving objects: 100% (33935/33935), 131.05 MiB | 30.24 MiB/s, done.
Resolving deltas: 100% (25413/25413), done.
Note: checking out 'v0.11.1.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 793bc973... Merge pull request #2717
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
111   780  111   780    0     0   2063      0 --:--:-- --:--:-- --:--:--  7572
Checking patch src/cryptonote_core/tx_pool.cpp...
Applied patch src/cryptonote_core/tx_pool.cpp cleanly.
mkdir -p build/release
cd build/release && cmake -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=release ../.. && make
/bin/sh: cmake: command not found
make: *** [release-all] Error 127
cp: cannot create regular file `/lib/systemd/system/': No such file or directory
--2017-12-08 19:52:16--  https://downloads.getmonero.org/blockchain.raw
Resolving downloads.getmonero.org... 104.24.27.115, 104.24.28.115, 2400:cb00:2048:1::6818:1c73, ...
Connecting to downloads.getmonero.org|104.24.27.115|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27537349958 (26G) [application/octet-stream]
Saving to: “/tmp/tmp.nMMCU0eniG/blockchain.raw”

**Comment by Snipa22** [comment]
This is not built to work on CentOS, as noted elsewhere in the repo.  Please use Ubuntu 16.04 LTS.
