### ISSUE TITLE
Manually Setup MySQL

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#195]
The directions state: 
.......in module/item format. You can also edit the values in sample_config.sql, then import them into SQL directly via an update.

Critical/Must be done:
pool/address
pool/feeAddress
general/shareHost

Nice to have:
general/mailgunKey
general/mailgunURL
general/emailFrom
---------------------------------------------------
The import process using the script doesn't import and no errors are given.  If I create the tables is the "Module" the table and the "item" the field?  If so, what format should they be in?  Char, var.... what about length?

**Comment by snoski3** [comment]
I changed the script from update to create and I was able to get an error:
sudo mysql schaadan_pool < sample_config.sql
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'pool.config SET item_value = '' WHERE module = 'pool' and item = 'address'' at line 1

**Comment by swa74** [comment]
mysql -u root -p
password root
use pool
source путь/файл.sql

**Comment by snoski3** [comment]
If I use the update command, it works but "...0 rows effected...."
![image](https://user-images.githubusercontent.com/5173575/33800876-972badf0-dd0f-11e7-8476-fbef531e8785.png)

If I use the create command, it doesn't work.
![image](https://user-images.githubusercontent.com/5173575/33800905-49f1a408-dd10-11e7-87c6-8845a94b4788.png)

**Comment by snoski3** [comment]
Please update the read me file. Under the Pre-Deploy section, create an anchor to the manually setup the database section. I followed that section then deleted all of the folders created by the script.  The tables were then created. 

That would have saved my about 4 hours of problems. 

Thanks
