### ISSUE TITLE
banLength: What means "-15m"?

### ISSUE THREAD

**Issue by mxjoe** [Snipa22/nodejs-pool#197]
The item `banLength` of module `pool` is a string and by default `-15m`.

My question is what exactly means `-15m`?
Does it mean the ban duration is 15 minutes? And if it means that why _minus_ 15m?

**Comment by JPaulMora** [comment]
Yes, it means 15 minutes. It's -15 so when time goes forward, the ban time decreases.. -14, -13 etc.

**Comment by mxjoe** [comment]
Okay, thanks for the info.
