### ISSUE TITLE
NiceHash Auto Detection

### ISSUE THREAD

**Issue by Snipa22** [Snipa22/nodejs-pool#20]
NH handily sends us a identifier that we can use to ID their traffic.  Combine this with a per-coin-config to override any difficulty to the max possible.

**Comment by Snipa22** [comment]
Fixed in c95afc3f4357860e19a37668e751c4665487947c

**Comment by mxjoe** [comment]
I am not 100 % sure, does this pool software has nicehash support?

**Comment by Snipa22** [comment]
Yes, it does.
