### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mharrisr** [Snipa22/nodejs-pool#204]
When I try to install the script it show this message without isntalling:

Continuing install, this will prompt you for your password if you're not already running as root and you didn't enable passwordless sudo.  Please do not run me as root!
You ran me as root! Do not run me as root!

How to sort out this issue? its not allowing me to continue install.

**Comment by vitorgatti** [comment]
... do not run the script as the root user.

**Comment by Snipa22** [comment]
Thanks @vitorgatti I was trying to decide how to respond.
