### ISSUE TITLE
Need some help understanding the frontend (poolui and pm2)

### ISSUE THREAD

**Issue by milesgratz** [Snipa22/nodejs-pool#210]
Hi - 

Kudos to the developers of this project, y'all are much smarter than me. 😢 

#### My Misunderstanding of Frontend 

I am trying to understand the frontend configuration a bit better and using [DigitalOcean | How To Set Up a Node.js Application for Production on Ubuntu 16.04 ](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04) as a frame of reference.

1. Is there a reason why poolui is not managed by pm2? How is it being launched on startup? I've looked over the deploy.bash several times and must be missing something. When building manually from Mesh00 repo, I needed to configure an auto start  `autostart enable -n "poolui" -p "/home/pooldaemon/poolui" -c "npm start"` but not seeing anything equivalent in deploy.bash.

2. I've reviewed `deploy.bash`, `/etc/systemd/system/caddy.service`, and `/etc/caddy/Caddyfile` and trying to understand how poolui is being served by Caddy + npm. When configuring poolui and npm manually from Mesh00 repo, it serves on port 8080 and I am using nginx to reverse proxy HTTP/HTTPS back to port 8080. 

#### My Understanding of Reference Implementation

- **xmrpool.net**
Static frontend on "Server1"
Relies on Node.js, npm, Caddy
HTTP (80) redirecting to HTTPS (443)

- **api.xmrpool.net**
API backend on "Server2"
Relies on Node.js, npm, pm2, Nginx, MySQL
HTTP (80) redirecting to HTTPS (443) 

- **mine.xmrpool.net**
RPC Daemon (stratum protocol) on "Server2"
Relies on Node.js, npm, pm2, Nginx, MySQL, monerodaemon
TCP 3333, 5555, 7777 - Unencrypted traffic
TCP 9000 - Encrypted traffic (self-signed "pool" certificate)

**Comment by vitorgatti** [comment]
poolui is not a pool module because it's just a folder where caddy (the webserver) uses as the root directory (a step that is done by deploy.bash)

check your /etc/caddy/Caddyfile

**Comment by milesgratz** [comment]
I was having some DNS issues due to my weird setup that made this really difficult for me to troubleshoot what was going wrong. It is working now, thanks.
