### ISSUE TITLE
Aeon block effort presentation  issue 

### ISSUE THREAD

**Issue by ArqTras** [Snipa22/nodejs-pool#211]
Block effort 370% or more but show only 270 %
The same situation in 760% effort and only 260% show
Any way to correct that values ?

**Comment by bobbieltd** [comment]
Do you know the mathematic formula to calculate block effort ? Is it : block effort = total pool hashes on this block / network difficulty ?

**Comment by ArqTras** [comment]
Effort is counted property because diff rise. But pool ui shows counted with lover diff. In the end it is counted as should be.
