### ISSUE TITLE
pool_db/data.mdb went from 500MB to 14GB in a day

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#214]
My data.mdb (not the blockchain) grew by 13GB just in a day, resulting in disk space problems.

How can I diagnose what happened? Is there any way to clean/trim/defrag/compact this database?

My pool is very small (20 miners, 15KH/s, released 1 month ago).

Thank you

**Comment by jredwine2857** [comment]
Have you looked at the longRunner process to make sure sure it's running?   Check out the readme under "API stopped updating!".  Restarting the daemons appears to clear out the db.

**Comment by vitorgatti** [comment]
Yes, longRunner is running fine (0 log errors), with these last lines in the pm2 logs:
```
5|longRunn | 2017-12-19 15:23 +00:00: Cleaning up the share DB
5|longRunn | 2017-12-19 15:23 +00:00: Done cleaning up the shareDB
5|longRunn | 2017-12-19 15:23 +00:00: Scanning from: 1468236 for more than: 142795556919 shares
5|longRunn | 2017-12-19 16:23 +00:00: Cleaning up the share DB
5|longRunn | 2017-12-19 16:23 +00:00: Done cleaning up the shareDB
5|longRunn | 2017-12-19 16:23 +00:00: Scanning from: 1468264 for more than: 140854749261 shares
```

The `mdb_stat -fear ~/pool_db/` took much longer to run than normal, but the results seem OK...
```
Max pages: 6291456
Number of pages used: 3444592
Free pages: 3284124
```

I never understood the 
> look at the "Reader Table Status" and look for the PID listed
part because I always get 
> (no active readers)
no matter what.

Restarted the longRunner module, but nothing changed (data.mdb still has 14GB).

Thanks

**Comment by ArqTras** [comment]
data.db is around 25 GB there is stored info about blocks shares and all other thing.
You need to dig deeper ;)

**Comment by vitorgatti** [comment]
@ArqTras it's not the blockchain, it's the pool's database.

**Comment by ArqTras** [comment]
Yes and : longRunner - Database share cleanup.

**Comment by ArqTras** [comment]
"The second step is to run:

pm2 stop blockManager worker payments remoteShare longRunner api
pm2 start blockManager worker payments remoteShare longRunner api

This will restart all of your related daemons, and will clear any open reader connections, allowing LMDB to get back to a normal state.

If on the other hand, you have no "Free pages" and your Pages used is equal to the Max Pages, then you've run out of disk space for LMDB. You need to verify the cleaner is working. For reference, 4.3 million shares are stored within approximately 2-3 Gb of space, so if you're vastly exceeding this, then your cleaner (longRunner) is likely broken."

**Comment by vitorgatti** [comment]
Indeed, but the longRunner module is running fine, no errors. How can I understand what happened to my database?

**Comment by ArqTras** [comment]
Server Requirements

    4 Gb Ram
    2 CPU Cores (with AES_NI)
    60 Gb SSD-Backed Storage - If you're doing a multi-server install, the leaf nodes do not need this much storage. They just need enough storage to hold the blockchain for your node. **The pool comes configured to use up to 24Gb of storage for LMDB**. Assuming you have the longRunner worker running, it should never get near this size, but be aware that it /can/ bloat readily if things error, so be ready for this!
    Notably, this happens to be approximately the size of a 4Gb linode instance, which is where the majority of automated deployment testing happened!

**Comment by ArqTras** [comment]
It can be more or less empty but size is ~24 GB

**Comment by vitorgatti** [comment]
no, 24GB is for gigantic pools, 14GB isn't normal, I know a pool that has 90KH/s and their database is only 8GB.

**Comment by Snipa22** [comment]
This is normal.  Most XMR pools are running ~70-80 Gb.  Long-runner, if you receive a spike of traffic, isn't able to clean up fast enough.  Your DB size will not decrease once it grows.  You can abuse mdb_copy -c  to clear it up, but as long as you're showing free pages, there's no reason to do so.

**Comment by vitorgatti** [comment]
Another spike, now the disk is full I don't have anything to delete.
From 14GB to 23GB in 6 hours.

How can a 18KH/s pool with 20 miners spike like that?

:(

**Comment by vitorgatti** [comment]
I thought someone was connecting to my pool with a fixed diff of 100 and sending thousands of shares per minute, but the mindiff of my pool is set to 2000 and I tried connecting with a fixed diff of 100 and couldn't.
