### ISSUE TITLE
auto install struck at one point " use pm2 show ...

### ISSUE THREAD

**Issue by bapparabi** [Snipa22/nodejs-pool#22]
http://prntscr.com/e9kzyq

do you know why your autoinstall script has been struck in this point ..and what need to be done ..as soon as i hit entire it leave the config and stop the process ..

**Comment by Snipa22** [comment]
That's because that's a backgrounded task.  The system has not halted installation, it's just running in the background. Your installation is complete when that pops up.  The PM2 installation for logrotate was causing issues. If you need additional help, please come find us on IRC on irc.freenode.net #monero-pools

**Comment by mxjoe** [comment]
My installation is stuck for over 5 hours at this point. Is this still normal?

**Comment by Obli-One** [comment]
mxjoe - yes its normal, it's finished if you scroll up you can see a message sating it's completed.  just press ctrl+c and you have command line back but everything is finished and you can go onto config stage

**Comment by mxjoe** [comment]
Obli-One - It says "[PM2][Module] Module successfully installed and launched" but I wasn't sure if the whole installation (of all the other modules) was also finished.

**Comment by mxjoe** [comment]
It wasn't completely installed as pm2 Module api was not running.

I started from scratch with this command:

curl -L https://raw.githubusercontent.com/Snipa22/nodejs-pool/master/deployment/deploy.bash | bash

And now it seems to have been installed completely! I think this command should be integrated into the README as I couldn't find it there.
