### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by Ogy** [Snipa22/nodejs-pool#221]
# systemd wallet-rpc service

cat /lib/systemd/system/monero-wallet.service
[Unit]
Description=Monero Wallet Daemon
After=monero.service

[Service]
Type=simple
GuessMainPID=no
ExecStart=/usr/local/src/monero/build/release/bin/monero-wallet-rpc --daemon-host 127.0.0.1 --rpc-bind-port 18082 --password-file /home/USER/wallet_pass --wallet-file /home/USER/Name-of-wallet --disable-rpc-login --trusted-daemon --rpc-bind-ip 127.0.0.1 --confirm-external-bind --log-file /home/USER/monero-wallet-rpc.log
Restart=always
User=USER

[Install]
WantedBy=multi-user.target

**Comment by Ogy** [comment]
https://github.com/Snipa22/nodejs-pool/blob/master/deployment/deploy.bash

should be  v8.9.3 in 94 line 
env PATH=$PATH:`pwd`/.nvm/versions/node/v6.9.2/bin node sql_sync.js

**Comment by Snipa22** [comment]
Thanks, missed that.
