### ISSUE TITLE
mysql and deploy.bash

### ISSUE THREAD

**Issue by Ogy** [Snipa22/nodejs-pool#222]
hello, i think deploy is broken,i tried it 5 times
there are missing tables
+----------------+
| Tables_in_pool |
+----------------+
| balance        |
| bans           |
| block_log      |
| config         |
+----------------+
4 rows in set (0.00 sec)

mysql  < ~xmr/nodejs-pool/deployment/base.sql 
ERROR 1067 (42000) at line 52: Invalid default value for 'paid_time'

**Comment by Ogy** [comment]
wier is that after deploy there is a table users, but it disappear when i run api restart

**Comment by Ogy** [comment]
New mysql has arrived
Add to the section [mysqld] of file /etc/mysql/mysql.conf.d/mysqld.cnf
explicit-defaults-for-timestamp = 1

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

table payments can be then created as follow:

CREATE TABLE `payments` (   `id` int(11) NOT NULL AUTO_INCREMENT,   `unlocked_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,   `paid_time` timestamp, .....

**Comment by snoski3** [comment]
@Ogy 
Are you able to get your SQL database working?  I found out that the script will install and configure MySQL.

**Comment by Ogy** [comment]
hello, somehow yes
but i drop xmr pool, and i'm using only ArqTras ETN pool
