### ISSUE TITLE
longRunner

### ISSUE THREAD

**Issue by Ogy** [Snipa22/nodejs-pool#225]
Hi, can you please help me with longrunner? it is throwing errors 
6|longRunn | 2017-12-24 13:34 +01:00: Error: You specified keyIsUint32 on the Dbi, so you can't use other key types with it.
6|longRunn |     at /home/xmr/nodejs-pool/lib/local_comms.js:638:46
6|longRunn |     at Array.forEach (<anonymous>)
6|longRunn |     at /home/xmr/nodejs-pool/lib/local_comms.js:630:45
6|longRunn |     at nextTask (/home/xmr/nodejs-pool/node_modules/async/dist/async.js:5070:14)
6|longRunn |     at /home/xmr/nodejs-pool/node_modules/async/dist/async.js:5064:13
6|longRunn |     at apply (/home/xmr/nodejs-pool/node_modules/async/dist/async.js:21:25)
6|longRunn |     at /home/xmr/nodejs-pool/node_modules/async/dist/async.js:56:12
6|longRunn |     at /home/xmr/nodejs-pool/node_modules/async/dist/async.js:840:16
6|longRunn |     at /home/xmr/nodejs-pool/lib/local_comms.js:605:29
6|longRunn |     at /home/xmr/nodejs-pool/lib/coins/xmr.js:70:24
6|longRunn |     at /home/xmr/nodejs-pool/lib/support.js:103:20
6|longRunn |     at Object.parseBody (/home/xmr/nodejs-pool/node_modules/request-json/main.js:74:12)
6|longRunn |     at Request._callback (/home/xmr/nodejs-pool/node_modules/request-json/main.js:148:26)
6|longRunn |     at Request.self.callback (/home/xmr/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
6|longRunn |     at emitTwo (events.js:126:13)
6|longRunn |     at Request.emit (events.js:214:7)

 mdb_stat -fear ~/pool_db/
Environment Info
  Map address: (nil)
  Map size: 25769803776
  Page size: 4096
  Max pages: 6291456
  Number of pages used: 547129
  Last transaction ID: 74049
  Max readers: 512
  Number of readers used: 24
Reader Table Status
    pid     thread     txnid
     25634 7fecca5e9740 73888
     26135 7f33cd3e5740 73897
     26163 7fdb61ea3740 73904
     26191 7f769b3f9740 73912
     26218 7fee2c37d740 73918
     26255 7f974cd9a740 73926
     26282 7fb046531740 73932
     26421 7efc397b4740 73941
     26448 7ff96c3b4740 73947
     26475 7f54f990b740 73955
     26502 7ff10282a740 73961
     26529 7f76157f3740 73971
     26556 7faee63f1740 73979
     26695 7f69d41f2740 73986
     26722 7f662f011740 73993
     26749 7f861c1ea740 74000
     26776 7f6486874740 74014
     26803 7ff663218740 74021
     26830 7f2325a29740 74029
     26970 7fbc160b8740 74035
     26997 7ff6431de740 74036
     27024 7fc37f0ba740 74043
     27051 7f7303e08740 74049
Freelist Status
  Tree depth: 3
  Branch pages: 10
  Leaf pages: 1470
  Overflow pages: 0
  Entries: 49003
  Free pages: 545436
Status of Main DB
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 3
Status of blocks
  Tree depth: 0
  Branch pages: 0
  Leaf pages: 0
  Overflow pages: 0
  Entries: 0
Status of cache
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 7
  Overflow pages: 79
  Entries: 22
Status of shares
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 9
  Overflow pages: 0
  Entries: 1667

**Comment by bobbieltd** [comment]
I got this error two ( I setup Aeon pool ). What does this error mean :( ?

**Comment by bobbieltd** [comment]
![longrunner error](https://user-images.githubusercontent.com/29669374/34340814-9129c9cc-e9bd-11e7-9cf6-3b7222d09f74.png)

**Comment by Ogy** [comment]
it is caused by remoteShare (mysql) i have caddy running only on http (there is a firewall with NAT before)
i had in mysql https:// which isn't reachable localy, i set http and problem is resolved

**Comment by CoinLogik** [comment]
I don't see how http vs https has anything to do with `You specified keyIsUint32 on the Dbi`. Would love to know why this error is happening.
