### ISSUE TITLE
i can`t complete it please help to make the pool alive

### ISSUE THREAD

**Issue by 3bkry** [Snipa22/nodejs-pool#226]
Hello,
Please tell me what the next steps 

![image](https://user-images.githubusercontent.com/14781002/34340565-1c9e8116-e98f-11e7-86b8-b5192241e62a.png)

**Comment by bobbieltd** [comment]
What do you mean "next steps" ? You run a miner from your PC to this pool address : your IP:3333 , check website and server (pm2 monit). The hardest thing is to test the payment, you need alot of hashing power and time. You can lose money (hashing power = money).

**Comment by ArqTras** [comment]
You have a lot of restarts.
login to admin section and update configuration for daemon ip, port, wallet address and other stuff.
More info on wiki (top site)

**Comment by 3bkry** [comment]
![image](https://user-images.githubusercontent.com/14781002/34355897-8e30914a-ea41-11e7-8b6b-958f97e51c10.png)

can you please help me.
i did it on this ip http://88.198.43.221/
but i can`t access this port 3333 for example http://88.198.43.221:3333

**Comment by bobbieltd** [comment]
As ArqTras pointed out. Your setup got alot of errors (restarts). Check “pm2 monit” command. Moreover, you should not install on root as Readme is written. I don’t think your pool funtions. You need reinstall it and check again if there is any errors.

**Comment by 3bkry** [comment]
i already reinstalled it and i think everything working well but the only problem that  i can`t access the pool ports like that http://88.198.43.221:3333 and i tried to start minig on it but it wasn`t work.

![image](https://user-images.githubusercontent.com/14781002/34357533-9547096e-ea50-11e7-8d01-31c13bdad27d.png)
![image](https://user-images.githubusercontent.com/14781002/34357562-e64587d2-ea50-11e7-9edc-de1edfb5ed05.png)

**Comment by ArqTras** [comment]
Wait until block manager finish adding blocks / sync with database

**Comment by bobbieltd** [comment]
@3bkry Can you check your longRunner ? “pm2 log longRunner” to see red lines if there are any.

**Comment by 3bkry** [comment]
@bobbieltd  
![image](https://user-images.githubusercontent.com/14781002/34358740-19779212-ea5b-11e7-8f41-84eb70d700d7.png)

**Comment by 3bkry** [comment]
and /home/admin/.pm2/logs/longRunner-error-6.log contain 
![image](https://user-images.githubusercontent.com/14781002/34358822-9bbec5e2-ea5b-11e7-81b3-acb56b6a01d2.png)

**Comment by 3bkry** [comment]
Do you think there is a problem ... I am waiting block manager to finish ! but i don`t know if there is a problem please help me.

**Comment by bobbieltd** [comment]
Don’t waste your time. Your pool won’t work. I and several people encounter this errors. I’ll find a solution, I’m reinstalling the pool again and again to debug (now the 15th time ;( ). See this #217

**Comment by 3bkry** [comment]
@bobbieltd 
you can try to change this code to false 
I am waiting block manager to finish and i`ll try too.
 the location of the file /home/username/nodejs-pool/lib/local_comms.js

![image](https://user-images.githubusercontent.com/14781002/34359990-591881a6-ea65-11e7-9ab0-69e4ac733969.png)

**Comment by bobbieltd** [comment]
@3bkry Do you understand the code ? I don’t. Why is it true of false ? If we change anything in the code, we need to know what it is. The risk is huge. I’m not coder.

**Comment by 3bkry** [comment]
i think the error because of a null or invalid value in the database ... the value should be unit32 

> The UInt32 value type represents unsigned integers with values ranging from 0 to 4,294,967,295.

so what if we change this condition to false.

the error will disappear but we should find where is the invalid value.

**Comment by bobbieltd** [comment]
In my point of view, keyIsUnit32 means the key is integer in shares and blocks. It you changed it to false, it would triger other errors anyway. Key being integer (true) seems correct to me. You should find which part give uninteger key ( non integer ) in database to longRunner.

**Comment by 3bkry** [comment]
@bobbieltd 
4294967295
1000000000000
check this file.
I am still waiting blockmanger to end. 

![image](https://user-images.githubusercontent.com/14781002/34361406-7b0c4bc8-ea72-11e7-97da-051a2b7e06c4.png)

**Comment by ArqTras** [comment]
Write directly to me support@supportaeon.com 
Maybe I can help

**Comment by 3bkry** [comment]
the same problem.
i contact you if you can help please tell me if you need ssh access
![image](https://user-images.githubusercontent.com/14781002/34372726-546e5d54-eadf-11e7-8ae6-446c723f0222.png)

**Comment by 3bkry** [comment]
@bobbieltd Are you solved the problem ?

**Comment by bobbieltd** [comment]
@3bkry Yes. It comes from NVM comptability. Change NVM back to 6.9.2 won’t make errors anymore. See this #230

**Comment by 3bkry** [comment]
I need to thank @ArqTras  for his supporting he helped me to install the pool. you are a genius  ^_^
I send him the root access and he do the installation from scratch for free. he really a good man thanks very much to you.

**Comment by bobbieltd** [comment]
@3bkry Totally agree. Managing a pool is not easy, you need to learn moẻ.
@ArqTras Without you, I don’t think I can set up my pool. I hope you’ll help us more in the future. When I got coins, I’ll donate to your coffee ☕️ :)

**Comment by ArqTras** [comment]
Topic to close - pool work - no extra info on this issue. 
Check all dep and wiki for solution, read carefully what to do step by step.
