### ISSUE TITLE
longRuner

### ISSUE THREAD

**Issue by 1rV1N-git** [Snipa22/nodejs-pool#227]
This code don't get oldest locked block. it gets first random locked blocks.
If you have some unlocked block, it can be problem.
I think this need to get all unlocked blocks sort it by "timestamp" then get oldest.

     this.getOldestLockedBlock = function(){
        this.refreshEnv();
        debug("Getting the oldest locked block in the system");
        let txn = this.env.beginTxn({readOnly: true});
        let cursor = new this.lmdb.Cursor(txn, this.blockDB);
        let highestBlock = null;
        for (let found = cursor.goToFirst(); found; found = cursor.goToNext()) {
            if (highestBlock !== null){
                break;
            }
            cursor.getCurrentBinary(function(key, data){  // jshint ignore:line
                let blockData = global.protos.Block.decode(data);
                if (blockData.unlocked === false){
                    highestBlock = blockData;
                }
            });
        }
        cursor.close();
        txn.commit();
        if (highestBlock !== null) {
            debug("Got the oldest locked block in the system at height: " + JSON.stringify(highestBlock));
        } else {
            debug("There are no unlocked blocks in the system.  Woohoo!");
        }
        return highestBlock;
    };

**Comment by Snipa22** [comment]
LMDB is a linear KV store, so assuming that you havn't changed the order of your blocks, this will continue to display the oldest locked block, as the LMDB store is keyed off the block height.

**Comment by 1rV1N-git** [comment]
I, too, thought so, but in fact I have more than once seen that he takes not the last block and saves me the buffer callback(null, body.height - Math.floor(global.config.payout.blocksRequired/2), Math.floor(body.difficulty * global.config.pplns.shareMulti * 5));
