### ISSUE TITLE
Admin Api beginner question

### ISSUE THREAD

**Issue by tzhbami7** [Snipa22/nodejs-pool#228]
Hi there,

I've succesfully deployed a new pool and it seems to work. It's accepting miners/hashes as shown on the last image but I'm wondering if everything is alright.

There are no errors showing up but I'm still wondering a bit about the admin dashboard (pplns)
Shares and Target Shares are showing 0. Is this because I haven't found a block yet?

![screen01 - edited](https://user-images.githubusercontent.com/401883/34360858-0ece97a2-ea65-11e7-8032-99956b49634a.png)

Since the pool is accepting miners - does that meen that it is configured and working. It would be kinda funny if the pool is sending it results into a black hole :P 

![screen03](https://user-images.githubusercontent.com/401883/34360630-d811e630-ea62-11e7-8d1f-0586e92bb6d6.png)

Thanks for the support!

**Comment by 1rV1N-git** [comment]
after block will be found you show it

**Comment by mxjoe** [comment]
Please close.
