### ISSUE TITLE
Solution for new installation errors (longRunner,...) from recent NVM 8.9.3 update

### ISSUE THREAD

**Issue by bobbieltd** [Snipa22/nodejs-pool#230]
@Snipa22 Could you please check if your code is compatible with NVM 8.9.3 ? As your recent change NVM from 6.9.2 to 8.9.3 makes some errors when running pool ( especially longRunner and pool module)

As for any one who tries to install recently ( last 6 days ) and get errors, you can run the old deploy.bash ( or you can fork Snipa22’s repository, change only all nvm lines with 8.9.3 to 6.9.2 in deploy.bash, your pool is still deployed from Snipa code repository )

**Comment by mtompkins** [comment]
I confirm these findings and it is relevant / remedies #217

**Comment by Snipa22** [comment]
I confirmed this working on my test versions, I'll have to check either way.  Most likely, there's something converting incorrectly to string.  If you run through the function that's generating the errors, you should be able to isolate and PR a fix.

**Comment by mtompkins** [comment]
I'll definitely revert if I can find the culprit. Thanks again for your project and support.

**Comment by Snipa22** [comment]
I've made a quick tweak, please check and verify.  I'm unable to repro on my test rigs.

**Comment by AndrVdov** [comment]
`blockID = **Number**((blockID - lastBlock+1) * -1);` // _don't work_

_try_

`for (let found = (cursor.goToRange(**parseInt**(blockID)) === blockID); found; found = cursor.goToNextDup()) {`

**Comment by Snipa22** [comment]
If that try is working, let me know, and I'll pull it into the core system.  Like I said, I'm unable to repro, so I'm relying on people's errors. :)

**Comment by AndrVdov** [comment]
tested, it worked correctly

**Comment by Tyldar** [comment]
I can confirm too, it's working with the new solution

**Comment by bobbieltd** [comment]
Could anyone debug to find the real issue ? 
The tweak is not a perfect solution.
BlockID should be always integer without parseInt function.
Why doesn’t error happens at the beginning of scanning ? 
What a pity. I’m noob at coding , I’ve tried to understand the code but not yet.

**Comment by mxjoe** [comment]
I created a pull request #260 which fixed the problem on my server. This fix is intended for NVM 8.9.3 if you are running versions prior to NVM 8 it might not work.

To all, please give feedback.

**Comment by bobbieltd** [comment]
parseInt() worked when I tested it. But I prefer nvm 6.9.2 solution because putting parseInt() seem nonsense. It seems there are not many coders debugging it. I close this issue to leave place for others.

**Comment by bobbieltd** [comment]
Great thanks to @CoinLogik for finding the bug. #274
