### ISSUE TITLE
aeon hashrate seems like doubles

### ISSUE THREAD

**Issue by aeon-team** [Snipa22/nodejs-pool#231]
Hi, trying to configure pool to work with Aeon, seems like i'm very close to finish :) except one thing - aeon network hashrate is showing 33MH on Dashboard right now. All other parameters diff, height is fine. How can I fix this?

It's a test installtion on Ubuntu and is based on deploy_aeon.bash script.

**Comment by sebseb7** [comment]
aeon is cryptonight light, therefore most cryptonight miners achive double the hashrate.

**Comment by ArqTras** [comment]
Edit poolui/utils/stings.js

.filter('difficultyToHashRate', function() {
  return function(hashrate) {
    return Math.floor(hashrate / 240)
  };

**Comment by bobbieltd** [comment]
@ArqTras Thanks. It works.
