### ISSUE TITLE
API unprotected

### ISSUE THREAD

**Issue by sunxfof** [Snipa22/nodejs-pool#232]
API is open to the wild, and I have seen cc attacks continously, I'm considering adding an authenticating layer to the api to solve this.

**Comment by Snipa22** [comment]
All important portions of the API are protected.  Authentication of the rest makes absolutely no sense.

**Comment by sunxfof** [comment]
I mean everyone can check the status of all hashrates, including blank address, this causes a lot of strees on the API server. I want to add an authentication layer to allow only legitimate API query.
