### ISSUE TITLE
Port difficulty not taken

### ISSUE THREAD

**Issue by Tyldar** [Snipa22/nodejs-pool#235]
Hi,

I've set up a port with a static difficulty of 650000.
When trying to connect with NiceHash on the port, I get this error : 

"Error: Pool difficulty too low (provided=200007.790584, minimum=400000)"

When I add the +650000 on the address, NiceHash connect fine.

Why the static port diff isn't taken in consideration?

Thanks

**Comment by bobbieltd** [comment]
I don’t know it but I’m interested in this. How can you connect NiceHash to your pool ? What’ll happen with payments to the miners ?

**Comment by 1rV1N-git** [comment]
@Tyldar Check ./lib/coins/xmr.js 
    this.niceHashDiff = 200000;

**Comment by Snipa22** [comment]
No ports support static diff.  Also, your NH diff setting should be changed to properly support this.  I've updated the public repo at this time.
