### ISSUE TITLE
Can you provide server addresses for Asia, especially China?

### ISSUE THREAD

**Issue by bodo005** [Snipa22/nodejs-pool#239]
I was too late in mining in China to find a good solution to the delay issue

**Comment by bobbieltd** [comment]
Mine at supportxmr.com , they got servers in Hong Kong.

**Comment by bobbieltd** [comment]
@bodo005 If I answer correctly your question, could you please close this issue ? Thank you.

**Comment by p2svn** [comment]
p2s.com.vn
we have pplns, pps, solo with lowest fees.
