### ISSUE TITLE
fresh install - pool only listening on 127.0.0.1

### ISSUE THREAD

**Issue by FurianXO** [Snipa22/nodejs-pool#241]
I attempted change this in the database (pool.ports ip_address), but every time i restart the pool, it changes it back.  I am not able to log into http://pool/admin.html, so I'm not sure where else I can set this at.  I'd also like to change some of the port numbers for miners.

If i try to change the bind ip in config.json to 0.0.0.0, the default ports (3333,5555,7777,9000) do not start up when I restart the pool.

**Comment by bobbieltd** [comment]
Any pm2 error logs ? Try change pool : 1 or 2 in config.json to test with 3333,5555,7777 port.

**Comment by camthegeek** [comment]
Making changes through /admin.html will not work efficiently.

If you're making the pool publicly available, it's best to use the public IP of server under bind IP in the config. I would imagine that you can not override previously entered pools into the database through the config (example, changing the bind IP without changing the pool #). To change ports, use MySQL CLI to insert or update ports. After you get this far, it is easier to modify everything using MySQL CLI. Look into how to login to MySQL via CLI and how to change settings this way or reinstall the pool software with the appropriate settings.

**Comment by p2svn** [comment]
config ip in nodejs-pool/config.json
with bind ip is external ip

**Comment by FurianXO** [comment]
This is behind a firewall, so i was going to set the bind ip to 0.0.0.0.  I was able to get this to work by changing the pool id in the config.json from 0, to 1, then setting the bind ip to 0.0.0.0
