### ISSUE TITLE
can not add/modify port

### ISSUE THREAD

**Issue by p2svn** [Snipa22/nodejs-pool#243]
hi ! i tried to change port or add port ( solo/pps/pplns ) but it not work. how to add port ?

**Comment by bobbieltd** [comment]
Mysql to modify/add in database + restart the pool.

**Comment by p2svn** [comment]
i was tried in database, but port auto remove...

**Comment by bobbieltd** [comment]
There are two tables. Perhaps, you changed in ports. You should change in port_config.

**Comment by p2svn** [comment]
thanks you. i changed successfull.
