### ISSUE TITLE
how can I check if mailgun is working?

### ISSUE THREAD

**Issue by aeon-team** [Snipa22/nodejs-pool#244]
I've configured mailgun account and set it in database config of the pool. How can check that pool will notify me of any problems? I was trying to stop some services (paement for example) to make it send me a message, but it didnt. What else should be done to make it work?

**Comment by bobbieltd** [comment]
Could you please close your old issue because it’s solved ?

**Comment by bobbieltd** [comment]
Thanks. For modules, I think pm2 will restart the module. For mailgun, I think it’s for informing the miners about start/stop of each miner. You can test by pointing one miner to your pool ( pass : “username:youremail@gmail.com” ). It’ll send you email each time when your miner start or stop mining.
