### ISSUE TITLE
Does this caddy from snipanet.com worth trust?

### ISSUE THREAD

**Issue by wenewzhang** [Snipa22/nodejs-pool#249]
In the deploy.bash,
It's download  caddy from snipanet.com,
code:
curl -sL "https://snipanet.com/caddy.tar.gz" | tar -xz caddy init/linux-systemd/caddy.service
sudo chmod 644 /etc/systemd/system/caddy.service
sudo systemctl daemon-reload
sudo systemctl enable caddy.service
sudo systemctl start caddy.service

does this caddy from snipanet.com worth trust?

Thanks

**Comment by Snipa22** [comment]
This is the caddy.tar.gz that was originally available from the Caddy website, before they changed their policies.  I simply re-hosted it, as there's not a good way to auto-download any longer.
