### ISSUE TITLE
minergate gui support

### ISSUE THREAD

**Issue by minecoins** [Snipa22/nodejs-pool#25]
in general pool doesn't accept connections if password is not set (empty). Since Minergate GUI doesn't have password field it can't connect.

**Comment by Snipa22** [comment]
{"id":"29","jsonrpc":"2.0","method":"login","params":{"agent":"MinerGateWin/6.6","login":"A2MSrn49ziBPJBh8ZNEhhbfyLMou6mao4C1F5TLGUatmUnCxZArDYkcbAnVkVEopWVeak2rKDrmc8JpoS7n5dvfN9YDPBTG","pass":""}}
