### ISSUE TITLE
multi-hashing install error

### ISSUE THREAD

**Issue by LannSoros** [Snipa22/nodejs-pool#254]
npm install multi-hashing

> multi-hashing@0.0.10 install /home/pooldaemon/nodejs-pool/node_modules/multi-hashing
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/pooldaemon/nodejs-pool/node_modules/multi-hashing/build'
  CXX(target) Release/obj.target/multihashing/multihashing.o
../multihashing.cc: In constructor ‘CNAsyncWorker::CNAsyncWorker(Nan::Callback*, char*, uint32_t)’:
../multihashing.cc:80:16: warning: ‘CNAsyncWorker::input’ will be initialized after [-Wreorder]
         char * input;
                ^
../multihashing.cc:79:18: warning:   ‘uint32_t CNAsyncWorker::input_len’ [-Wreorder]
         uint32_t input_len;
                  ^
../multihashing.cc:59:9: warning:   when initialized here [-Wreorder]
         CNAsyncWorker(Nan::Callback *callback, char * input, uint32_t input_len)
         ^
../multihashing.cc: In constructor ‘CNLAsyncWorker::CNLAsyncWorker(Nan::Callback*, char*, uint32_t)’:
../multihashing.cc:121:16: warning: ‘CNLAsyncWorker::input’ will be initialized after [-Wreorder]
         char * input;
                ^
../multihashing.cc:120:18: warning:   ‘uint32_t CNLAsyncWorker::input_len’ [-Wreorder]
         uint32_t input_len;
                  ^
../multihashing.cc:100:9: warning:   when initialized here [-Wreorder]
         CNLAsyncWorker(Nan::Callback *callback, char * input, uint32_t input_len)
         ^
  CC(target) Release/obj.target/multihashing/cryptonight.o
../cryptonight.c: In function ‘cryptonight_hash’:
../cryptonight.c:333:14: warning: passing argument 1 of ‘CNKeccak’ from incompatible pointer type [-Wincompatible-pointer-types]
     CNKeccak(&ctx->state.hs, input);
              ^
../cryptonight.c:228:13: note: expected ‘uint64_t * {aka long unsigned int *}’ but argument is of type ‘union hash_state *’
 static void CNKeccak(uint64_t *output, uint64_t *input)
             ^
../cryptonight.c:333:30: warning: passing argument 2 of ‘CNKeccak’ from incompatible pointer type [-Wincompatible-pointer-types]
     CNKeccak(&ctx->state.hs, input);
                              ^
../cryptonight.c:228:13: note: expected ‘uint64_t * {aka long unsigned int *}’ but argument is of type ‘const char *’
 static void CNKeccak(uint64_t *output, uint64_t *input)
             ^
../cryptonight.c:337:21: warning: pointer targets in passing argument 1 of ‘ExpandAESKey256’ differ in signedness [-Wpointer-sign]
     ExpandAESKey256(ExpandedKey);
                     ^
../cryptonight.c:84:20: note: expected ‘char *’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 static inline void ExpandAESKey256(char *keybuf)
                    ^
../cryptonight.c:413:18: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  uint64_t *dst = &ctx->long_state[c[0] & 0x1FFFF0];
                  ^
../cryptonight.c:425:21: warning: pointer targets in passing argument 1 of ‘ExpandAESKey256’ differ in signedness [-Wpointer-sign]
     ExpandAESKey256(ExpandedKey);
                     ^
../cryptonight.c:84:20: note: expected ‘char *’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 static inline void ExpandAESKey256(char *keybuf)
                    ^
../cryptonight.c:456:16: warning: passing argument 1 of ‘CNKeccakF1600’ from incompatible pointer type [-Wincompatible-pointer-types]
  CNKeccakF1600(&ctx->state.hs);
                ^
../cryptonight.c:161:13: note: expected ‘uint64_t * {aka long unsigned int *}’ but argument is of type ‘union hash_state *’
 static void CNKeccakF1600(uint64_t *st)
             ^
../cryptonight.c:377:47: warning: unused variable ‘b’ [-Wunused-variable]
     uint64_t a[2] __attribute((aligned(16))), b[2] __attribute((aligned(16)));
                                               ^
../cryptonight.c: At top level:
../cryptonight.c:267:13: warning: ‘mul’ defined but not used [-Wunused-function]
 static void mul(const uint8_t* a, const uint8_t* b, uint8_t* res) {
             ^
../cryptonight.c:271:13: warning: ‘mul_sum_xor_dst’ defined but not used [-Wunused-function]
 static void mul_sum_xor_dst(const uint8_t* a, uint8_t* c, uint8_t* dst) {
             ^
../cryptonight.c:281:13: warning: ‘sum_half_blocks’ defined but not used [-Wunused-function]
 static void sum_half_blocks(uint8_t* a, const uint8_t* b) {
             ^
../cryptonight.c:299:13: warning: ‘swap_blocks’ defined but not used [-Wunused-function]
 static void swap_blocks(uint8_t* a, uint8_t* b) {
             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from ../cryptonight.c:13:
../cryptonight.c: In function ‘ExpandAESKey256_sub2’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^
../cryptonight.c:71:7: error: called from here
  tmp4 = _mm_aeskeygenassist_si128(*tmp1, 0x00);
       ^
multihashing.target.mk:115: recipe for target 'Release/obj.target/multihashing/cryptonight.o' failed
make: *** [Release/obj.target/multihashing/cryptonight.o] Error 1
make: Leaving directory '/home/pooldaemon/nodejs-pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pooldaemon/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/home/pooldaemon/.nvm/versions/node/v8.9.3/bin/node" "/home/pooldaemon/.nvm/versions/node/v8.9.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pooldaemon/nodejs-pool/node_modules/multi-hashing
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pooldaemon/.npm/_logs/2018-01-05T16_16_32_786Z-debug.log

**Comment by Snipa22** [comment]
No AES-NI:
../cryptonight.c:71:7: error: called from here
tmp4 = _mm_aeskeygenassist_si128(*tmp1, 0x00);

**Comment by hokkjoy** [comment]
Is there an option to resort to software logic instead?
Also, is this a compile-time only dependency or would cross-compiling help?
