### ISSUE TITLE
4 Gb Ram ?

### ISSUE THREAD

**Issue by swa74** [Snipa22/nodejs-pool#257]
Good afternoon. Installed according to instructions, only amended and installed it on a processor without aes-ni. All the requirements stated 4 Gb Ram, and my server a day later came to 16 Gb of Ram, is this normal ? https://minexmr24.ru

**Comment by bobbieltd** [comment]
4Gb is not enough. I think 8Gb+.

**Comment by swa74** [comment]
Thank you, otherwise I began to worry

**Comment by swa74** [comment]
If anyone wants to test for the 1st block, I invite you to https://minexmr24.ru It does not guarantee the correctness of the operation, but I will try to check the details.

**Comment by mxjoe** [comment]
I am running a virtual Server with 4 GB of RAM and it is enough. But if you have a hundred miners I am pretty sure you need more RAM than this.

**Comment by swa74** [comment]
Thank you all, the question is closed.
