### ISSUE TITLE
Why are fees zero ? (pool fee, dev fee, codev fee)

### ISSUE THREAD

**Issue by bobbieltd** [Snipa22/nodejs-pool#259]
I got 3 ETN blocks found. Payments go correctly to miners but in balance. However, all fees type is zero ( pool has 0.4% fee with donation ). When I read the pool code, I can see it adds fee addresses to blockedAddress so payments won’t go to fees. So how and which will module send payments to three fee wallets ?

**Comment by 1rV1N-git** [comment]
Blockmanager distributes them to the "balance" table
Payment module send to you after free will be under feesForTXN

**Comment by bobbieltd** [comment]
@1rV1N-git Thank you. I don’t have any feesForTXN table ? Is that abnormal ? Moreover, in base.sql I don’t find a command that create feesForTXN. How can I check all three fees , could you provide more details ?

**Comment by 1rV1N-git** [comment]
in balance table you must have entry with pool_type is fees
feesForTXN  is Amount of XMR that is left from the fees to pay miner fees.
look into sql_sync
you need to run 
cd ~/nodejs-pool/sql_sync/
env PATH=$PATH:`pwd`/.nvm/versions/node/v8.9.3/bin node sql_sync.js

**Comment by bobbieltd** [comment]
Oppps, sorry I won't run sql_sync. I think we got some misunderstanding. 
"in balance table you must have entry with pool_type is fees" : yes, I got 3 addresses with fees (pool_type), 
"feesForTXN is Amount of XMR that is left from the fees to pay miner fees." : I got this in my config (mysql).
"look into sql_sync" : yes, SELECT from config_entry, INSERT into mysql. In fact, why do I need to put back those values and what'll change ? Same values (it's not my case but I assume that I manage XMR pool as others).
All amount in balance table with pool_type = fees are always zeros.
I'm newbie. Is that when block founds, the fees will increase ? or by other mechanism later ?

**Comment by 1rV1N-git** [comment]
fee adress, miner wallet address , pool address must be different addresses
"Is that when block founds, the fees will increase ?" yes. In blockmanager.js you may change 
debug("Made it to the point that I can update the balance for: " + balance_id + " for the amount: " + amount); on *console.log*("Made it to the point that I can update the balance for: " + balance_id + " for the amount: " + amount); and went block will be found in log file you will see who increased balance

**Comment by ArqTras** [comment]
It will increase when you have enabled dev donation and pool donation after block find

**Comment by bobbieltd** [comment]
@1rV1N- git You answer is much better. Do you know how can I see all debug , which command ? I don’t like much put more logs. Is there any way we can get debug logs files ?
@ArqTras : What do you mean enabled dev donation ? I never put 0. 0.4% pool fees, 6% for dev donation, 6% for poolDev donation.

**Comment by bobbieltd** [comment]
I prefer know the logic mechanism behind everything ( with code explanation if possible). Not changing this or that with your assumption without some explanations.
All fees are zero. The think I don’t understan that in the code, all fees are added to blockedAddress ( any explation ?). In my config,  pplnsFee = .4, devDonation = 6, poolDevDonation = 6.

**Comment by ArqTras** [comment]
I don't get it:
You have pool fees like : 
pplnsFee 0.4
devDonation 0
poolDevDonation 0
?
pplnsFee should be transfered when you hit over feesForTXN

**Comment by bobbieltd** [comment]
Question is Why all fees (pool, dev, poolDev) are Zero ? 
I’ll test by putting poolDonation = 0 and poolDevDonation = 0 to see if pool fee will be added.

**Comment by bobbieltd** [comment]
Here is the part of code in coin Javascript that I find : 
if (payee.poolType === "fees" && payee.address === global.config.payout.feeAddress && payee.amount >= ((global.support.decimalToCoin(global.config.payout.feesForTXN) + global.support.decimalToCoin(global.config.payout.exchangeMin)))) {
                    debug("This is the fee address internal check for value");
                    payee.amount -= global.support.decimalToCoin(global.config.payout.feesForTXN);
                } else if (payee.address === global.config.payout.feeAddress && payee.poolType === "fees") {
                    debug("Unable to pay fee address.");
                    payee.amount = 0;
                }

**Comment by bobbieltd** [comment]
I temporarily close this issue. This need to be debugged with live pool and I can’t do it at my pool. If someone can help, please comment below and I’ll reopen the issue.

**Comment by bobbieltd** [comment]
@1rV1N-git ArqTras tried your advice but I still can’t find the issue when I look at logs. If possible, can I chat with you ? My email :  support@mail.semipool.com . P/s : I have no intention to setup Monero so no direct pool competition ( out of my capability ).
