### ISSUE TITLE
PPS paying out for others blocks

### ISSUE THREAD

**Issue by azaryc2s** [Snipa22/nodejs-pool#276]
So i spent some time already reading the code and i find (at least) one thing strange. Since the PPS-Payout-Balance-Update is done "on the main loop" - as referred to it in the code, it has the side effect, that it's called every time a new block (within the range specified) is found in the blockchain - regardless of who found this block. So it seems to me, like the pool is increasing the miner balance even for blocks it didn't find (blockScanner() -> blockQueue). Is this intended? Or am i missing something?

Aditionally if it was lucky and found a block at 10% luck, it's also only paying 10% of the reward and if it had a bad luck (let's say 500%) it's paying out 5x the block reward.
Now i understand, that the luck is gonna even out (ideally) but this just creates unnecessary need for a buffer on the pool wallet. You could also just weight down (or up) the shares depending on the overall share-sum from all miners.

And if i'm right about the first issue, than those two combined make the pool even lose money instead of getting fees. (Imagine having to pay for 100 blocks without finding any)

**Comment by Snipa22** [comment]
This is expected and normal.  PPS is "Pay Per Share"  Not "Pay Per Share Per Found Block."
