### ISSUE TITLE
 [RPC0]Block is already in blockchain

### ISSUE THREAD

**Issue by myaeon-ru** [Snipa22/nodejs-pool#281]
Is it normal? repeated messages in wallet log?!

Jan 24 18:54:57  [1839]: [RPC0]HTTP [127.0.0.1] POST /json_rpc
Jan 24 18:54:57  [1839]: [RPC0]/json_rpc[getbalance] processed with 0/0/0ms
Jan 24 18:54:57  [1839]: [RPC0]Block is already in blockchain: b0cb7a8a95ecb3967fe645d01949aed33f8c477217c633f724c7cc94469c2ac4
Jan 24 18:54:57  [1839]: [RPC0]Refresh done, blocks received: 0, balance: 6.013000000000, unlocked: 6.013000000000
Jan 24 18:54:57  [1839]: [RPC0]Block is already in blockchain: b0cb7a8a95ecb3967fe645d01949aed33f8c477217c633f724c7cc94469c2ac4
Jan 24 18:54:57  [1839]: [RPC0]Refresh done, blocks received: 0, balance: 6.013000000000, unlocked: 6.013000000000
Jan 24 18:54:57  [1839]: [RPC0]Block is already in blockchain: b0cb7a8a95ecb3967fe645d01949aed33f8c477217c633f724c7cc94469c2ac4
Jan 24 18:54:57  [1839]: [RPC0]Refresh done, blocks received: 0, balance: 6.013000000000, unlocked: 6.01300000000

**Comment by camthegeek** [comment]
Not related to this repo.

This is related to aeon daemon/wallet (and it is perfectly okay to see these messages).
