### ISSUE TITLE
blockManager not at the same height as the network

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#288]
My AEON nodejs-pool blockManager module log:
```
2|blockMan | Scan complete, unlocking remainder of blockManager functionality.
2|blockMan | 2018-02-02 17:23 +00:00: Performing PPS payout on block: 919692 Block Value: 11.479555343734
2|blockMan | 2018-02-02 17:23 +00:00: PPS payout cycle complete on block: 919692 Block Value: 11.479555343734 Block Payouts: 0 Payout Percentage: 0%
2|blockMan | 2018-02-02 17:23 +00:00: Scan complete, unlocking remainder of blockManager functionality.

```
But the AEON network is at the 919724 height (last mined block 919723).

That's a 32 blocks difference.

Is that expected?

Asking because my pool is in a very bad luck of 450%+ effort, so I'm trying to check if there's anything wrong with the pool.

Thank you

**Comment by bobbieltd** [comment]
What is your average effort ? Do you receive any email “Pool is behind ... blocke” ?

**Comment by vitorgatti** [comment]
We eventually found a block, even after a huge effort...
The average effort is now 99,88%

I didn't receive an email with that alert

blockManager now is at height 920066, and the network is at 920098 (32 difference)

I guess this is expected then... just don't know why

**Comment by ArqTras** [comment]
blockManager - Unlocks blocks and distributes payments into MySQL
This module run on scheduled time, it always show behind block.
So You r mining new block, but unlocker do its job after maturity (for aeon next 60 blocks) depend of your settings
