### ISSUE TITLE
pls help me develop

### ISSUE THREAD

**Issue by vtnplus** [Snipa22/nodejs-pool#297]
Hi develop group. I don't understand
what is this.prefix = 178;
Where i can check prefix when i want create new coin info in lib/coin/newcoin.js

**Comment by bobbieltd** [comment]
Write a Javascript and use this cnUtil.address_decode(....) , put whatever coin address inside to know prefix. Any way, if you don’t mind, give me the coin name, I’ll provide prefix for you.

**Comment by Snipa22** [comment]
Or go look inside the coin source code, because that's where anyone sane goes and gets them. :)

**Comment by vtnplus** [comment]
Sample coins.
https://bitcointalk.org/index.php?topic=2813261.0

Website: https://stellite.cash
Website Mirror: https://stellitecoin.github.io
Block Explorer: https://explorer.stellite.cash/

@bobbieltd you can write for me cnUtil.address_decode(....) with it ?
@Snipa22 i have see in code method "prop" with prop payment can work ? or not ?. if work what i need config use prop method ?

**Comment by Snipa22** [comment]
Nope.  Never implemented it.  Not enough call/desire to.

**Comment by vtnplus** [comment]
ok. nodejs-pool is supper pool nodejs language i think :). This is good project
"go look inside the coin source code, because that's where anyone sane goes and gets them" <== are you know where in code ? 
thanks master

**Comment by vtnplus** [comment]
var cnUtil = require('cryptonote-util')
this.prefix = cnUtil.address_decode(new Buffer(config.poolServer.poolAddress))
this.intPrefix <=== What is this friend. where i can decode it

**Comment by bobbieltd** [comment]
@vtnplus It’s better to stay away this coin. intPrefix is for integrated address. I don’t want you to waste your time for this fork. So you should choose other coin.

**Comment by bobbieltd** [comment]
@vtnplus Here is the source code https://github.com/stellitecoin/Stellite/tree/master/src  , prefix and intPrefix is in it ) (...BASE58_PREFIX...). Please close this issue because we still have more issues to solve, my friend ? This coin is not welcom.

**Comment by vtnplus** [comment]
thanks @bobbieltd

**Comment by bobbieltd** [comment]
Thanks. For your question : 
uint64_t const CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX = 0x2419;
uint64_t const CRYPTONOTE_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX = 0x7096;
uint16_t const P2P_DEFAULT_PORT = 20188;
In decimal :
this.prefix = 9241;
this.intPrefix = 28822;

It's ETN/XMR's fork, so you just copy xmr.js in coin and payment to new file stl.js , it will work with nodejs-pool.

**Comment by vtnplus** [comment]
thanks  you @bobbieltd . 
when i rent hash power form nicehash ( diff 400015) but all bad share 
password nicehash ( x )
Are you solution for me ?

**Comment by bobbieltd** [comment]
NiceHash need 400000 difficulty port (add a port like that). Anyway, you should try with mining by your PC first to see if shares are valid.

**Comment by bobbieltd** [comment]
Oạch, người Việt hả. Nói mẹ tiếng Việt đi cho rồi 😂

**Comment by vtnplus** [comment]
Á đù. nhận email hơi bị bất ngờ

**Comment by bobbieltd** [comment]
Mấy cái coin lởm ( không có exchange ) đừng làm. Mất time. stl.js thì dùng etn.js nhé (lấy bên repo mình), branch nodejs-pool-etn. Có điều mình không thích giúp đối thủ cạnh tranh ( hình như bạn làm pool cho cả Electroneum và Ethereum, hai cái này trong điểm của mình) 😂😂😂.

**Comment by vtnplus** [comment]
Mới đây truy thu điện cao quá mới làm ctytonight. Chứ trước toàn ETH va EQHASH 🗡

**Comment by bobbieltd** [comment]
Ác gì đâu, pool mình ETN mà. Sửa codes chạy ngon lành rồi. STL thoải mái đi. Hình như bạn là xeminer trước bị thằng Arq đem ra làm chuột bạch thí nghiệm và lên chat dành khách đúng kg ? Nó rành cấu hình thôi, codes dốt lắm, cái ETN chạy là do mình fix. Trước chục chặc payment thì do MO fix. Tóm lại nodejs-pool ngon lành. Pool đối tác mình cũng sắp open source code cho ITNS rồi. Hiện tại có 5 coins mình né hỗ trợ : XMR, ETH, ETN, AEON và ITNS.

**Comment by vtnplus** [comment]
cryptonote ITNS ngon nhi. cho minh xin 2 config blocktemplate cua no di. chuyen trai qua dao :D

**Comment by bobbieltd** [comment]
ITNS không copy kiểu bình thường được đâu nha. Thằng đấy nó sửa code cả đống mới chạy được. Hiện tại nó chưa open source, mình cũng không nắm được hết codes của nó. Pool của nó đây https://itnspool.net , khi nào nó chịu open source thì mình bảo.

**Comment by vtnplus** [comment]
uh con do la crytonode ma. cai pool dang co la crytonight. khac nhau ve block template.

**Comment by bobbieltd** [comment]
Chuẩn khỏi chỉnh. Đấy là nodejs-pool cho forknote (ITNS) và cần chỉnh lại util + code vài chỗ vì khác l nhau block template (hơi khác thôi). Mình không nắm được source ( có nắm đk cũng không cho bạn được vì của người ta ). Mấy hôm trước có thảo luận thì nó bảo từ từ sẽ open source cái pool đấy.

**Comment by bobbieltd** [comment]
For info, here is recently released ITNS (forknote) nodejs-pool for everyone from Venthos : https://github.com/Venthos/nodejs-pool
