### ISSUE TITLE
What setting to change network hashrate? Currently showing double what it should?

### ISSUE THREAD

**Issue by LegolasGChief** [Snipa22/nodejs-pool#299]
Hey everyone I just started switching over from universal pool.

The network hashrate is double what it should be and even though I have set aeon as the main coin it still shows XMR all over the site.

How do I fix this?

![image](https://user-images.githubusercontent.com/25286936/36010956-0559fcac-0d4c-11e8-905b-714822c0bd2a.png)

**Comment by BKdilse** [comment]
Utils/strings.js
last line Math.floor(hashrate / **120**
change it to **240**
