### ISSUE TITLE
pm2 restart api returns "[PM2][ERROR] Process api not found"

### ISSUE THREAD

**Issue by 78bash** [Snipa22/nodejs-pool#303]
I get the following error after doing `pm2 delete all` and start them back as per the readme, except
`pm2 restart api` returns `[PM2][ERROR] Process api not found`

**Comment by bobbieltd** [comment]
You start api by wrong way.
pm2 delete api
cd ~/nodejs-pool
pm2 start init.js --name=api --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=api
