### ISSUE TITLE
Minimum Payout not paying 1 wallet

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#306]
Hi,

I have a new Aeon pool running, 2 blocks found so far.
Minimum payout = 0.15 AEON.
Fees = 0.1

I can see 2 payments made for above 2 AEON
2 payment which should have been made for 0.79 AEON, hasn't processed.

Any ideas?

**Comment by bobbieltd** [comment]
Do they use PaymentID ? Payment threshold for exchange is higher.

**Comment by BKdilse** [comment]
I did think about that, ad maybe that is the reason.  They have not complained, I was just looking at worker payments, and noticed this one.

I don't have remote access to my DB, so can't check right now, but do you know which table/entries are created when users select custom payments/paymentids?

**Comment by BKdilse** [comment]
OK, got remote access.
Can confirm user has set a high minimum payout threshold.
