### ISSUE TITLE
Caddy high load

### ISSUE THREAD

**Issue by M5M400** [Snipa22/nodejs-pool#31]
Just did a clean install today and observing same behavior of caddy again. Uses more ressources than monerod at around 70req/sec

![caddy](https://cloud.githubusercontent.com/assets/22886679/23096421/78f12ed0-f61c-11e6-974c-8c113c6b0368.PNG)

replaced it with apache and apache doesn't even blink...

**Comment by Snipa22** [comment]
Caddy was selected for ease of use, automated SSL, and ease of integration
as we're moving towards websockets, which should drop this usage
significantly.  That being said, you're welcome to replace it in your
environment with any webserver you'd like

**Comment by M5M400** [comment]
I guess if I am the only one having this issue, then that's fair game

**Comment by mtompkins** [comment]
@M5M400 Would it be possible to share your apache config? .. I'd be very appreciative.
