### ISSUE TITLE
Fee Issue

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#311]
Just noticed that pm2 logs payments show Total Fee: NaN AEON.

I thought I changed all bit I needed to AEON.

Any pointers to which file handles the fee part?  Is it the coin.js in payment_systems?

**Comment by BKdilse** [comment]
Fee Wallet is also empty after 3 blocks.
Wallet Fee is set to **.1**

**Comment by bobbieltd** [comment]
Something is wrong. It should work with AEON. Is your fee adress correct ? It’s in blockManager. NaN AEON —> Did you change fee address in running ?

**Comment by bobbieltd** [comment]
Stop all modules and start them again.

**Comment by BKdilse** [comment]
Fee address is set.
What do you mean by "It's in blockManager"?  The address is in the SQL DB.

Fee address was synced initially when setup, and I can login to the Fee Wallet to refresh it.  I Just logged into it now, and refreshed, 0 balance.

All modules were restarted yesterday evening, I'll try another restart.

**Comment by camthegeek** [comment]
https://github.com/Snipa22/nodejs-pool/blob/master/lib/payment_systems/aeon.js#L185

Pool fees are paid when the exchange minimums are hit (in the pool fee wallet).

The total fee line usually is the fee that's set in SQL (0.01 for AEON).

**Comment by BKdilse** [comment]
I'm confused, these payments are not an exchange, they are to wallets only.  I would have thought the fee for each payment would have been 0.1% of the total AEON sent.  Am I thinking incorrectly on what the pplnsFee is?

Some of the settings in SQL:

pplnsFee = .1
exchangeMin = 1
walletMin = .15
feesForTXN = 1

**Comment by bobbieltd** [comment]
Your config is OK. You should check fees in the Balance not the Fee Wallet command line.

**Comment by camthegeek** [comment]
If your exchange payout amount is set to 1.0 AEON, the pool's fee wallet will be paid when it hits 1.0 AEON.

**Comment by BKdilse** [comment]
@bobbieltd  what do you mean the balance, is this in SQL or poolui?

**Comment by BKdilse** [comment]
@camthegeek isn't exchangeMin for minimum amount for exchange pay out Desc: "Minimum XMR balance for payout to exchange/payment ID"?

**Comment by BKdilse** [comment]
The way i see this working is that 0.1% of miner payments should end up in the Fee Wallet.  Is this not correct?

**Comment by bobbieltd** [comment]
BlockManager calculate payments (not module) into balance (mysql) at first. If your fee is small, payment module won’t send and keep it in balance table (mysql) and wait until fee is high enough to send.

**Comment by BKdilse** [comment]
Thanks makes sense. I'll check the tables later today.

**Comment by camthegeek** [comment]
So I'll explain this the easiest way I can in hopes that you get a more clear understanding. 

I will use the configuration that I have on https://aeonminingpool.com
payout  | pplnsFee                | 1.0  (solid 1% pool fee)
payout  | poolDevDonation         | 20 (20% of 1% pool fee goes directly to pool developer (Snipa))
 payout  | feesForTXN              | 0.01  (TX fee per payout to miners)
 payout  | exchangeMin             | 1 (payout to miners with exchange wallet)
 payout  | walletMin               | .25 (normal wallet payouts)

Now, to clear up the fees question and I'll repeat it again and will link the code and explain it.

> If your exchange payout amount is set to 1.0 AEON, the pool's fee wallet will be paid when it hits 1.0 AEON.

https://github.com/Snipa22/nodejs-pool/blob/master/lib/payment_systems/aeon.js#L185
` if (payee.poolType === "fees" && payee.address === global.config.payout.feeAddress && payee.amount >= ((global.support.decimalToCoin(global.config.payout.feesForTXN) + global.support.decimalToCoin(global.config.payout.exchangeMin)))) {`

Reading the line should be pretty simple. If the pool type being paid out is fees, and if the payee address is what you have in payout | feeAddress and if the amount is greater than or equal to your payout | feesForTXN (0.01) PLUS payout | exchangeMin (1.0), then carry on. At this point, it checks to make sure the payout amount is greater than 1.01 AEON. 2 lines down in the source, it removes the feesForTXN amount making your pool fee wallet payout at a minimum that is equal to the exchange payout minimum (1.00 AEON).

Using my example, it will take approximately 10-11 blocks before a pool fee payout  is ready.  

Using the variables you posted above @BKdilse
> pplnsFee = .1
> exchangeMin = 1
> walletMin = .15
> feesForTXN = 1

This will result in a payout after 100 blocks. Your wallet must hit atleast 2 AEON total before a payout is pushed. It will be sent 1 AEON and charged a 1 AEON total transaction fee. Consider lowering your feesForTXN! Baseline safe minimum is 0.01 AEON.

Also, if you wish to check the pool fee wallet balance, just run a sql query like 

select amount from \`balance\` where \`payment_address\` = 'pool_Fee_wallet_address';

**Comment by BKdilse** [comment]
Thanks very much the detailed explanation. Just watch needed.  I'll review my fees.

**Comment by bobbieltd** [comment]
@camthegeek I love the way you explain thing. Cool 👍👍👍. By the way, I have a question. What is the difference between payout.blockRequired vs payout.unlock_time ?

**Comment by bobbieltd** [comment]
Holy shit ! Your pool hashrate is 1.25 Mh/s, can you give my pool some kH/s. At the moment my AEON pool hashrate has total ~ 4 kH/s 😰😰😰. Solidarity 😂😂😂

**Comment by BKdilse** [comment]
Nooo. Give me some please.  Lol.  I'm on 31kh/s.  23kh/s is my personal miner. Rest is other miners.

**Comment by camthegeek** [comment]
@bobbieltd Regarding the difference

blockRequired is the maturity level. It is typically set to 60 blocks on most pools. It requires X amount of blocks to be found on the network before the block is unlocked and rewards are distributed. (X=blockRequired number)

I haven't found an actual use for unlock_time. This would be a @Snipa22 answer.

Re: Pool hashrate
I've made a lot of connections, built a community and constantly help many people! Also, we've been around since August 2017 (with a rebranding in October when Snipa opened the doors to this pool on AEON). Work hard at building your pools and don't get overly spammy with them :D

**Comment by bobbieltd** [comment]
@camthegeek Ouff, you are the biggest Aeon pool now. Congratulation ! Any bounty for Aeon new POW rebase 😂😂😂. Ring a bell 🙈
