### ISSUE TITLE
[AEON] Current effort becomes very different than the real block effort when the first raises above 300%.

### ISSUE THREAD

**Issue by curumimxara** [Snipa22/nodejs-pool#316]
There were multiple incidents where the current effort (represented on poolui as `{{(100 * poolStats.global.roundHashes / network.difficulty).toFixed(1) | number}}` went above 300%, more recently with a block that take us two days and made us go above 750%..

Whenever this happens and a block is found, the blocks page shows the effort as something a lot lower. Using the same example as above, the 750% block became a 271% block when it went to the blocks page. Code there is `{{::block.luck | number:0}}` which is a reference to the javascript: `luck = block.shares/block.diff*100;` which also requests the value from the API.

This might not sound major, but multiple miners came to ask if we're arbitrarily changing these values to make the average luck lower than what it should be. 

What would be the path to fix this? Change the API?

**Comment by camthegeek** [comment]
roundHashes does not always reset when a block is found which creates this issue.

The blocks page gets data directly from the api's /pool/blocks, which has the actual share count (this matters most!)

Additionally, poolUI issues aren't meant to go here.

**Comment by curumimxara** [comment]
> roundHashes does not always reset when a block is found which creates this issue.

The thing is, no blocks were found from 0% to 750%. The blocks page wasn't updated, so it was really the current effort for the pool. This wasn't the accumulated effort for 2 or 3 blocks.

> The blocks page gets data directly from the api's /pool/blocks

So does the poolstats.html, right? It gets the roundHashes from the API call on the app.js file (/pool/stats)

> Additionally, poolUI issues aren't meant to go here.

I'm unsure if this is a problem with poolui or with the API (since the front-end is just making the calls). Where would be the best place to report a possible issue with the API?

**Comment by bobbieltd** [comment]
@MoneroOcean Thanks MO, now I understand why I don’t have this issue 😂.

**Comment by bobbieltd** [comment]
Wait a second, we can resolve this issue by putting shareLogMulti >= 5, is it correct ?

**Comment by MoneroOcean** [comment]
Yes, it will help as well.

**Comment by vitorgatti** [comment]
my pool is having the same issue, where can I change this value?

thanks

**Comment by MoneroOcean** [comment]
local_comms.js:cleanShareDB function: replace 1.3 factor to some higher factor.

**Comment by vitorgatti** [comment]
thanks!

a question, though... any risks of database corruption if I change from 1.3 to 5?

**Comment by MoneroOcean** [comment]
No corruption unless your DB size is big already. If it is smaller than 5GB I do not think it will cause any issues.
