### ISSUE TITLE
Debug Log Location?

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#317]
I was able to setup the MySQL database with all of the tables.  My website is up and running, however I can't login to setup the pool fees or any other setting.
Where are the log files so I can see if the front end is connected to the database?

Thank you,

**Comment by TimeTravelersHackedMe** [comment]
If you can't login, maybe you're using the wrong username/password. Check the base.sql file for the default username/password for the Admin login. The password is stored in the e-mail field I believe until you reset it.

**Comment by snoski3** [comment]
@TimeTravelersHackedMe 
Step 6 - Hop into the web interface (Should be at http://<your server IP>/admin.html)
I tried to login using the IP address and hostname.  It still says "Please check your login details"

I'm looking for the log that show the login process.  For example, the user <username> with password <password> tried to connect to MySQL at <IP Address>:<port number>
or the security logs for MySQL to see who is trying to connect.

**Comment by TimeTravelersHackedMe** [comment]
Try logging in with the login information on the line in the base.sql file
that says Administrator.

**Comment by snoski3** [comment]
I did the following:
vi  /etc/mysql/my.ncf
Added the following to the bottom of the file
[mysqld_safe]
log_error=/var/log/mysql/mysql_error.log
 
[mysqld]
log_error=/var/log/mysql/mysql_error.log

Then restarted the service: service mysql restart
Here is the error when I viewed the error log:
![image](https://user-images.githubusercontent.com/5173575/36336101-5edbfb1e-134a-11e8-9fe2-30eca8c4d351.png)

Now I need to give root access and I should be good.

**Comment by snoski3** [comment]
@TimeTravelersHackedMe 
Well that didn't work, I matched the two root passwords, the MySQL and system login.  I still can't login to the web portal.
![image](https://user-images.githubusercontent.com/5173575/36352946-8d6bd256-1485-11e8-9b22-f9fbdde18643.png)
![image](https://user-images.githubusercontent.com/5173575/36352959-a99a7446-1485-11e8-975f-44e61471daf9.png)

**Comment by snoski3** [comment]
@Snipa22 
Do you have any ideas why I wouldn't be able to login to the web portal, even though root doesn't need a password to login?
![image](https://user-images.githubusercontent.com/5173575/36353009-60e79412-1486-11e8-9278-8667a1d71672.png)

Thank you,

**Comment by TimeTravelersHackedMe** [comment]
The web portal is using the pool user, not root.

**Comment by snoski3** [comment]
@TimeTravelersHackedMe 
Thanks, here is the permissions for the mysql pool account:
mysql> show grants for 'pool'@'localhost';
+---------------------------------------------------+
| Grants for pool@localhost                         |
+---------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'pool'@'localhost' |
+---------------------------------------------------+
1 row in set (0.00 sec)

Any ideas why it still won't work?

thanks,

**Comment by snoski3** [comment]
Reran script on a clean VM with no prep work, which resolved the issue.

**Comment by avense** [comment]
hello how you solve?
