### ISSUE TITLE
Sumo Pool Payments - incorrect

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#326]
sumo.js files for coin and payment system obtained from @bobbieltd. https://github.com/bobbieltd/nodejs-pool-1/

My pool has found it's 1st block.

Payment very low, and the rest sitting in the Pool's wallet.
New pool, so only 4 payees, each with very low due amount.

Not sure where to look to sort this out.

**Some stats:**
Mined	36.45
Paid		1.18
Balance	35.263228806
Shares	432,271,786

**Paid | Due | _Should have been paid (rough calculations)_**
1.180139394 | 0.00077816 | **_30.67537399_**
0.025532455 | 0 | **_0.639421532_**
0.246644529 | 0 | **_4.685326783_**
0.009228221 | 0 | **_0.380382384_**

DB Settings:
pplnsfee: .1
exchangeMin: 25
walletMin: .5
denom: .001
sigDivisor: 1000000000 (for easy reading: 1,000,000,000)
feesForTXN: .01
mixIn: 12

Does anyone have any input in how I can ensure future payments are correct?
Also, what is the best way to correct the payout for the 1st block?

**Comment by BKdilse** [comment]
updated original post with more details.

**Comment by bobbieltd** [comment]
Some first lucky blocks, the pool doesn’t distribute all rewards.
Sumo diff now : 6,350,973,114

**Comment by bobbieltd** [comment]
Reward distribution 432271768 / (2*6350973114  or shares / (2 * PPLNS diff), can you check that with your payment ? I’m lazy with math.

**Comment by BKdilse** [comment]
@bobbieltd I got worried, as I did not see this behaviour on my Aeon pool.  This was a lucky block, arrived soon.  So I am good to continue onto next block?

**Comment by bobbieltd** [comment]
Let’s do the math. Your pool reward distribution = 36.45 SUMO * 432271768 / (2*6350973114) = 1.24 SUMO. Boom ! Ereka ! Cool ! Your pool distribution is perfect. Keep it growing ! Fighting !

**Comment by BKdilse** [comment]
thanks @bobbieltd.
I understand about your pull, so the file isn't your creation.

Reward calculation also makes sense after you explained it.

And, yes, I do calculate the effort, which was 8% for this block (super lucky).  Aeon pool, 1st block was 139% effort, which explains why a larger payout was made.

I'll continue with pool growth.

Thanks again.

**Comment by bobbieltd** [comment]
Gotcha ! Your pools are very nice, I love them . https://sumo.pool.gntl.co.uk . Don’t fight each other on Reddit ! We are small pools, we need unite together to fight big pools ! Have a good luck ! Fighting !

**Comment by BKdilse** [comment]
Thanks, yes, we have to work together against the big beasts !
