### ISSUE TITLE
[AEON] My pool is holding some coins and didn't share with miners

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#330]
My AEON pool found the block  926750:
https://chainradar.com/aeon/block/dd1dac8d81ddcfe0a168a3ade927a3d5923a230711c8239fdd09ee8bf13a4da0

After maturing, the following showed up in logs:
`2018-02-22 16:00 +00:00: PPLNS payout cycle complete on block: 926750 Block Value: 11.174980827774 Block Payouts: 11.174980827774 Payout Percentage: 100%`

But no miners received coins ("total due" didn't update). A few hours later, my pool found another block, which after maturing did indeed share the rewards correctly.

Total Owned + Total Payed should be something close to Total Mined (not including maturing blocks), right? It's not in my pool... it seems that a few coins are in a "limbo".

Is there anything that I can do to "rescan" that block?
Or this is intended and I just don't understand PPLNS very well?

Thanks

**Comment by bobbieltd** [comment]
Stop using PPLNS as an excuse (it's wrong). PPLNS is over long time ago with your pool. I guess something crashed, you must relock the block that was not distributed. I don't have experience in this (never got this issue)

**Comment by bobbieltd** [comment]
Learn to use this https://github.com/Snipa22/nodejs-pool/blob/master/debug_scripts/block_locker.js and feedback me your experience. Be careful , you can overpay if you play dumb with that.

**Comment by bobbieltd** [comment]
Wait for a second ! Did you check Pool Wallet balance ? Precaution for orphan block.

**Comment by vitorgatti** [comment]
@bobbieltd do you know how to use block_locker.js?

something like that?
`node block_locker.js --blockHash=09shd0a9shdsa09dhas90dh`

**Comment by bobbieltd** [comment]
1. Backup mysql+pool_db
2. pm2 stop blockManager payments
3. node <path>\block_locker.js —blockID=“your undistributed block ID”
4. pm2 start blockManager and check log
5. Checking if balance table is updated correctly
6. If correct, pm2 start payments

**Comment by bobbieltd** [comment]
If the script run correctly, you’ll see log like this
"Block "+argv.blockID+" re-locked!  Exiting!"
