### ISSUE TITLE
SUMO Pool Daemon issues

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#331]
Not a happy pool at the moment, been running for nearly 4 days.  I had to use "make release-static" to compile sumokoin, as it would fail otherwise.

sumokoind is taking up most of the CPU, and I have 4 cores assigned to the machine.  Been working for last 3 days, but today the pool stopped updating Network Stats.

longRunner is throwing the following errors:

7|longRunn | 2018-02-22 22:22 +00:00: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":19734}
7|longRunn | 2018-02-22 22:31 +00:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":19734}
7|longRunn | 2018-02-22 22:35 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
7|longRunn | 2018-02-22 22:39 +00:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":19734}
7|longRunn | 2018-02-22 22:44 +00:00: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
7|longRunn | 2018-02-22 22:57 +00:00: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":19734}

I have 3 other pools, built very similarly, for different coins, and they are running fine.
I guess the connect errors are related to CPU being busy.

Any suggestions?

**Comment by BKdilse** [comment]
follow up...  I've restarted longRunner, and it now seems happy.  Looks like I had to wait for Daemon to catch up with its tasks, before starting longRunner.

Still an issue as to why Daemon needs so much more time to get ready, and why is it eating my 4 cores.  I have tried the switch to limit it to 1 thread, but it did not help.

**Comment by bobbieltd** [comment]
You already posted at Sumokoin repo. Wait for them to repond. I think their source code have problem. The make doesn’t work (I used make release-static like you but it’s weird). I still don’t have time to test my pool. I think it’s sumokoin’s side, not nodejs-pool issue.

**Comment by BKdilse** [comment]
I think so too, I'll close this, and see what the outcome on the daemon is.
