### ISSUE TITLE
Reward For Pool Setup Help

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#332]
I hope this doesn't get removed....
I would like to learn how to troubleshoot the pool setup.  So, if it is possible, the one who helps me the most to get my pool running can be my transaction fee wallet.

Thank you,

**Comment by vitorgatti** [comment]
Post your questions and people will try to help.

But if you're totally lost (almost zero Linux knowledge), then, my personal opinion: don't waste your time opening a pool, it will give you more headaches than anything else :P

**Comment by bobbieltd** [comment]
This is funny ( I prefer “scam” word ) post. Who believes in transaction fee wallet to get reward is naive or idiot. Anyway, you can ask for helps for “free”.
I won’t help you because I don’t your pool won’t survive (besides easy setup things, there are a lot stuffs you need to deal when running it)

**Comment by snoski3** [comment]
I would like this pool running sooner than later, that is why I made this post. If there are debug logs, no one has mentioned the location. 
I started with a centOS pool and I got stuck at the same place I am now that I'm running an Ubuntu pool. 
My goal is to support monero miners and if I make money, that is a bonus.

**Comment by bobbieltd** [comment]
@vitorgatti  Do you have Discord ? I'd like to add you
@snoski3 Show me your hashing power ( > 1 MH/s for XMR, > 100 KH/s for other coins). I'll help you to have a pool (whatever linux, whatever mysql, whatever problem, I can debug them).

**Comment by vitorgatti** [comment]
Make sure that you are running Ubuntu 16.04 x86_64. You can't use an older or newer version, it's not guaranteed it will work. Your first mistake was trying to install the pool in CentOS (redhad-based). Packages and commands are sometimes very different from Ubuntu (debian-based).

The main page of this project has an extended tutorial on how to setup the pool.

You have to tell us where you got stuck.

**Comment by vitorgatti** [comment]
@bobbieltd I do :) search for `shigutso`

**Comment by bobbieltd** [comment]
@vitorgatti Obrigado

**Comment by TimeTravelersHackedMe** [comment]
@snoski3 I'll set up your pool for 2XMR donated to a charity

**Comment by snoski3** [comment]
@vitorgatti
I setup SQL logging and found out that the admin login page doesn't attempt to authenticate to the SQL server. When I get a change, I'm going to change the bound IP address to 0.0.0.0

@timetravelershackedme
After I make that change and it still doesn't help, we can talk. I only have 1 xmr, plus I want to learn so I can pay it forward. Even if it takes two minutes, it will be worth the price.

**Comment by snoski3** [comment]
@vitorgatti 
I made the adjustment and bound the IP to 0.0.0.0 and the UI still doesn't attempt to connect to the MySQL server.

@TimeTravelersHackedMe 
Please let me know if 1 XMR is acceptable.

Thanks,

**Comment by cryptocrushers** [comment]
@snoski3 
I am interested in helping you set your own mining pool, I have already set several mining pools using opensource poolui and nodejs backend. the price is negotiable.if you are interested hit me up at Cryptocrusher@freenode.

**Comment by ArqTras** [comment]
@snoski3 PM me support@supportaeon.com or join discord
https://discordapp.com/invite/vGeRWQF

Installation for free

**Comment by snoski3** [comment]
@ArqTras 
Thank you for your help!
If anyone wants to get their pool up and running, here is what you do.
Go to vultr.com and but the 100 GB package under the shared plan, it is $40 USD per month.
Run the bash script and update the config files as needed.
Schedule an appointment with ArqTras and he will finish the setup.
ArqTras too about 45 minutes to get my pool up and running.

If I would had dinner that first, that would have saved me over 4 weeks of trying to get the pool running on my own.

**Comment by ArqTras** [comment]
@snoski3 close this thread;)
