### ISSUE TITLE
Announcement: NodeJS Pool developer community

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [Snipa22/nodejs-pool#336]
** Docker configs (MariaDB, Aeon, Monero, Stripped Down NodeJS Pool) docker-compose file
** nginx front end proxy configs, websockets examples, cryptonoter example, html5 boilerplate tweaks
** New Ionic 3/Angular 5 front end (and admin) demo: https://monero.gives
** Firebase Sync service that streams data through Firebase websockets (Used by Monero Gives front end)

Test servers available upon request.

Join the dev channel:
https://gitlab.com/NodeJS-Pool-Dev-Channel

**Comment by Snipa22** [comment]
Given that Github works perfectly fine for tracking of issues, I'm closing this as there's no need for a community.  If you want to discuss the development of features, there's always IRC if you want something faster than the asynchronous nature of GH issues.
