### ISSUE TITLE
pm2 restart api not found

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#338]
From a fresh install I run the command in step 5.
pooldaemon@host:~$ pm2 restart api
Use --update-env to update environment variables
[PM2][ERROR] Process api not found

**Comment by vitorgatti** [comment]
```
cd ~/nodejs-pool
pm2 start init.js --name=api --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=api

pm2 restart api
```

**Comment by snoski3** [comment]
@vitorgatti 
Thanks, that worked.
Starting /home/pooldaemon/nodejs-pool/init.js in fork_mode (1 instance)
[PM2] Done.

**Comment by vitorgatti** [comment]
I think you're having the same issue I had.
Your deploy.bash script is hanging after line 87
`pm2 install pm2-logrotate &`

Change it to this:
`pm2 install pm2-logrotate`
(without the & character)
Start a new server and run the deploy script with that line altered

I think you'll be able to finally check your pool working :)

**Comment by snoski3** [comment]
@vitorgatti
So, I would copy the script, edit the file, then run it locally after I start from scratch?

Thanks.

**Comment by vitorgatti** [comment]
yes, manually download the deploy.bash file, remove the & from line 87 and run it manually without the curl command, just `bash deploy.bash`

**Comment by snoski3** [comment]
That worked.
