### ISSUE TITLE
Shares and Hashes

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#341]
I've seen an instance were 2 miners have similar amount of shares showing in the dashboard, but miner1 of them has sent over double the amount of hashes than the miner2.  Why would the shares be pretty much the same?

The only thing I can think off is that miner2 has hopped in before difficulty dropped.

Can someone explain what is going on here please?

**Comment by Snipa22** [comment]
The pool aims to "configure" your miners to submit a share every 30 seconds.  It does this by adjusting the difficulty of each share. Difficulty is the expected number of hashes required to find a particular share.

If miner 1 has 1 kh/s, and miner 2 has 2 kh/s, the system will try setting 30k diff, and 60k diff, making each share that miner 2 submits, twice as valuable, even if they're coming in at the same rate.

**Comment by BKdilse** [comment]
Thanks. That makes sense.

**Comment by BKdilse** [comment]
Sorry, 1 last question...  If the Shares are the same, doesn't that mean, that the Hashes and Shares are used together to work out the pending payment?

**Comment by Snipa22** [comment]
Work completed is determined as the summed value of all shares active within the N range of the PPLNS search.  N is a multipler against the block difficulty.

Assume that you're looking for 180k hashes, and miner 2 submitted 2 at 60k, and miner 1 submitted 2 at 30k.  Miner 2 is performing twice as much work as miner 1, and receives twice the reward.

Shares are "collections" of hashes, hashes are the basis of the payment systems, not shares.

**Comment by BKdilse** [comment]
Thanks a lot, makes complete sense now.

**Comment by bobbieltd** [comment]
Let me guess. He still doesn’t understand shares vs hashes. Misunderstanding comes from the “famous” admin page which makes people using shares and hashes as the same definition.

**Comment by BKdilse** [comment]
Shares are "collections" of hashes - makes sense.  That's all I needed to know.
