### ISSUE TITLE
Bytecoin Support

### ISSUE THREAD

**Issue by sevendoorknobs** [Snipa22/nodejs-pool#348]
I am attempting to fix  Bytecoin support and I have most of it working, but when a miner connects I am getting a "Failed to parse block" error. I assume this has something to do with Cryptonote Utils, but I cannot seem to figure out a solution. Any ideas?

**Comment by Bathmat** [comment]
Yes, it is a Utils issue. Bytecoin should work with my Forknote version of the pool; however, I haven't tested Bytecoin specifically. https://github.com/Bathmat/nodejs-pool-forknote

**Comment by BKdilse** [comment]
@Bathmat with your version, can I use the original coin source or do I have to use the forknote source with coin config files?

I'm having issues with XLC coin.

**Comment by Bathmat** [comment]
For XLC, originally it was working with cryptonote utils, but they did a few changes, so now I think it works with forknote utils. Looks like I need to change that in my fork.

BTW, we shouldn't be clobbering Snipa's repo with this stuff. Feel free to post in my repo.

**Comment by BKdilse** [comment]
I couldn't find the issues option on your repo.  Hence posted here.  I agree, need to keep separate.

**Comment by Bathmat** [comment]
@BKdilse oops, I opened the issues now.
