### ISSUE TITLE
App and build directories look like duplicate

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#351]
I am trying to update the welcome.html file, the file says it is located in apps but I edit the welcome.html file but it doesn't get changed on the live site.  Then I found the same data in the build folder but changing the welcome.html file there didn't help either.

Thanks,

**Comment by BKdilse** [comment]
I've seen this too.  Not sure if it's intentional, but they are installed to the build folder, where you have to make your changes for it to work.

**Comment by BKdilse** [comment]
This is actually a Pool UI issue, so should be closed, and raised with the Pool UI owner

**Comment by snoski3** [comment]
Ok, thanks.
