### ISSUE TITLE
pool show miner connetced but miner show connection refunse startusm connection fail 

### ISSUE THREAD

**Issue by bapparabi** [Snipa22/nodejs-pool#36]
si pool is working ..

miner show connection refuse .. on all port defauly one :- http://prntscr.com/ebmn42

but when i see the pm2 log pool all it show that miner connacted .

############################
[STREAMING] Now streaming realtime logs for [pool] process
7|pool     | 2017-02-21 16:43 +00:00: (Worker 1 - 29846) New block to mine at height: 1251096.  Difficulty: 7034771035
7|pool     | (Master) New block to mine at height: 1251096.  Difficulty: 7034771035
7|pool     | 2017-02-21 16:44 +00:00: (Master) New block to mine at height: 1251097.  Difficulty: 7004000692
7|pool     | 2017-02-21 16:44 +00:00: (Worker 1 - 29846) New block to mine at height: 1251097.  Difficulty: 7004000692

##########################################

alos the front page don't show the miner is connected nor the status of the miner connected ..

i have test the port and all listening not blocking ..

what can be the iisue ??

you have any idea

**Comment by Snipa22** [comment]
This is on your side, and you'll need to debug it further.  You may wish to verify your bind_ip setting to ensure it's the external IP of your server, and not 127.0.0.1
