### ISSUE TITLE
Pool - Invalid Module Provided

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#360]
I ran pm2 monit:
![image](https://user-images.githubusercontent.com/5173575/37261574-b5c2405e-256b-11e8-9c5b-f973a400806f.png)

I didn't have this issue yesterday.  Also, yesterday I ran pm2 restart all -update-all, I saw a list of modules that were restarting, now....
![image](https://user-images.githubusercontent.com/5173575/37261614-f2346bca-256b-11e8-8213-01ac89a983ae.png)

**Comment by snoski3** [comment]
Now I just ran pm2 restart all:
![image](https://user-images.githubusercontent.com/5173575/37261670-4d3a8b08-256c-11e8-9ca6-2921110c1be1.png)

pm2 monit:
![image](https://user-images.githubusercontent.com/5173575/37261698-7710b39e-256c-11e8-978a-65d4ec6f6611.png)

**Comment by vitorgatti** [comment]
why are you running **two** monero-wallet-rpc modules?

**Comment by bobbieltd** [comment]
Nice trick. Two monero wallet = double earning 😂.
cd ~/nodejs-pool
pm2 delete pool
pm2 start init.js --name=pool --log-date-format="YYYY-MM-DD HH:mm Z" -- --module=pool

Congratulation ! Got your pool ! Let’s become millionaire ! For double wallet, if you can hack the transfers, keep me update ! Love that idea !

**Comment by snoski3** [comment]
@vitorgatti 
The first wallet was miss-configured.

@bobbieltd 
Thanks, that worked!
