### ISSUE TITLE
Miner: connection refused

### ISSUE THREAD

**Issue by snoski3** [Snipa22/nodejs-pool#364]
Now I'm ready to connect miners to my pool, however, when I connect, the error I get is connection refused.  I'm guessing I'm missing something.
Even though the ports are listed in the ports page of the webUI, I'm guessing they are still not open?
How can I enable those ports?

Thanks,

**Comment by bobbieltd** [comment]
Frankly, you are very stubborn. It’s good. Try to turn off all firewalls if there are any between your miners and your pool.

**Comment by kronoscrasher** [comment]
in nodejs-pool/config.json

try 

"bind_ip": "0.0.0.0",

**Comment by snoski3** [comment]
Well.... I got it to work.  The firewall was off and I was able to check which ports were listening.
