### ISSUE TITLE
Block_Locker.js is throwing "You specified keyIsUint32 on the Dbi, so you can't use other key types with it."

### ISSUE THREAD

**Issue by sevendoorknobs** [Snipa22/nodejs-pool#368]
I know he has effected longrunner in the past, trying to fix missing shares on my pool

**Comment by bobbieltd** [comment]
You can use the tweak parseInt(...) to fix, so I guess it’s a bug of LMDB/nodejs.

**Comment by bobbieltd** [comment]
Or you can downgrade nodejs back to 6.9.2 to avoid it.

**Comment by sevendoorknobs** [comment]
Yeah I tried doing so but then it was a new issue, I will continue messing with it and submit a fix when it's complete. Thanks Bobbie.

**Comment by sevendoorknobs** [comment]
Well, fixed the debug script but it didn't update payments, unfortunately.

**Comment by sevendoorknobs** [comment]
Fixed and submitted pull request.
