### ISSUE TITLE
Random invalid output bug - duplicated job method

### ISSUE THREAD

**Issue by fireice-uk** [Snipa22/nodejs-pool#37]
Some of the guys mining on supportxmr.com reported crashes in my miner when we switched to the new pool. After some debugging we managed to find the invalid input that was causing the crashes. I fixed the bug on my end, but as this is technically an invalid packet - the miner needs to drop the connection.
The problem seems to occur more (or even exclusively) on TLS connections. Here is the traffic log:

 ```
 RECV: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}                                                                  
 SEND: {"method":"submit","params":{"id":"93fe7f07-ddc8-4af3-9341-2b69cc59f22e","job_id":"a21aab8e-6e2e-4a32-9d29-3c6d0e1c966d","nonce"
 "7d5a8001","result":"318458d54450f1592c485f07b2e2e7190f2e7a99c3f7a7dcca7ef3cadd6f0000"},"id":1}                                      
                                                                                                                                       
 RECV: {"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}                                                                  
 RECV: {"jsonrpc":"2.0","method":"job","params":{"blob":"0405c3c6b3c50581207363a1ef64b66befca420896fa51b7730090c84b244f6ae2ed4ce6e15424
 00000002919ec5db724833da0c7b406d61d37c3db84e36fae57162810612b01878d710b06","job_id":"ecc106ad-3780-4285-a6f6-729ab7e28198","target":""
 aaa0200"}}                                                                                                                            
 RECV: {"jsonrpc":"2.0","method":"job","params":{"blob":"","job_id":"","target":""}}                                                  
 [1]    2154 floating point exception (core dumped)  ./xmr-stak-cpu.debug config-1.txt        
```

Good luck in finding that bastard! It seems to occur roughly every 240 hrs of runtime (once a day with 10 miners)

**Comment by Snipa22** [comment]
Interesting, this would explain why the claymore guys have been running into issues.  Interestingly, we use the same exact methods for SSL in general, unless SSL is eating things alive, I'll have to dig in a bit more.

I know that the blank blob, job_id, and target are done when the lastBlockHeight and the activeBlockTemplate.height are the same, and there's no new difficulty, as there's no new job to hand out.  Quick fix would be to disable that, and let the miner get new jobs more readily, which is fine in my books, but matches old pool impl, so either it's something new that's seriously breaking TLS based connections, which is odd, or the old miners opted to ignore it.
