### ISSUE TITLE
Need Snipa22's Wallet Address

### ISSUE THREAD

**Issue by sevendoorknobs** [Snipa22/nodejs-pool#371]
Reaching out to Snipa to see if he has a wallet address for Bytecoin that I can add prior to releasing it.

**Comment by Venthos** [comment]
Obviously I can't speak for Snipa22, but I don't think anyone would fault you for setting the poolDevAddress to your own if you generated and tested the relevant lib/coins/ and lib/payments_systems/ files for Bytecoin.

If I were to hazard a guess, Snipa22 likely doesn't have nor want to have a wallet for every possible mineable crypto.  You could always show your thanks by exchanging a portion of your profits in a given coin to BTC/AEON/XMR (which he has publicly posted donation addresses for) and sending your thanks that way.

**Comment by sevendoorknobs** [comment]
I have set up a separate wallet, at least for now. Then I can send the wallet his way of he decides he wants it.

**Comment by bobbieltd** [comment]
Like Venthos said, you can put your addresses to Dev/Pool addresses. It looks bad but most people put 0 at donations.
