### ISSUE TITLE
Errors connecting to daemon after upgrade to v0.12

### ISSUE THREAD

**Issue by 78bash** [Snipa22/nodejs-pool#379]
I get `{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18081}`
in my logs after upgrading the monero daemon to v0.12.

I pulled the new version, added the patch, compiled, restarted the service and my logs look like a psychadelic rainbow now. (note: I manually made the patch correctly to tx_pool.cpp)

Can someone say what I should do now?

**Comment by 78bash** [comment]
Ok, the daemon is running properly now but the monero-wallet-rpc server won't bind to :18082 'cause the daemon is on it. I'm out of ideas on how to resolve this. Anyone?

**Comment by vitorgatti** [comment]
it seems that the port 18082 is already being already being used by **monerod**

your wallet-rpc will have to use another port, try 18083 and update your pool.config table in mysql to connect to the new port

**Comment by 78bash** [comment]
Looks like that worked. Thanks for the help @vitorgatti
