### ISSUE TITLE
pool id already in use 

### ISSUE THREAD

**Issue by bapparabi** [Snipa22/nodejs-pool#38]
6|pool     | 2017-02-22 02:27 +00:00: Master cluster setting up 1 workers...
6|pool     | 2017-02-22 02:27 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
6|pool     | 2017-02-22 02:27 +00:00: Pool ID in use already for a different IP.  Update MySQL or change pool ID.
6|pool     | 2017-02-22 02:28 +00:00: Master cluster setting up 1 workers...
6|pool     | 2017-02-22 02:28 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
6|pool     | 2017-02-22 02:28 +00:00: Pool ID in use already for a different IP.  Update MySQL or change pool ID.
6|pool     | 2017-02-22 02:28 +00:00: Master cluster setting up 1 workers...
6|pool     | 2017-02-22 02:28 +00:00: Did not send e-mail successfully!  Response: undefined Response: undefined
6|pool     | 2017-02-22 02:28 +00:00: Pool ID in use already for a different IP.  Update MySQL or change pool ID.

i tryt o find pool id in mysql but don't able to see ..do yo know what this iisue is and how to solve it

**Comment by Snipa22** [comment]
The pool_id is used in the pools table, under the ID column.
