### ISSUE TITLE
items in queue keeps increasing

### ISSUE THREAD

**Issue by bruceleeon** [Snipa22/nodejs-pool#383]
7|pool     | 2018-04-05 18:17 -04:00: (Master) Queue debug state: 0 items in the queue 21 items being processed

This increases to the point of 96, then 0 items starts incrementing.

7|pool     | 2018-04-05 18:51 -04:00: (Master) Queue debug state: 507 items in the queue 96 items being processed

no clue!

**Comment by bruceleeon** [comment]
Environment Info
  Map address: (nil)
  Map size: 25769803776
  Page size: 4096
  Max pages: 6291456
  Number of pages used: 2627
  Last transaction ID: 231809
  Max readers: 512
  Number of readers used: 3
Reader Table Status
(no active readers)
Freelist Status
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 23
  Free pages: 254
Status of Main DB
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 3
Status of blocks
  Tree depth: 0
  Branch pages: 0
  Leaf pages: 0
  Overflow pages: 0
  Entries: 0
Status of cache
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 16
  Overflow pages: 223
  Entries: 53
Status of shares
  Tree depth: 2
  Branch pages: 1
  Leaf pages: 233
  Overflow pages: 0
  Entries: 28029

**Comment by camthegeek** [comment]
Check remoteShare module is running.

Check SQL  to ensure shareHost is set. It is typically http://127.0.0.1/leafApi

**Comment by bruceleeon** [comment]
Cannot GET /leafApi

**Comment by bruceleeon** [comment]
HOLY CRAPOLA!!! @camthegeek, thank you for leading me down that path. It seems caddy & the poolui weren't on the same page. I changed sharedhost to http instead of https (even though caddy has sitename.com instead of :80 so https works), and now it started updating again!!! Thank you!!!!!
