### ISSUE TITLE
Error: MDB_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by jredwine2857** [Snipa22/nodejs-pool#386]
Seeing this quite a bit in my worker logs.   Anyone have any ideas?  I'm assuming this is LMDB, but the free pages look good.

Restarted the entire server and I'm still seeing it in the logs.  

Anyone else seeing this since the fork?  (Could be totally unrelated to that)

**Comment by snoski3** [comment]
@jredwine2857 
Please post a few lines of the errors in the log.

**Comment by jredwine2857** [comment]
This is what I'm seeing in the worker logs continuously.



 Error: MDB_MAP_FULL: Environment mapsize limit reached
    at Error (native)
    at Database.bulkSetCache (/home/ubuntu/nodejs-pool/lib/local_comms.js:514:21)
    at /home/ubuntu/nodejs-pool/lib/worker.js:246:33
    at /home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:840:16
    at /home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:2938:18
    at apply (/home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:21:25)
    at /home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:56:12
    at /home/ubuntu/nodejs-pool/lib/worker.js:126:24
    at /home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:2937:44
    at apply (/home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:21:25)
    at /home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:56:12
    at /home/ubuntu/nodejs-pool/lib/worker.js:126:24
    at /home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:2937:44
    at apply (/home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:21:25)
    at /home/ubuntu/nodejs-pool/node_modules/async/dist/async.js:56:12
    at /home/ubuntu/nodejs-pool/lib/worker.js:126:24

**Comment by jredwine2857** [comment]
Think I fixed it.  Looks like my LMDB in pool_db hit the 24GB limit.  I upped this limit in Local_comms.js in nodejs-pool/lib by changing the 24 to 48 (GB).  I've bolded the value I changed from 24 to 48.  

What I don't know is if this growth is normal.  LongRunner shows no errors so that seems to be working.  I'm guessing this is just par for the course as the pool grows.

Is my thinking correct here?

this.initEnv = function(){
        global.database.env = new this.lmdb.Env();
        global.database.env.open({
            path: global.config.db_storage_path,
            maxDbs: 10,
            mapSize: **48** * 1024 * 1024 * 1024,
            noSync: false,
            mapAsync: true,
            useWritemap: false,
            noMetaSync: true,
            maxReaders: 512
