### ISSUE TITLE
Payments module sending 1 miner payment first then the rest after

### ISSUE THREAD

**Issue by jredwine2857** [Snipa22/nodejs-pool#387]
I've seen this the last few times our pool has hit a block.  The payments module will show 32 miners are to be paid.  Then is will send payment to 1 miner.   Afterwards, it will pay 25 miners (I have my limit set to 25 payees per payment), and then, finally, the last 6 miners will get paid in 3rd, and final, payment.

Anyone seeing this?

**Comment by Snipa22** [comment]
The first miner is likely a payment ID enabled miner, and must be sent seperately.

**Comment by jredwine2857** [comment]
Ah, that makes sense and you are correct, it is.   Thanks, Snipa!
