### ISSUE TITLE
Nicehash "Error: Read timed out"

### ISSUE THREAD

**Issue by Invisys** [Snipa22/nodejs-pool#389]
Nicehash cant connect to pool with MoneroV7 protocol.

> Resolving pool host xmr.dark-mine.su... OK
> Establishing connection with proxy... OK
> Establishing connection with pool 144.76.106.131:8888... OK
> Sending mining.subscribe... OK
> Sending mining.authorize... OK
> Error: Read timed out

Miner software works correctly.

How to solve this?

**Comment by BKdilse** [comment]
I've got same issue, logged it with nicehash support and they gave a useful answer "enable it on your pool", A**holes.

Any ideas guys?

**Comment by jredwine2857** [comment]
Yeah, i had this issue too.  I tested my pool and it failed.  then I tested supportxmr.com and it failed too.

So then i just threw caution to the wind and bought some hash power and sent it.

Guess what??  it worked fine!  My guess is nicehash's testing process for v7 is what's broke, not the pool.

So, just go ahead and send the hash, it'll likely work. It did for me!

**Comment by BKdilse** [comment]
I thought that might be the case, so I was going to try that tonight, and completely forgot LOL

Thanks for the reminder, and test.  Time to send BTC !

**Comment by BKdilse** [comment]
Raised this on Twitter, their devs have now fixed the test.  Works now.

**Comment by bobbieltd** [comment]
NiceHash tested and confirmed. No more timeout. Nice job and very active. Thanks BKdilse.
