### ISSUE TITLE
Invalid module provided  -- init

### ISSUE THREAD

**Issue by bapparabi** [Snipa22/nodejs-pool#39]
the init log show this iisue what this issue is and how to solve it 

7|init     | Invalid module provided.  Please provide a valid module
7|init     | Invalid module provided.  Please provide a valid module
7|init     | Invalid module provided.  Please provide a valid module
7|init     | Invalid module provided.  Please provide a valid module
7|init     | Invalid module provided.  Please provide a valid module
7|init     | Invalid module provided.  Please provide a valid module

**Comment by Snipa22** [comment]
What module were you attempting to launch?  All the given commands work correctly.

**Comment by bapparabi** [comment]
yes all show live and just thsi 2 show error log and when it ryt to see the log i see this 

pooladmin@xmr:~$ pm2 list
┌──────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬────────────┬──────────┐
│ App name     │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem        │ watching │
├──────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼────────────┼──────────┤
│ api          │ 8  │ fork │ 10698 │ online │ 0       │ 11m    │ 0%  │ 38.9 MB    │ disabled │
│ blockManager │ 1  │ fork │ 748   │ online │ 0       │ 31m    │ 0%  │ 305.4 MB   │ disabled │
│ init         │ 7  │ fork │ 9013  │ online │ 1049    │ 1s     │ 50% │ 40.5 MB    │ disabled │
│ longRunner   │ 5  │ fork │ 947   │ online │ 0       │ 31m    │ 0%  │ 84.4 MB    │ disabled │
│ payments     │ 3  │ fork │ 819   │ online │ 0       │ 31m    │ 0%  │ 46.4 MB    │ disabled │
│ pool         │ 6  │ fork │ 9039  │ online │ 1069    │ 1s     │ 0%  │ 34.8 MB    │ disabled │
│ remoteShare  │ 4  │ fork │ 903   │ online │ 0       │ 31m    │ 0%  │ 38.9 MB    │ disabled │
│ worker       │ 2  │ fork │ 782   │ online │ 0       │ 31m    │ 0%  │ 47.3 MB    │ disabled │
└──────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴────────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┤
│ pm2-logrotate │ 2.2.0   │ N/A        │ online │ 0       │ 0%  │ 31.594 MB   │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┘
 Use `pm2 show <id|name>` to get more details about an app
pooladmin@xmr:~$

**Comment by Snipa22** [comment]
│ init │ 7 │ fork │ 9013 │ online │ 1049 │ 1s │ 50% │ 40.5 MB │ disabled │

Is certainly incorrect, and is mis-launched.  All modules have proper names, and not init.  Please recreate all of your projects at this point in time in pm2.

I suggest digging into: http://pm2.keymetrics.io/docs/usage/quick-start/ heavily for detail.
