### ISSUE TITLE
Turtlecoin Lite CN1 pool not accepting miners

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#390]
I know this is not a issue with this repo, but I didn't know where else to log it.

I've spent the whole morning trying to sort this out, but not getting far.  Please advise if you know what I'm doing wrong. @bobbieltd I think you have a working pool, any advise please?

I have tried both hashing packages:
**github.com/MoneroOcean/node-cryptonight-hashing.git**
(with const cnHashing = require('cryptonight-hashing'); in coin file)
**github.com/turtlecoin/node-multi-hashing-node8.git**
(with const multiHashing = require("cryptonight-hashing"); in coin file)

Along with the changes in the coin file:
**this.cryptoNight = function(convertedBlob) {
    let cn_variant = convertedBlob[0] >= 4 ? 1 : 0;
    return cnHashing.cryptonight_light(convertedBlob, cn_variant);
};**

and:     return multiHashing.cryptonight-lite(convertedBlob, cn_variant);
 

Pool log shows "Error: channel closed.
XMrig shows: connect error.

**Comment by bobbieltd** [comment]
Ouff, sorry, I’m selfish and I don’t share my techniques 😂. There is another who made it work too —> @Bathmat

**Comment by Bathmat** [comment]
package.json: 

```
    "cryptonote-util": "git://github.com/turtlecoin/node-cryptonote-util.git",
    "multi-hashing": "git://github.com/turtlecoin/node-multi-hashing-node8.git"
```

`/lib/coins/trtl.js` (line 157? could be different):

`this.cryptoNightLite = multiHashing['cryptonight-lite'];`

pool.js line 617:

`hash = global.coinFuncs.cryptoNightLite(convertedBlob, 1);`

Tips appreciated, lol: `TRTLv2tC4aWcxKwZPanUndCmAYsp2xpnBW9Lo8ebZathjGVdUpXaeLWAfBzrf2kU5HHceNVMSYsGu7SMDsekSScTGnTUEeJw1h6`

**Comment by bobbieltd** [comment]
@Bathmat You are great (more generous than me in helping others). From my watch, your pool is better than mine (less forking, less lost of sync) but I don’t understand why miners don’t stay with your pool.

**Comment by BKdilse** [comment]
@Bathmat Unfortunately still getting issues.  Pool Error log shows **Error: Failed to parse block**

I'm sure i've done it right.  Any clues?

**Comment by Bathmat** [comment]
@BKdilse That would be an issue with the `cryptonote-util`. Try updating your package.json to the ones I listed above, then `npm install` and/or `npm rebuild`.

**Comment by BKdilse** [comment]
@Bathmat Found it:  Changed const cnUtil = require('forknote-util'); to const cnUtil = require('cryptonote-util');

Will send you a little something for appreciation :)
