### ISSUE TITLE
PM2 log clean up

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#394]
I can see large amounts of archive logs building up in the ~/.pm2/logs directory.

Does anyone know if these should be getting cleared out automatically, so is it best practice to write a script to do it?

**Comment by vitorgatti** [comment]
My pool is 3 months old and that folder has 6GB.
You can clean it by removing old files with a script.

**Comment by BKdilse** [comment]
I just found a way in PM2, to remove 30 day old ones:

`pm2 set pm2-logrotate:retain 30`

Doesn't apply to existing ones.  One of my pools had 20GB !!!
