### ISSUE TITLE
XMR Pool Total Due not updated after Block Matures

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#397]
I can't see any errors in the logs.

Pool found a block, which has matured.  Total Due has not updated.

Any ideas on what might be causing this?

**Comment by bobbieltd** [comment]
Check blockManager, there should be payout log on PPLNS. If not, blockManager was hang or stuck, try restart it.

**Comment by BKdilse** [comment]
Already tried restarting all modules, still don't see errors, checking individual logs now.

**Comment by bobbieltd** [comment]
You should post that log line PPLNS payout here. So vague to know the osue.

**Comment by bobbieltd** [comment]
If blockManager run correctly (no error, no mysql error), balance should be updated with rewards.

**Comment by BKdilse** [comment]
blockMan | 2018-04-17 10:05 +00:00: Performing PPLNS payout on block: 1552999 Block Value: 4.797958834032

**Comment by BKdilse** [comment]
Mysql error.log is showing:

[Note] Aborted connection 3 to db: 'pool' user: 'pool' host: 'localhost' (Got an error reading communication packets)

**Comment by bobbieltd** [comment]
So it’s mysql error that caused your problem. Try to increase max_connections.

**Comment by BKdilse** [comment]
@bobbieltd Thanks for that.

Just increased max_connections to 1000, and error is gone.

Restarted all modules apart from payments.  No change in Total Due or Balance table.  Should I now re-attempt the block_locker ?

**Comment by bobbieltd** [comment]
Re lock that block. Nothing to worry. Stop the payments in advance.

**Comment by BKdilse** [comment]
spoke too soon, as soon as I try re-lock, start blockmanager, I see the sql error again.

Now increased to 3000, and still the same connection error.

**Comment by bobbieltd** [comment]
Nothing to worry.
GRANT ALL ON pool.* TO pool@`127.0.0.1` IDENTIFIED BY 'yourpass';
GRANT ALL ON pool.* TO pool@localhost IDENTIFIED BY 'yourpass';
Check pass in config.json
Stop payments + relock block + rerun blockManager

**Comment by bobbieltd** [comment]
Try also 
#sudo systemctl restart mysql

**Comment by bobbieltd** [comment]
Got it now , you have to increase max_allowed_packet (double or triple the default value)
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_max_allowed_packet

**Comment by BKdilse** [comment]
I've just increased max_connections to 10,000 as a test, and it worked ok.  Balance table now updated, and looks correct.  I will start payments later on.

I'll have to look into what the appropriate value for max_connections should be.

**Comment by BKdilse** [comment]
I did see some bad shares from nicehash.  And my job is showing rejects, so that must have been it.

I'll close this now.  Thanks for your help.

**Comment by BKdilse** [comment]
Still got aborted connection errors is sql log.
Also, payout has occurred and I can't see updates to tables such as payments, transactions.  Balance table still shows payments due.

Bit of a mess.

**Comment by BKdilse** [comment]
@bobbieltd I've now increased max_connections and max_allowed_packet, which should hopefully be enough for future.

Do you know how I can get the information for the 2 payouts into the database?
1. Is it safe to deduct the balance that was paid to the 2 miners in the Balance table?
2. Is it safe to manually create the payments and transaction table entries?

Or is there a better way to sort this mess out?

**Comment by BKdilse** [comment]
There was a limit in Ubuntu which kept resetting the max connections, I've increased it.

I'll have a look at the table changes thanks.

**Comment by bobbieltd** [comment]
Because payments are made without updating on mysql. The only choice is to make up those transactions manually. I don’t think you have another way except you double pay (send 5 XMR from your personal wallet to pool wallet and try to repay 😂😂😂)

**Comment by bobbieltd** [comment]
There was a limit in Ubuntu which kept resetting the max connections —> Every time you restart mysql, all variables return to default. There is a conf file to make permanant changes (I haven’t done it)

**Comment by BKdilse** [comment]
Not doing double !!! lol

Yep, made conf change.

**Comment by BKdilse** [comment]
Got this working, with multiple changes in the end.  Increased max_connections to 5K and max_allowed_packet to 256MB, updated Daemon again, sent coins back to pool (safer option).

Closing now
