### ISSUE TITLE
worker module error, and get api /pool/ports return false

### ISSUE THREAD

**Issue by Ephzent** [Snipa22/nodejs-pool#404]
hi, i build a node-js pool, but worker module running error
detail:

> 2|worker   | 2018-04-27 06:39 -04:00: Block headers identical to historical header.  Ignoring
2|worker   | 2018-04-27 06:39 -04:00: Unhandled rejection TypeError: Cannot read property 'blockID' of undefined
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:392:77
2|worker   |     at Array.forEach (<anonymous>)
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:374:44
2|worker   |     at Array.forEach (<anonymous>)
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:354:14
2|worker   |     at tryCatcher (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
2|worker   |     at Promise._settlePromiseFromHandler (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
2|worker   |     at Promise._settlePromise (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
2|worker   |     at Promise._settlePromise0 (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
2|worker   |     at Promise._settlePromises (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
2|worker   |     at Async._drainQueue (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
2|worker   |     at Async._drainQueues (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
2|worker   |     at Immediate.Async.drainQueues (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
2|worker   |     at runCallback (timers.js:789:20)
2|worker   |     at tryOnImmediate (timers.js:751:5)
2|worker   |     at processImmediate [as _immediateCallback] (timers.js:722:5)
2|worker   | 2018-04-27 06:39 -04:00: Unhandled rejection TypeError: Cannot read property 'blockID' of undefined
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:392:77
2|worker   |     at Array.forEach (<anonymous>)
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:374:44
2|worker   |     at Array.forEach (<anonymous>)
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:354:14
2|worker   |     at tryCatcher (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
2|worker   |     at Promise._settlePromiseFromHandler (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
2|worker   |     at Promise._settlePromise (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
2|worker   |     at Promise._settlePromise0 (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
2|worker   |     at Promise._settlePromises (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
2|worker   |     at Async._drainQueue (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
2|worker   |     at Async._drainQueues (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
2|worker   |     at Immediate.Async.drainQueues (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
2|worker   |     at runCallback (timers.js:789:20)
2|worker   |     at tryOnImmediate (timers.js:751:5)
2|worker   |     at processImmediate [as _immediateCallback] (timers.js:722:5)
2|worker   | 2018-04-27 06:39 -04:00: Block headers identical to historical header.  Ignoring
2|worker   | 2018-04-27 06:39 -04:00: Unhandled rejection TypeError: Cannot read property 'blockID' of undefined
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:392:77
2|worker   |     at Array.forEach (<anonymous>)
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:374:44
2|worker   |     at Array.forEach (<anonymous>)
2|worker   |     at /home/nodepool/nodejs-pool/lib/worker.js:354:14
2|worker   |     at tryCatcher (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
2|worker   |     at Promise._settlePromiseFromHandler (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
2|worker   |     at Promise._settlePromise (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
2|worker   |     at Promise._settlePromise0 (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
2|worker   |     at Promise._settlePromises (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
2|worker   |     at Async._drainQueue (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
2|worker   |     at Async._drainQueues (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
2|worker   |     at Immediate.Async.drainQueues (/home/nodepool/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
2|worker   |     at runCallback (timers.js:789:20)
2|worker   |     at tryOnImmediate (timers.js:751:5)
2|worker   |     at processImmediate [as _immediateCallback] (timers.js:722:5)
and get api /pool/ports return false
detail:
https://noobxmr.com/api/pool/ports

> mysql>
 select * from pools;
+----+---------------+---------------------+--------+---------+---------------------+--------------------+
| id | ip            | last_checkin        | active | blockID | blockIDTime         | hostname           |
+----+---------------+---------------------+--------+---------+---------------------+--------------------+
|  0 | 0.0.0.0       | 2018-04-27 18:45:39 |      1 | 1560323 | 2018-04-27 10:45:40 | cnpool.noobxmr.com |
|  1 | 199.167.29.9  | 2018-04-27 06:45:38 |      1 | 1560323 | 2018-04-27 10:45:38 | uspool.noobxmr.com |
|  2 | 192.99.35.185 | 2018-04-27 06:45:39 |      1 | 1560323 | 2018-04-27 10:45:39 | capool.noobxmr.com |
+----+---------------+---------------------+--------+---------+---------------------+--------------------+
3 rows in set (0.00 sec)
mysql> select * from ports;
+---------+--------------+---------------+-----------+---------------------------------------+--------+---------------+---------------------+--------+----------+
| pool_id | network_port | starting_diff | port_type | description                           | hidden | ip_address    | lastSeen            | miners | ssl_port |
+---------+--------------+---------------+-----------+---------------------------------------+--------+---------------+---------------------+--------+----------+
|       2 |         5555 |          5000 | pplns     | Medium-Range Hardware (Up to 160 h/s) |      0 | 192.99.35.185 | 2018-04-27 10:46:29 |      2 |        0 |
|       2 |         3333 |          1000 | pplns     | Low-End Hardware (Up to 30-40 h/s)    |      0 | 192.99.35.185 | 2018-04-27 10:46:29 |      2 |        0 |
|       2 |         7777 |         10000 | pplns     | High-End Hardware (Anything else!)    |      0 | 192.99.35.185 | 2018-04-27 10:46:29 |      0 |        0 |
|       2 |         9000 |         20000 | pplns     | Claymore SSL                          |      0 | 192.99.35.185 | 2018-04-27 10:46:29 |      0 |        1 |
|       0 |         3333 |          1000 | pplns     | Low-End Hardware (Up to 30-40 h/s)    |      0 | 0.0.0.0       | 2018-04-27 10:46:30 |      0 |        0 |
|       0 |         5555 |          5000 | pplns     | Medium-Range Hardware (Up to 160 h/s) |      0 | 0.0.0.0       | 2018-04-27 10:46:30 |      0 |        0 |
|       0 |         7777 |         10000 | pplns     | High-End Hardware (Anything else!)    |      0 | 0.0.0.0       | 2018-04-27 10:46:30 |      0 |        0 |
|       0 |         9000 |         20000 | pplns     | Claymore SSL                          |      0 | 0.0.0.0       | 2018-04-27 10:46:30 |      0 |        1 |
|       1 |         5555 |          5000 | pplns     | Medium-Range Hardware (Up to 160 h/s) |      0 | 199.167.29.9  | 2018-04-27 10:46:28 |    188 |        0 |
|       1 |         3333 |          1000 | pplns     | Low-End Hardware (Up to 30-40 h/s)    |      0 | 199.167.29.9  | 2018-04-27 10:46:28 |      0 |        0 |
|       1 |         9000 |         20000 | pplns     | Claymore SSL                          |      0 | 199.167.29.9  | 2018-04-27 10:46:28 |      0 |        1 |
|       1 |         7777 |         10000 | pplns     | High-End Hardware (Anything else!)    |      0 | 199.167.29.9  | 2018-04-27 10:46:28 |      0 |        0 |
+---------+--------------+---------------+-----------+---------------------------------------+--------+---------------+---------------------+--------+----------+
12 rows in set (0.00 sec)

**Comment by bobbieltd** [comment]
It seems you are hasty. You should try a pool with one server before adding leaves. But looking at the pool, you are serious, I like that.
mysql should be open to outside. Remove the line bind 127.0.0.1 , you can put a firewall to protect mysql (only main server and leaves can access mysql).

**Comment by Ephzent** [comment]
hi, thank you reply
mysql is a single server and bind 0.0.0.0 firewall allow any pool server
this is my mindmap : https://www.processon.com/view/link/5ae30e70e4b090f6eeb8b3cc

**Comment by 78bash** [comment]
Are your blockchains fully synced?

**Comment by Ephzent** [comment]
@78bash 
yeah, is synced

**Comment by GustavoEdny** [comment]
I have same problem

**Comment by Ephzent** [comment]
@GustavoEdny 
@bobbieltd 
@78bash 
i think it's fixd
try add this parameter to mysqld config:

> skip-external-locking
key_buffer_size = 32M
max_allowed_packet = 1M
table_open_cache = 128
sort_buffer_size = 768K
net_buffer_length = 8K
read_buffer_size = 768K
read_rnd_buffer_size = 512K
myisam_sort_buffer_size = 8M
thread_cache_size = 16
query_cache_size = 16M
tmp_table_size = 32M
#skip-networking
max_connections = 500
max_connect_errors = 100
open_files_limit = 65535
