### ISSUE TITLE
Where can I find API for network hashrate?

### ISSUE THREAD

**Issue by LegolasGChief** [Snipa22/nodejs-pool#405]
/api/network/stats

No hashrate?

**Comment by Ephzent** [comment]
monerod is synced? or choice a remote node update in your config on: https://www.xmr.be/

**Comment by LegolasGChief** [comment]
@Ephzent Hello sorry :P pool is running find I was just wondering if there is API I can get the hashrate for the whole network on I thought would be able to get it  from http://127.0.0.1/api/network/stats
on server but cant find it :(

**Comment by LegolasGChief** [comment]
@Ephzent I have pool running here https://www.durinsmine.com
I am trying to get the hashrate from API like https://www.durinsmine.com/api/network/stats
But there is not network hashrate?

**Comment by LegolasGChief** [comment]
Thanks :)
