### ISSUE TITLE
Anything to worry about when changing pools wallet address?

### ISSUE THREAD

**Issue by Reptillian** [Snipa22/nodejs-pool#415]
My wallet seems to have been corrupted when updating through the Aeon rebase and I have to create a new wallet.

Have got pool running it seems.

I changed database wallet to new one then ran pm2 reload api --update-env

My modules seem to be using a lot of memory compared to before? have I done something wrong?

My longRunner is currently at 4.8GB memory usage but it doesnt show using htop?

Remoteshare + worker are also using 1GB+ memory each.

**Comment by bobbieltd** [comment]
1. Changing pool wallet fee —> restart all module (in fact, only two modules need to be restarted but restart all will be magic way when changing some essential things)
2. Memory usage of all modules (excluding daemon) > 2 Gb —> abnormal
3. Stoping using reload (0 down time = funny). Don’t hesitate to use pm2 restart.

**Comment by Reptillian** [comment]
Everything is fine now thanks for help!
