### ISSUE TITLE
supportxmr.com page broken

### ISSUE THREAD

**Issue by tkalfaoglu** [Snipa22/nodejs-pool#416]
the web site https://supportxmr.com/#/dashboard  does not properly load.
The only thing it displays is:
 powered by nodejs-pool & poolui
(mod by miziel)

**Comment by tkalfaoglu** [comment]
Thanks - I noticed that supportxmr.com and www.supportxmr.com show different web sites..

**Comment by TrueOsiris** [comment]
Still the webpage is not properly showing anything, besides the "powered by" line
