### ISSUE TITLE
aeon-rebase 0.12 released, steps to update AEON pool?

### ISSUE THREAD

**Issue by shigutso** [Snipa22/nodejs-pool#417]
AEON 0.12 "Sophia" has been released, changing how the daemon and the wallet works (also changing the PoW):
https://github.com/aeonix/aeon/releases
Its code is pretty much Monero's code now.

What are the steps to update an existing AEON pool using the old software? Many pool admins might have issues, so it would be nice to have a "quick step-by-step" on how to update your nodejs-pool from the old version.

This repo by @Snipa22 also needs updating I guess:
https://github.com/Snipa22/node-multi-hashing-aesni

Thanks!

**Comment by bobbieltd** [comment]
Extremely quick step-by-step guide : change coin from aeon to aeon-rebase, that is all. Fully tested with testnet, already in this repo.

**Comment by shigutso** [comment]
Just change `aeon` to `aeon-rebase` from the `config.json` file and do a `git pull`?
What about the nodejs modules that the deploy script downloads from another repo?

**Comment by bobbieltd** [comment]
Ouff, I thought you asked for fun.
1. git pull
2. npm install
3. nano config.json (change to “coin” : “aeon-rebase”
4. pm2 restart all

You can run on test server at first, but I think it’s unnecessary (any thing wrong, you can switch back aeon-rebase to “coin” : “aeon” and post your issue in this post). I believe it will be smooth.

**Comment by bobbieltd** [comment]
Be careful with step 2
If npm install doesn’t go well, stop doing anything further.
Google to npm install to insall all new utils.

**Comment by shigutso** [comment]
I guess that many pool admins can't code (myself included), can only troubleshoot, follow instructions and do some Linux sysadmin stuff, that's why I opened this issue, to make clearer for everyone that will have to upgrade their pools. As Snipa is kinda away from this repo, it would be nice if the community helped other pool admins to keep their stuff working :)

**Comment by bobbieltd** [comment]
As you said, I recommend you to rent one more VPS to practice and learn installing aeon-rebase from this repo.
Even if Snipa is here, he won't help you. His policy is that this repo is for Monero , not other coins (Aeon is not an exception). You are lucky that Snipa let aeon-rebase sneaked inside the repo.

**Comment by bobbieltd** [comment]
As I told you, “npm install” must be installed correctly. Your error means “git pull” without “npm install”.
You can use MoneroOcean for utils. Fork this repo, I’ll pull request change for you.

**Comment by aeon-team** [comment]
I have the same problem as shigutso on my AEON pool. Did a clean install on a new system. The problem is only when I configure 'aeon-rebase' coin in pool config. There are no problems if I use 'aeon' coin.

**Comment by aeon-team** [comment]
@bobbieltd I'v tested this option on Snipa's pool, and the problem is gone. Seems like all is working fine. Is it safe to leave it like this?

**Comment by bobbieltd** [comment]
Yes, it is safe to use now with Aeon rebase and it will autoswitch to new algo with Aeon 1st June fork.
For MoneroOcean cryptonight light variant 1 hashing, I tested it and it works.

**Comment by aeon-team** [comment]
@bobbieltd thanks a lot! I've found that this code from MoneroOcean was added to Snipa code https://github.com/Snipa22/nodejs-pool/commit/9c52de91edc558a8ea4e79bfde0bf7e90e1eff77, but was not sure if its enough and tested

**Comment by shigutso** [comment]
@bobbieltd yes I did a `npm install`, without errors.

So @Snipa22's code literally only works for the new PoW? That's crazy.
`Error: Argument 2 should be a boolean` means that the pool was trying to mine with v7 instead of v1 PoW?

Where exactly is MoneroOcean's module? Sorry but I didn't understand what I need to change
Is it this one? https://github.com/MoneroOcean/node-cryptonight-hashing

**Comment by bobbieltd** [comment]
In aeon-rebase.js (coins directory, line 4), replace
const multiHashing = require('multi-hashing');
to —> const multiHashing = require('cryptonight-hashing');

This repo (Snipa’s) uses MoneroOcean utils for XMR also. Snipa’s multi-hashing util is for old algorithm and not updated ( my mistake that I thought he updated it )

**Comment by camthegeek** [comment]
The aeon-rebase file was meant to use the standard node-multi-hashing-aesni that I had updated for variant support -> https://github.com/camthegeek/node-multi-hashing-aesni

Either package will work. One requires a change in aeon-rebase while the other doesn't.

**Comment by shigutso** [comment]
it worked, thanks everyone

**Comment by snoski3** [comment]
I just went through the steps.
after npm install, I was required to upgrade npm.  Then I ran npm install and received the following error:
added 2 packages from 4 contributors and audited 1067 packages in 7.625s
found 23 vulnerabilities (9 low, 13 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
I run: npm audit and I see a lot of "Prototype pollution" and " Regular Expression Denial of Service"
The summary report:
found 23 vulnerabilities (9 low, 13 moderate, 1 high) in 1058 scanned packages
  6 vulnerabilities require semver-major dependency updates.
  17 vulnerabilities require manual review. See the full report for details.

Any thoughts on how I can fix these errors?

Thanks,

**Comment by shigutso** [comment]
I just renamed my nodejs-pool to nodejs-pool_old and cloned the github again, restoring the config.json and the certificate file that is generated on snipa's deploy script. AFAIK, no other files are necessary, you can wipe your nodejs-pool folder.

**Comment by snoski3** [comment]
@shigutso 
I still got the same errors:
make: Leaving directory '/home/pooldaemon/nodejs-pool/node_modules/zmq/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
added 364 packages from 361 contributors and audited 1016 packages in 59.449s
found 46 vulnerabilities (20 low, 19 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details

How can I confirm which Monero version I'm running?

Thanks,
