### ISSUE TITLE
Leaf Node minimum hardware specs

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#418]
I couldn't find a list on minimum specs, i.e. Quad Core, 4GB RAM, 60GB SSD.  What is everyone running, and what's the bare minimum I can get away with?

**Comment by jbnl** [comment]
If you'll only build 1 pool then 2GB of ram should suffice. 1 core is sufficient as well. Disk space depends on the blockchain size really... good luck!

**Comment by BKdilse** [comment]
Thanks. I'll give it a go, and see how it performs.

**Comment by bobbieltd** [comment]
Leaf bare minimum is 1 Gb ( main pool minimum is 2Gb ). 1 core is enough because of small pool. I always prefer 2 vcores.

**Comment by BKdilse** [comment]
Yeah I'd go with 2 cores.  RAM is the issue, running low on my virtual servers, gotta get another server.

**Comment by bobbieltd** [comment]
More RAM = more buffer (a bit better) = Quick first sync = Quick GCC.
Hardware specs are not issues because with leaf, you can upscale the server easily when more miners come. Check RAM and CPU usages, if it runs high, upgrade the server. Simple.

**Comment by BKdilse** [comment]
Cool, I'll start one off soon
