### ISSUE TITLE
I am looking to change my pool over to this repo from another for Aeon what do I need to do?

### ISSUE THREAD

**Issue by Reptillian** [Snipa22/nodejs-pool#421]
I have aeon pool running on a repo that is no longer being updated. 
If I wanted to switch my pool to this repo what do I need to do?

rename old nodejs-pool file to backup and then git clone this repo?

I already have pool up and running so deployment is not much help :(

Are there any new entries in the database that I might be missing what is best way to check?

I am thinking that 
cloning repo to nodejs-pool
keeping old config file for old pool
npm install
npm update
then pm2 restart all?

**Comment by Reptillian** [comment]
I am using a different repo forked by someone else, I want to move it back to this?

**Comment by shigutso** [comment]
probably better to update to the new repo, but even this one isn't fully ready to work with AEON's rebase, you'll have to make one small change, as described on #417

**Comment by Reptillian** [comment]
For anyone that was wondering just change the name of nodejs-pool to backup or w/e then mkdir nodejs-pool; npm uninstall; then git clone repo etc
