### ISSUE TITLE
How to change the pool hashrate charts so they are not in decimal?

### ISSUE THREAD

**Issue by DurinsMine** [Snipa22/nodejs-pool#437]
I forgot how to update the pools UI so that the pools hashrate chart is not in decimal.
Anyone able to tell me what I need to change?

Thanks

**Comment by bobbieltd** [comment]
I don’t remember well but it is in utils/string.js 
.filter('toHashRate', function() {
  return function(hashes) {

**Comment by DurinsMine** [comment]
I think that is for the pool hashrate not chart?

I found it at the top of home.js 

        dataService.getData("/pool/chart/hashrate/pplns", function(data){
            data = _.forEach(data, function(element) {
                element.ts = new Date(element.ts);
		element.hs = element.hs/100;
            });
