### ISSUE TITLE
Round effort not right sometimes?

### ISSUE THREAD

**Issue by DurinsMine** [Snipa22/nodejs-pool#440]
Hello everyone, having a weird issue with block effort. Is it supposed to reset when I restart pool modules? As in, it stays the same on the UI but internally does it reset?

I have had some strange issues with my pool after switching to this repo from a different version for Aeon.
Should I have removed pool_db when changing repos and reset the pool?

**Comment by shigutso** [comment]
No, it does not reset when you restart pool modules, the shares sent are kept inside pool_db and it uses that to calculate the effort %

**Comment by DurinsMine** [comment]
Ah I am not sure if something is corrupt because it does not seem to be
working properly.

It is safe to just deleted pool db and start again?

**Comment by shigutso** [comment]
if you reset your pool_db to zero, all shares sent by miners will be deleted as well, if that's not an issue on your pool, then go for it!

**Comment by DurinsMine** [comment]
I see, I will make a backup first and try it after the next block has been
paid out

**Comment by BKdilse** [comment]
check out https://github.com/Snipa22/nodejs-pool/pull/73/commits/be4351401677e25bbcdf7af7e6a25059f202cd13

Should fix it

**Comment by DurinsMine** [comment]
It was a modification I made to one of files reverted it and fixed nothing to do with repo my bad xD
