### ISSUE TITLE
How do I Adjust Block Reward, detucting a Percentage

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#443]
I've had a look at the code, and cannot work out where I need to do this, so any advice would be much apreciated...

I am running a Bittube pool, and can see from their code where they have made the adjustment:

https://github.com/ipbc-dev/bittube-pool/commit/6dbc073880e5312dc982c01d0685190aa643f6e6

Any ideas where I need to make adjustents on my pool?

**Comment by bobbieltd** [comment]
Simple solution : add 0.03% to pool fee
Normal solution : in blockMaganer.js
feesToPay += Math.floor(amountToPay *0.03/100) 
before amountToPay -= feesToPay
Hard solution : check block major version to adjust version 4 and version 5 base reward fee. I can pull request the change for you if you have a fork of nodejs-pool repo.

**Comment by bobbieltd** [comment]
if (global.config.general.coinCode === “TUBE”) feesToPay += Math.floor(amountToPay *0.03/100);

You can do with blockHeader.reward -= blockHeader.reward*0.03/100;
I think your idea is more correct. I don’t understand why official bittube pool repo put base reward to pool fee. Anyway, bittube devs are not professional. Even official pool (and related bittube repo pools), I don’t understand how they get block reward which is different.

**Comment by BKdilse** [comment]
Agreed, the devs could have don it in a better way.  Would be better to build it into the code rather than adjusting it in pool code.

I'll have a play about and see how I go.  Will post results back once I'm done.

**Comment by BKdilse** [comment]
Implemented changes, awaiting next block.
