### ISSUE TITLE
Miner client-Xmrig.exe,encounter issue of 'Bad share or Low difficulty share',come on,help me,crying !!!

### ISSUE THREAD

**Issue by JokeAnything** [Snipa22/nodejs-pool#445]
Every pool moudue process running OK,xmrig miner connecting OK,but i met problem that from log or code,such as "Bad share from miner" ,"invalidShare","Low difficulty share",maybe miner client does not support node.js-pool or algorithm wrong,help,help,help,online waiting!!!

log below:
![xmrig_log](https://user-images.githubusercontent.com/41603511/43135500-37f83f94-8f78-11e8-9bd7-5b4eb5b5bc36.png)
![pool_error_log](https://user-images.githubusercontent.com/41603511/43135488-2be980aa-8f78-11e8-8c32-da3713725ee0.png)

**Comment by bobbieltd** [comment]
I guess blob version of other coins less than 7.
Edit lib/coins/xmr.js change
this.cryptoNight = function(convertedBlob) {
        return multiHashing.cryptonight(convertedBlob, convertedBlob[0] >= 7 ? convertedBlob[0] - 6 : 0);
    }

—> to —>
this.cryptoNight = function(convertedBlob) {
        return multiHashing.cryptonight(convertedBlob, 1);
    }

It will solve.
