### ISSUE TITLE
transaction is too big

### ISSUE THREAD

**Issue by Projek-Kripto** [Snipa22/nodejs-pool#447]
hi all, i got some error please help, small payment works great but when pool want to send payment due more then 5000 i got this error - Issue making payments{"code":-4,"message":"transaction is too big"}

**Comment by bobbieltd** [comment]
Ask coin devs

**Comment by Projek-Kripto** [comment]
@bobbieltd any other solution? i also use node-cryptonote-pool without any issue tho, thanks

**Comment by bobbieltd** [comment]
If node-cryptonote-pool works, nodejs-pool should works too. My guess : try to reduce mixin to see if it passes.

**Comment by Projek-Kripto** [comment]
@bobbieltd reduce mixin same error, i think i want to transfer manually but how to update the database?

**Comment by DurinsMine** [comment]
@Projek-Kripto connect using mysql workbench using root and password that was generated I think

**Comment by Projek-Kripto** [comment]
@DurinsMine i use phpmyadmin and manually send payment, thanks
