### ISSUE TITLE
Hostname change

### ISSUE THREAD

**Issue by BKdilse** [Snipa22/nodejs-pool#449]
I have changed the hostname for my pool.  Everything works fine, apart from the old hostname showing under Ports List > PPLNS > Server (still showing old hostname).

How do I get this to change?
I've had a look at SQL and UI files, as I can't any any bits that I forgot to change.

**Comment by bobbieltd** [comment]
Change hostname in pools table (MySQL)

**Comment by BKdilse** [comment]
I'll double check that, maybe I missed it.

**Comment by BKdilse** [comment]
@bobbieltd Yes, I am going blind, found it, thanks :)
