### ISSUE TITLE
admin page is not working

### ISSUE THREAD

**Issue by chaturanga50** [Snipa22/nodejs-pool#45]
as per the instructions,

`Hop into the web interface (Should be at http://<your server IP>/#/admin), then login with Administrator/Password123, MAKE SURE TO CHANGE THIS PASSWORD ONCE YOU LOGIN. <- This step is currently not active, we're waiting for the frontend to catch up! Head down to the Manual SQL Configuration to take a look at what needs to be done by hand for now.`

when we type our url, it's redirecting back to home page.

**Comment by Snipa22** [comment]
Per the very instructions you pasted:
This step is currently not active, we're waiting for the frontend to catch up! Head down to the Manual SQL Configuration to take a look at what needs to be done by hand for now.
