### ISSUE TITLE
Anyone have guide to setting up node? 

### ISSUE THREAD

**Issue by DurinsMine** [Snipa22/nodejs-pool#458]
https://github.com/Snipa22/nodejs-pool/issues/174

Link to arqtras wiki has been removed :(

**Comment by bobbieltd** [comment]
Great thanks to ArqTras :
1. Open mysql (0.0.0.0, no more 127.0.0.1) . Firewall as protection so only leaf can access.
2. host in mysql will point http://mainserverIP/leafApi
Run pool module on leaf.
Good luck 😉

**Comment by DurinsMine** [comment]
I got it to work I think :)
