### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by Chanakan5591** [Snipa22/nodejs-pool#469]
When I click LOGIN on the admin.html poolui page it gave me please check your login details. But I check the username and the password it was correct I try it a lot of times but it still not working. So I think maybe it related to database connection problem. I have change the mysql password manually om nodejs-pool/config.json file and on the MySQL itself. Will I have to edit another files else?

**Comment by shigutso** [comment]
The first user in pool.users is the admin, you have to use that username and password to login into admin.html, not the mysql credentials.

**Comment by Chanakan5591** [comment]
I have use Administrator for user and Password123 it didn't work

ในวันที่ อ. 26 มี.ค. 2019 18:50 น. shigutso <notifications@github.com>
เขียนว่า:
