### ISSUE TITLE
No payments and worker error

### ISSUE THREAD

**Issue by DannyGreen** [Snipa22/nodejs-pool#59]
I've been having an issue with miners being paid out from the rpc wallet. The install was ran from the bash script and followed the guide word for word. I've checked that the wallet has a value in it via a curl command and I have 1 miner awaiting a payout for 4 blocks. I've also checked all the logs and can confirm that the pool has a connection to the wallet. And I'm also getting an error on the worker log "GetLastBlockHeader Error during block header update". I've tried my best at debugging these issues but unfortunately haven't got anywhere.

**Comment by Snipa22** [comment]
The WorkerLog error is expected.  As for the RPC wallet, please make sure it's accepting the payments.  Or restart the Payment Daemon, and check for it spitting back the error it gets.
