### ISSUE TITLE
custom thresholds - users with exchange address

### ISSUE THREAD

**Issue by M5M400** [Snipa22/nodejs-pool#60]
It is possible for users with exchange addresses to set their threshold to a lower value than the one globally configured for exchange payouts. I didn't check if these are actually honored by the payment process (I hope not) but it would be nice to have the user notified when entering a threshold below allowed minimum.

**Comment by Snipa22** [comment]
Yes, this is permitted, they are limited lower-bounds wise to the same limit as wallet withdrawls.

**Comment by M5M400** [comment]
then this is not an issue, really. just a matter of opinions :)
