### ISSUE TITLE
what kind of coins does this support?

### ISSUE THREAD

**Issue by systemroot** [Snipa22/nodejs-pool#70]
Hello,

This is a project developed just for Monero, or it supports other coins?! 

if you support more than just Monero, can you please tell me which one are supported !?

Thanks.

**Comment by nibbons** [comment]
Yes, I too would like to know how to use this for other CryptoNote coins

**Comment by systemroot** [comment]
i'm closing this cause as i'm seeing no one wanna give those infos.

**Comment by Snipa22** [comment]
Sorry, I had responded to the GH e-mail.  At this time, no other coins are supported.  I'm reviewing the implementation for other CN based coins this weekend.

**Comment by d3ancole1995** [comment]
Any update to this? I'd like to get a pool up and running for byte coin but I can't get it working.
