### ISSUE TITLE
Running deploy.bash returns errors saying npm is not installed

### ISSUE THREAD

**Issue by 78bash** [Snipa22/nodejs-pool#71]
Even if I install npm through apt-get and then continue running the script there are npm installation errors returned.

**Comment by Snipa22** [comment]
Is this being installed in a bash environment or sh?  Last time we saw this, it was someone executing the scripts in a sh based shell, versus a bash shell.  NVM requires bash as it uses/abuses a large number of envvars.

**Comment by 78bash** [comment]
I'm installing this in a bash shell.

I haven't changed any defaults, chsh shows that I'm using /bin/bash, I'm installing it in Ubuntu server 16.04 as instructed.

**Comment by Snipa22** [comment]
Would you be able to hop on IRC?  It sounds like NPM isn't installing correctly, which is concerning.

**Comment by 78bash** [comment]
Sure, which channel?

**Comment by Snipa22** [comment]
#monero-pools on irc.freenode.net.  I'm on there as Snipa.  Say my name and I'll tab in.

**Comment by 78bash** [comment]
So it turns out this happens when installing on a machine locally, installing on a cloud server works great.
