### ISSUE TITLE
Apply Changes Made to global.js

### ISSUE THREAD

**Issue by newbienoobie** [Snipa22/nodejs-pool#78]
Hi everyone,

I just started trying to deploy nodejs-pool on my Ubuntu 16.04 DO server. After making changes to my pool name in `~/poolui/build/globals.js`, I cannot see the new changes on the webpage after refreshing the browser or after doing `service caddy restart`. It seems to only take effect if I reboot the server.

What is the correct way to apply the changes made to `global.js`?

**Comment by M5M400** [comment]
this seems to be frontend related, so it should be raised here https://github.com/mesh0000/poolui

that said, try editing the app.manifest in the docroot (just change a char of the checksum in the last line of the file)
