### ISSUE TITLE
Cannot read property 'blocktemplate_blob' of undefined

### ISSUE THREAD

**Issue by Klakloy** [Snipa22/nodejs-pool#89]
Pool log
2017-07-06 07:25 +00:00: TypeError: Cannot read property 'blocktemplate_blob' of undefined
at /home/foo/nodejs-pool/lib/pool.js:161:48
 
ubuntu server 16.04.2 lts

**Comment by Snipa22** [comment]
Your monero daemon isn't returning a BT blob.  Check to make sure you have a pool wallet address set, and that your XMR daemon is responding.

**Comment by berkbadem** [comment]
same problem for me, i checked xmr daemon with 

`curl -X POST http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getblocktemplate","params":{"wallet_address":"44GBHzv6ZyQdJkjqZje6KLZ3xSyN1hBSFAnLP6EAqJtCRVzMzZmeXTC2AHKDS9aEDTRKmo6a6o9r9j86pYfhCWDkKjbtcns","reserve_size":60}' -H 'Content-Type: application/json'`

output is : 
`{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockhashing_blob": "0505bf8cfaca05a81711a2aabe2093f6efabe3df94a18ecd2f65855d0103c5d7ef7d8d06e094fa0000000012a016873c411bae943a3a10245754184f1629ba34a87e74efc7445b41d6d51502",
    "blocktemplate_blob": "cfaca05a81711a2aabe2093f6efabe3df94a18ecd2f65855d0103c5d7ef7d8d06e094fa0000000002c2a75201ff86a75201ef88ee938ece01029e16e6d7f4731e791c51a27ac5649f780a4cb576d99f8a31f687b33c42bc2fa55f01d7d56088183219567db862716102bc8810544705bd677bd442da68d60b01faa4023c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000137f1ec8fbd8c0b8477a5dc7488c6187d9fa0a35bf7b4b6411a929db27492da0b",
    "difficulty": 13906700788,
    "height": 1348486,
    "prev_hash": "a81711a2aabe2093f6efabe3df94a18ecd2f65855d0103c5d7ef7d8d06e094fa",
    "reserved_offset": 130,
    "status": "OK"
  }
}`

**Comment by berkbadem** [comment]
@Klakloy 
login to mysql and check pool address with that query : 
`SELECT * FROM pool.config WHERE module='pool' AND item='address';`

then if its empty update it

**Comment by propercoil** [comment]
Probably the monero daemon stopped. Try:
`sudo systemctl restart monero`
