### ISSUE TITLE
API stopped updating

### ISSUE THREAD

**Issue by marlove** [Snipa22/nodejs-pool#92]
Hi there! For some reason the api suddenly stopped updating on my pool. I tried the steps described in the troubleshooting section and, as you can see, there is no valid PID under the Reader Table Status.
```
Environment Info
  Map address: (nil)
  Map size: 25769803776
  Page size: 4096
  Max pages: 6291456
  Number of pages used: 2510
  Last transaction ID: 144949
  Max readers: 512
  Number of readers used: 3
Reader Table Status
(no active readers)

```
Do you have any idea how to solve this problem? Just for your information the pool is https://www.xmrpool.xyz

Thank you for the support!

**Comment by marlove** [comment]
I understood what was the source of the problem, I enabled the https on Caddy and this for some reason breaks the application. Just to be clear I am not talking about the website. As consequence I also got a spike in the number of conntrack sessions (above 30K). At the moment I had to disable https in order to restore the pool. Do you know if I've to update some configuration files or the database when I enable https?

**Comment by Snipa22** [comment]
When changing to https, if you're putting the leafApi behind it, you'd want to ensure that the leafApi is updated in your database as well, if your remotes were using http://api.xmrpool.xyz/leafApi, as the system reads the http/https state to connect properly, and a 302 redirect won't play nicely w/ nodejs' http/https handlers.  With that fixed, it should sort itself naturally once you reboot the pool.

**Comment by marlove** [comment]
Thank you @Snipa22 for the quick reaction. Unfortunately I still experience the same issue even after updating the database and restarting the pool.

This is step by step what I did:
1. Update the value of general/shareHost with https://api.xmrpool.xyz/leafApi
2. Update Caddifile with the following content
```
https://api.xmrpool.xyz {
    proxy /leafApi 127.0.0.1:8000
    proxy / 127.0.0.1:8001
    proxy /socket.io 127.0.0.1:8001 {
        header_upstream Connection {>Connection}
        header_upstream Upgrade {>Upgrade}
    }
    header / {
        Access-Control-Allow-Methods "GET, POST, OPTIONS"
        Access-Control-Allow-Headers "Content-Type, x-access-token"
    }
    gzip
}

https://www.xmrpool.xyz {
    root /var/www
    gzip
    mime .manifest text/cache-manifest
}
```
3. Restarted caddy with
```
sudo systemctl stop caddy.service
sudo systemctl start caddy.service
```
4. Restarted the pool with
`pm2 restart all`
After the step number 4 the number of conntrack sessions rises quickly to 30K (the limit on my VPS). And of course the values returned by the stats api are 0.

Any further advices for me? Thank you again!

**Comment by marlove** [comment]
I tried out again and it worked.

**Comment by norlover** [comment]
@marlove 


Please tell me your answer
