### ISSUE TITLE
Can not login with Administrator/Password123 after clean install

### ISSUE THREAD

**Issue by Ernillew** [Snipa22/nodejs-pool#94]
Steps for reproduce
1. Deploy via installer
2. Read instruction and configure
3. Go http://IP/#/admin(Browser redirect to http://IP/#/home)
4. Press «Login» and enter «Administrator» in «Payment Address» field, enter «Password123» in «Password» field
5. See «Please check your login details» in login window

P.S.

`mysql> select * from pool.users;`
```
+----+---------------+------+-------------+-------+------------------+--------------+
| id | username      | pass | email       | admin | payout_threshold | enable_email |
+----+---------------+------+-------------+-------+------------------+--------------+
|  1 | Administrator | NULL | Password123 |     1 |                0 |            1 |
+----+---------------+------+-------------+-------+------------------+--------------+
```

**Comment by Snipa22** [comment]
Hello,

Please use http://IP/admin.html rather than /admin/

**Comment by Ogy** [comment]
same issue
