### ISSUE TITLE
xmt.to transactions

### ISSUE THREAD

**Issue by MineMoneroPRO** [Snipa22/nodejs-pool#95]
Transactions through xmr.to are sent, but the enduser does not receive them.

Here is the support answer:

> To avoid these happening in future, please make sure to either include a payment id, or to use integrated addresses, that you can now use through our api v2 - 
> http://xmrto-api.readthedocs.io/en/latest/api_v2.html

**Comment by Snipa22** [comment]
Xmr.to transactions include payment ID's.  Please check your xmrtoTxn table for these details, as it includes both the paymentID, Address, and the ID of the transaction so you can verify it.  If it's there with all those details, you should be able to cross-check your wallet and/or xmr.to for details.  If the user used xmr.to as their address, I can't help with that.
